-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity dsp_core_axis_top_fft128_real_zmpio_step1_kTwiddleRealQ15_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 16; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of dsp_core_axis_top_fft128_real_zmpio_step1_kTwiddleRealQ15_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0111111111111111", 1 => "0111111111011000", 2 => "0111111101100001", 3 => "0111111010011100", 
    4 => "0111110110001001", 5 => "0111110000101001", 6 => "0111101001111100", 7 => "0111100010000100", 
    8 => "0111011001000001", 9 => "0111001110110101", 10 => "0111000011100010", 11 => "0110110111001001", 
    12 => "0110101001101101", 13 => "0110011011001111", 14 => "0110001011110001", 15 => "0101111011010111", 
    16 => "0101101010000010", 17 => "0101010111110101", 18 => "0101000100110011", 19 => "0100110000111111", 
    20 => "0100011100011100", 21 => "0100000111001110", 22 => "0011110001010110", 23 => "0011011010111010", 
    24 => "0011000011111011", 25 => "0010101100011111", 26 => "0010010100101000", 27 => "0001111100011010", 
    28 => "0001100011111001", 29 => "0001001011001000", 30 => "0000110010001100", 31 => "0000011001001000", 
    32 => "0000000000000000", 33 => "1111100110111000", 34 => "1111001101110100", 35 => "1110110100111000", 
    36 => "1110011100000111", 37 => "1110000011100110", 38 => "1101101011011000", 39 => "1101010011100001", 
    40 => "1100111100000101", 41 => "1100100101000110", 42 => "1100001110101010", 43 => "1011111000110010", 
    44 => "1011100011100100", 45 => "1011001111000001", 46 => "1010111011001101", 47 => "1010101000001011", 
    48 => "1010010101111110", 49 => "1010000100101001", 50 => "1001110100001111", 51 => "1001100100110001", 
    52 => "1001010110010011", 53 => "1001001000110111", 54 => "1000111100011110", 55 => "1000110001001011", 
    56 => "1000100110111111", 57 => "1000011101111100", 58 => "1000010110000100", 59 => "1000001111010111", 
    60 => "1000001001110111", 61 => "1000000101100100", 62 => "1000000010011111", 63 => "1000000000101000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

