-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dsp_core_axis_top_push is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sample_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    sample_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    sample_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    sample_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
    core_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    core_ce0 : OUT STD_LOGIC;
    core_we0 : OUT STD_LOGIC_VECTOR (47 downto 0);
    core_d0 : OUT STD_LOGIC_VECTOR (383 downto 0);
    core_q0 : IN STD_LOGIC_VECTOR (383 downto 0);
    core_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    core_ce1 : OUT STD_LOGIC;
    core_we1 : OUT STD_LOGIC_VECTOR (47 downto 0);
    core_d1 : OUT STD_LOGIC_VECTOR (383 downto 0);
    core_q1 : IN STD_LOGIC_VECTOR (383 downto 0) );
end;


architecture behav of dsp_core_axis_top_push is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (23 downto 0) := "000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (23 downto 0) := "000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (23 downto 0) := "000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (23 downto 0) := "000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (23 downto 0) := "000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (23 downto 0) := "000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (23 downto 0) := "000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (23 downto 0) := "000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (23 downto 0) := "000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (23 downto 0) := "001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (23 downto 0) := "010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv34_0 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv63_4000000000000000 : STD_LOGIC_VECTOR (62 downto 0) := "100000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv48_FF000000 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000011111111000000000000000000000000";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv48_FF : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000011111111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv48_FF0000000000 : STD_LOGIC_VECTOR (47 downto 0) := "111111110000000000000000000000000000000000000000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv384_lc_1 : STD_LOGIC_VECTOR (383 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv48_10000 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000010000000000000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv48_FF00000000 : STD_LOGIC_VECTOR (47 downto 0) := "000000001111111100000000000000000000000000000000";
    constant ap_const_lv129_lc_2 : STD_LOGIC_VECTOR (128 downto 0) := "000000000000000000000000000000000000000000000000000000000000000010101010101010101010101010101010101010101010101010101010101010110";
    constant ap_const_lv15_AB : STD_LOGIC_VECTOR (14 downto 0) := "000000010101011";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv192_lc_3 : STD_LOGIC_VECTOR (191 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv48_3 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv34_4000 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000100000000000000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv20_F8000 : STD_LOGIC_VECTOR (19 downto 0) := "11111000000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_13E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111110";
    constant ap_const_lv32_17D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111101";
    constant ap_const_lv64_68 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000001101000";
    constant ap_const_lv48_F : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000001111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_146 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000110";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv320_lc_3 : STD_LOGIC_VECTOR (319 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv57_0 : STD_LOGIC_VECTOR (56 downto 0) := "000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv256_lc_3 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal zmpio_step1_kFirCoefficientsQ15_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal zmpio_step1_kFirCoefficientsQ15_ce0 : STD_LOGIC;
    signal zmpio_step1_kFirCoefficientsQ15_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_365_p2 : STD_LOGIC_VECTOR (128 downto 0);
    signal reg_353 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal mul_ln22_1_reg_377 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal reg_436 : STD_LOGIC_VECTOR (58 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal reg_440 : STD_LOGIC_VECTOR (57 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_16_fu_444_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_1368 : STD_LOGIC_VECTOR (0 downto 0);
    signal axis_1_reg_1407 : STD_LOGIC_VECTOR (1 downto 0);
    signal axis_fu_515_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal axis_reg_1414 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_521_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_1419 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln56_fu_552_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln56_reg_1431 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln56_fu_574_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln56_reg_1436 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_654_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_1441 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tap_fu_664_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tap_reg_1450 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal or_ln_fu_684_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln_reg_1455 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_20_fu_698_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_reg_1460 : STD_LOGIC_VECTOR (1 downto 0);
    signal accumulator_1_fu_929_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal sext_ln44_fu_977_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln44_reg_1481 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal tmp_22_reg_1514 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal and_ln_fu_1157_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln_reg_1519 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln95_fu_1313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln95_reg_1524 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal grp_build_frame_fu_400_ap_start : STD_LOGIC;
    signal grp_build_frame_fu_400_ap_done : STD_LOGIC;
    signal grp_build_frame_fu_400_ap_idle : STD_LOGIC;
    signal grp_build_frame_fu_400_ap_ready : STD_LOGIC;
    signal grp_build_frame_fu_400_core_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_build_frame_fu_400_core_ce0 : STD_LOGIC;
    signal grp_build_frame_fu_400_core_we0 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_build_frame_fu_400_core_d0 : STD_LOGIC_VECTOR (383 downto 0);
    signal tap_1_reg_342 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_build_frame_fu_400_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal zext_ln34_4_fu_588_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln38_1_fu_708_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln36_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln36_fu_670_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln90_4_fu_1177_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal phi_ln44_fu_232 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln33_fu_838_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln33_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal axis_2_fu_236 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal x_fu_240 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal output_0_fu_815_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_fu_244 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal z_fu_248 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal bit_fu_252 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    signal zext_ln50_fu_1003_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal icmp_ln49_fu_988_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_assign_18_fu_256 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal select_ln53_1_fu_1094_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal icmp_ln52_fu_1029_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_fu_260 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal result_3_fu_1086_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal bit_2_fu_264 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    signal zext_ln59_fu_1112_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln31_fu_476_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal zext_ln44_fu_536_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal shl_ln34_2_fu_647_p2 : STD_LOGIC_VECTOR (383 downto 0);
    signal shl_ln34_fu_628_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal shl_ln90_2_fu_1236_p2 : STD_LOGIC_VECTOR (383 downto 0);
    signal shl_ln90_fu_1217_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal zext_ln92_fu_1267_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal zext_ln93_fu_1286_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal zext_ln35_fu_1343_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal grp_fu_365_p0 : STD_LOGIC_VECTOR (64 downto 0);
    signal sext_ln19_fu_541_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln34_1_fu_580_p1 : STD_LOGIC_VECTOR (128 downto 0);
    signal zext_ln38_2_fu_693_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln189_fu_915_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln20_fu_938_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln21_fu_947_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln90_2_fu_1164_p1 : STD_LOGIC_VECTOR (128 downto 0);
    signal grp_fu_365_p1 : STD_LOGIC_VECTOR (66 downto 0);
    signal sext_ln38_2_fu_920_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln1_fu_452_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln31_fu_462_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln_fu_468_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal shl_ln1_fu_556_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln56_2_fu_567_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln56_fu_563_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln34_4_fu_601_p3 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln34_2_fu_609_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln34_3_fu_593_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln34_fu_613_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln34_fu_619_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln34_fu_624_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln34_1_fu_635_p3 : STD_LOGIC_VECTOR (66 downto 0);
    signal zext_ln34_fu_585_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal zext_ln34_3_fu_643_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal trunc_ln37_fu_675_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln56_fu_679_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_20_fu_698_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln12_fu_721_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln3_fu_727_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln14_fu_741_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln4_fu_747_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln14_1_fu_757_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_18_fu_713_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln14_1_fu_761_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln14_fu_737_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal select_ln11_fu_767_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_19_fu_775_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln27_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_fu_791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_fu_809_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_fu_801_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln33_fu_797_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln38_2_fu_862_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln38_3_fu_869_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln38_1_fu_855_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln38_fu_873_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln38_fu_879_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln38_fu_852_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln38_fu_883_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_21_fu_889_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln38_1_fu_897_p1 : STD_LOGIC_VECTOR (66 downto 0);
    signal zext_ln38_4_fu_901_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal lshr_ln38_fu_905_p2 : STD_LOGIC_VECTOR (383 downto 0);
    signal trunc_ln38_fu_911_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln38_3_fu_925_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln38_3_fu_925_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln22_fu_953_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln22_2_fu_961_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln22_fu_953_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln22_2_fu_961_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln22_fu_965_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln22_1_fu_957_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln22_1_fu_971_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln47_fu_984_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bit_4_fu_993_p4 : STD_LOGIC_VECTOR (60 downto 0);
    signal zext_ln44_1_fu_1038_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln53_fu_1042_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln53_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_2_fu_1066_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln55_fu_1076_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln53_fu_1054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_1_fu_1080_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln54_fu_1060_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bit_6_fu_1102_p4 : STD_LOGIC_VECTOR (60 downto 0);
    signal trunc_ln8_fu_1131_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln56_1_fu_1141_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln61_fu_1169_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln90_4_fu_1190_p3 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln90_1_fu_1198_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln90_3_fu_1182_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln90_fu_1202_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln90_fu_1208_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln90_fu_1213_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln90_1_fu_1224_p3 : STD_LOGIC_VECTOR (66 downto 0);
    signal zext_ln90_fu_1173_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal zext_ln90_3_fu_1232_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal trunc_ln_fu_1243_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln92_fu_1253_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln2_fu_1259_p3 : STD_LOGIC_VECTOR (326 downto 0);
    signal trunc_ln93_fu_1272_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln93_fu_1276_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_25_fu_1291_p4 : STD_LOGIC_VECTOR (56 downto 0);
    signal trunc_ln93_1_fu_1282_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln95_fu_1301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_fu_1307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2_fu_1319_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln35_fu_1329_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln3_fu_1335_p3 : STD_LOGIC_VECTOR (319 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dsp_core_axis_top_build_frame IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sample_sequence : IN STD_LOGIC_VECTOR (31 downto 0);
        core_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        core_ce0 : OUT STD_LOGIC;
        core_we0 : OUT STD_LOGIC_VECTOR (47 downto 0);
        core_d0 : OUT STD_LOGIC_VECTOR (383 downto 0);
        core_q0 : IN STD_LOGIC_VECTOR (383 downto 0) );
    end component;


    component dsp_core_axis_top_mul_65s_67s_129_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (64 downto 0);
        din1 : IN STD_LOGIC_VECTOR (66 downto 0);
        dout : OUT STD_LOGIC_VECTOR (128 downto 0) );
    end component;


    component dsp_core_axis_top_mux_3_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dsp_core_axis_top_push_zmpio_step1_kFirCoefficientsQ15_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;



begin
    zmpio_step1_kFirCoefficientsQ15_U : component dsp_core_axis_top_push_zmpio_step1_kFirCoefficientsQ15_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => zmpio_step1_kFirCoefficientsQ15_address0,
        ce0 => zmpio_step1_kFirCoefficientsQ15_ce0,
        q0 => zmpio_step1_kFirCoefficientsQ15_q0);

    grp_build_frame_fu_400 : component dsp_core_axis_top_build_frame
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_build_frame_fu_400_ap_start,
        ap_done => grp_build_frame_fu_400_ap_done,
        ap_idle => grp_build_frame_fu_400_ap_idle,
        ap_ready => grp_build_frame_fu_400_ap_ready,
        sample_sequence => sample_8_val,
        core_address0 => grp_build_frame_fu_400_core_address0,
        core_ce0 => grp_build_frame_fu_400_core_ce0,
        core_we0 => grp_build_frame_fu_400_core_we0,
        core_d0 => grp_build_frame_fu_400_core_d0,
        core_q0 => core_q0);

    mul_65s_67s_129_1_1_U22 : component dsp_core_axis_top_mul_65s_67s_129_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 65,
        din1_WIDTH => 67,
        dout_WIDTH => 129)
    port map (
        din0 => grp_fu_365_p0,
        din1 => grp_fu_365_p1,
        dout => grp_fu_365_p2);

    mux_3_2_16_1_1_U23 : component dsp_core_axis_top_mux_3_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => sample_0_val,
        din1 => sample_1_val,
        din2 => sample_2_val,
        din3 => axis_2_fu_236,
        dout => tmp_fu_521_p5);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_build_frame_fu_400_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_build_frame_fu_400_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                    grp_build_frame_fu_400_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_build_frame_fu_400_ap_ready = ap_const_logic_1)) then 
                    grp_build_frame_fu_400_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axis_2_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_16_fu_444_p3 = ap_const_lv1_0))) then 
                axis_2_fu_236 <= ap_const_lv2_0;
            elsif (((icmp_ln36_fu_658_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                axis_2_fu_236 <= axis_reg_1414;
            end if; 
        end if;
    end process;

    bit_2_fu_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_fu_988_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                                bit_2_fu_264(0) <= bit_fu_252(0);                bit_2_fu_264(2) <= bit_fu_252(2);                bit_2_fu_264(4) <= bit_fu_252(4);                bit_2_fu_264(6) <= bit_fu_252(6);                bit_2_fu_264(8) <= bit_fu_252(8);                bit_2_fu_264(10) <= bit_fu_252(10);                bit_2_fu_264(12) <= bit_fu_252(12);                bit_2_fu_264(14) <= bit_fu_252(14);                bit_2_fu_264(16) <= bit_fu_252(16);                bit_2_fu_264(18) <= bit_fu_252(18);                bit_2_fu_264(20) <= bit_fu_252(20);                bit_2_fu_264(22) <= bit_fu_252(22);                bit_2_fu_264(24) <= bit_fu_252(24);                bit_2_fu_264(26) <= bit_fu_252(26);                bit_2_fu_264(28) <= bit_fu_252(28);                bit_2_fu_264(30) <= bit_fu_252(30);                bit_2_fu_264(32) <= bit_fu_252(32);                bit_2_fu_264(34) <= bit_fu_252(34);                bit_2_fu_264(36) <= bit_fu_252(36);                bit_2_fu_264(38) <= bit_fu_252(38);                bit_2_fu_264(40) <= bit_fu_252(40);                bit_2_fu_264(42) <= bit_fu_252(42);                bit_2_fu_264(44) <= bit_fu_252(44);                bit_2_fu_264(46) <= bit_fu_252(46);                bit_2_fu_264(48) <= bit_fu_252(48);                bit_2_fu_264(50) <= bit_fu_252(50);                bit_2_fu_264(52) <= bit_fu_252(52);                bit_2_fu_264(54) <= bit_fu_252(54);                bit_2_fu_264(56) <= bit_fu_252(56);                bit_2_fu_264(58) <= bit_fu_252(58);                bit_2_fu_264(60) <= bit_fu_252(60);                bit_2_fu_264(62) <= bit_fu_252(62);
            elsif (((icmp_ln52_fu_1029_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                                bit_2_fu_264(0) <= zext_ln59_fu_1112_p1(0);                bit_2_fu_264(2) <= zext_ln59_fu_1112_p1(2);                bit_2_fu_264(4) <= zext_ln59_fu_1112_p1(4);                bit_2_fu_264(6) <= zext_ln59_fu_1112_p1(6);                bit_2_fu_264(8) <= zext_ln59_fu_1112_p1(8);                bit_2_fu_264(10) <= zext_ln59_fu_1112_p1(10);                bit_2_fu_264(12) <= zext_ln59_fu_1112_p1(12);                bit_2_fu_264(14) <= zext_ln59_fu_1112_p1(14);                bit_2_fu_264(16) <= zext_ln59_fu_1112_p1(16);                bit_2_fu_264(18) <= zext_ln59_fu_1112_p1(18);                bit_2_fu_264(20) <= zext_ln59_fu_1112_p1(20);                bit_2_fu_264(22) <= zext_ln59_fu_1112_p1(22);                bit_2_fu_264(24) <= zext_ln59_fu_1112_p1(24);                bit_2_fu_264(26) <= zext_ln59_fu_1112_p1(26);                bit_2_fu_264(28) <= zext_ln59_fu_1112_p1(28);                bit_2_fu_264(30) <= zext_ln59_fu_1112_p1(30);                bit_2_fu_264(32) <= zext_ln59_fu_1112_p1(32);                bit_2_fu_264(34) <= zext_ln59_fu_1112_p1(34);                bit_2_fu_264(36) <= zext_ln59_fu_1112_p1(36);                bit_2_fu_264(38) <= zext_ln59_fu_1112_p1(38);                bit_2_fu_264(40) <= zext_ln59_fu_1112_p1(40);                bit_2_fu_264(42) <= zext_ln59_fu_1112_p1(42);                bit_2_fu_264(44) <= zext_ln59_fu_1112_p1(44);                bit_2_fu_264(46) <= zext_ln59_fu_1112_p1(46);                bit_2_fu_264(48) <= zext_ln59_fu_1112_p1(48);                bit_2_fu_264(50) <= zext_ln59_fu_1112_p1(50);                bit_2_fu_264(52) <= zext_ln59_fu_1112_p1(52);                bit_2_fu_264(54) <= zext_ln59_fu_1112_p1(54);                bit_2_fu_264(56) <= zext_ln59_fu_1112_p1(56);                bit_2_fu_264(58) <= zext_ln59_fu_1112_p1(58);                bit_2_fu_264(60) <= zext_ln59_fu_1112_p1(60);                bit_2_fu_264(62) <= zext_ln59_fu_1112_p1(62);
            end if; 
        end if;
    end process;

    bit_fu_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln33_fu_509_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                bit_fu_252(0) <= '0';
                bit_fu_252(2) <= '0';
                bit_fu_252(4) <= '0';
                bit_fu_252(6) <= '0';
                bit_fu_252(8) <= '0';
                bit_fu_252(10) <= '0';
                bit_fu_252(12) <= '0';
                bit_fu_252(14) <= '0';
                bit_fu_252(16) <= '0';
                bit_fu_252(18) <= '0';
                bit_fu_252(20) <= '0';
                bit_fu_252(22) <= '0';
                bit_fu_252(24) <= '0';
                bit_fu_252(26) <= '0';
                bit_fu_252(28) <= '0';
                bit_fu_252(30) <= '0';
                bit_fu_252(32) <= '0';
                bit_fu_252(34) <= '0';
                bit_fu_252(36) <= '0';
                bit_fu_252(38) <= '0';
                bit_fu_252(40) <= '0';
                bit_fu_252(42) <= '0';
                bit_fu_252(44) <= '0';
                bit_fu_252(46) <= '0';
                bit_fu_252(48) <= '0';
                bit_fu_252(50) <= '0';
                bit_fu_252(52) <= '0';
                bit_fu_252(54) <= '0';
                bit_fu_252(56) <= '0';
                bit_fu_252(58) <= '0';
                bit_fu_252(60) <= '0';
                bit_fu_252(62) <= '1';
            elsif (((icmp_ln49_fu_988_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                                bit_fu_252(0) <= zext_ln50_fu_1003_p1(0);                bit_fu_252(2) <= zext_ln50_fu_1003_p1(2);                bit_fu_252(4) <= zext_ln50_fu_1003_p1(4);                bit_fu_252(6) <= zext_ln50_fu_1003_p1(6);                bit_fu_252(8) <= zext_ln50_fu_1003_p1(8);                bit_fu_252(10) <= zext_ln50_fu_1003_p1(10);                bit_fu_252(12) <= zext_ln50_fu_1003_p1(12);                bit_fu_252(14) <= zext_ln50_fu_1003_p1(14);                bit_fu_252(16) <= zext_ln50_fu_1003_p1(16);                bit_fu_252(18) <= zext_ln50_fu_1003_p1(18);                bit_fu_252(20) <= zext_ln50_fu_1003_p1(20);                bit_fu_252(22) <= zext_ln50_fu_1003_p1(22);                bit_fu_252(24) <= zext_ln50_fu_1003_p1(24);                bit_fu_252(26) <= zext_ln50_fu_1003_p1(26);                bit_fu_252(28) <= zext_ln50_fu_1003_p1(28);                bit_fu_252(30) <= zext_ln50_fu_1003_p1(30);                bit_fu_252(32) <= zext_ln50_fu_1003_p1(32);                bit_fu_252(34) <= zext_ln50_fu_1003_p1(34);                bit_fu_252(36) <= zext_ln50_fu_1003_p1(36);                bit_fu_252(38) <= zext_ln50_fu_1003_p1(38);                bit_fu_252(40) <= zext_ln50_fu_1003_p1(40);                bit_fu_252(42) <= zext_ln50_fu_1003_p1(42);                bit_fu_252(44) <= zext_ln50_fu_1003_p1(44);                bit_fu_252(46) <= zext_ln50_fu_1003_p1(46);                bit_fu_252(48) <= zext_ln50_fu_1003_p1(48);                bit_fu_252(50) <= zext_ln50_fu_1003_p1(50);                bit_fu_252(52) <= zext_ln50_fu_1003_p1(52);                bit_fu_252(54) <= zext_ln50_fu_1003_p1(54);                bit_fu_252(56) <= zext_ln50_fu_1003_p1(56);                bit_fu_252(58) <= zext_ln50_fu_1003_p1(58);                bit_fu_252(60) <= zext_ln50_fu_1003_p1(60);                bit_fu_252(62) <= zext_ln50_fu_1003_p1(62);
            end if; 
        end if;
    end process;

    phi_ln44_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_16_fu_444_p3 = ap_const_lv1_0))) then 
                phi_ln44_fu_232 <= ap_const_lv4_0;
            elsif (((icmp_ln36_fu_658_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                phi_ln44_fu_232 <= add_ln33_fu_838_p2;
            end if; 
        end if;
    end process;

    reg_353_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                reg_353 <= accumulator_1_fu_929_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                reg_353 <= ap_const_lv34_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                reg_353 <= grp_fu_365_p2(34 - 1 downto 0);
            end if; 
        end if;
    end process;

    result_fu_260_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_fu_988_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                result_fu_260 <= ap_const_lv64_0;
            elsif (((icmp_ln52_fu_1029_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                result_fu_260 <= result_3_fu_1086_p3;
            end if; 
        end if;
    end process;

    tap_1_reg_342_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                tap_1_reg_342 <= tap_reg_1450;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                tap_1_reg_342 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    value_assign_18_fu_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_fu_988_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                value_assign_18_fu_256 <= sext_ln44_reg_1481;
            elsif (((icmp_ln52_fu_1029_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                value_assign_18_fu_256 <= select_ln53_1_fu_1094_p3;
            end if; 
        end if;
    end process;

    x_fu_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_16_fu_444_p3 = ap_const_lv1_0))) then 
                x_fu_240 <= ap_const_lv16_0;
            elsif (((icmp_ln36_fu_658_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9) and (axis_1_reg_1407 = ap_const_lv2_0))) then 
                x_fu_240 <= output_0_fu_815_p3;
            end if; 
        end if;
    end process;

    y_fu_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_16_fu_444_p3 = ap_const_lv1_0))) then 
                y_fu_244 <= ap_const_lv16_0;
            elsif (((icmp_ln36_fu_658_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9) and (axis_1_reg_1407 = ap_const_lv2_1))) then 
                y_fu_244 <= output_0_fu_815_p3;
            end if; 
        end if;
    end process;

    z_fu_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_16_fu_444_p3 = ap_const_lv1_0))) then 
                z_fu_248 <= ap_const_lv16_0;
            elsif ((not((axis_1_reg_1407 = ap_const_lv2_1)) and not((axis_1_reg_1407 = ap_const_lv2_0)) and (icmp_ln36_fu_658_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                z_fu_248 <= output_0_fu_815_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    add_ln56_reg_1436(63 downto 1) <= add_ln56_fu_574_p2(63 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                and_ln95_reg_1524 <= and_ln95_fu_1313_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                    and_ln_reg_1519(63 downto 2) <= and_ln_fu_1157_p3(63 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                axis_1_reg_1407 <= axis_2_fu_236;
                axis_reg_1414 <= axis_fu_515_p2;
                tmp_reg_1419 <= tmp_fu_521_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                empty_reg_1441 <= empty_fu_654_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                mul_ln22_1_reg_377 <= grp_fu_365_p2(32 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                    or_ln_reg_1455(6 downto 1) <= or_ln_fu_684_p4(6 downto 1);
                tap_reg_1450 <= tap_fu_664_p2;
                tmp_20_reg_1460 <= tmp_20_fu_698_p1(14 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state5))) then
                reg_436 <= grp_fu_365_p2(128 downto 70);
                reg_440 <= grp_fu_365_p2(127 downto 70);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                sext_ln44_reg_1481 <= sext_ln44_fu_977_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_16_reg_1368 <= core_q0(128 downto 128);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                tmp_22_reg_1514 <= add_ln56_1_fu_1141_p2(63 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                trunc_ln56_reg_1431 <= trunc_ln56_fu_552_p1;
            end if;
        end if;
    end process;
    add_ln56_reg_1436(0) <= '0';
    or_ln_reg_1455(0) <= '0';
    and_ln_reg_1519(1 downto 0) <= "00";
    bit_fu_252(1) <= '0';
    bit_fu_252(3 downto 3) <= "0";
    bit_fu_252(5 downto 5) <= "0";
    bit_fu_252(7 downto 7) <= "0";
    bit_fu_252(9 downto 9) <= "0";
    bit_fu_252(11 downto 11) <= "0";
    bit_fu_252(13 downto 13) <= "0";
    bit_fu_252(15 downto 15) <= "0";
    bit_fu_252(17 downto 17) <= "0";
    bit_fu_252(19 downto 19) <= "0";
    bit_fu_252(21 downto 21) <= "0";
    bit_fu_252(23 downto 23) <= "0";
    bit_fu_252(25 downto 25) <= "0";
    bit_fu_252(27 downto 27) <= "0";
    bit_fu_252(29 downto 29) <= "0";
    bit_fu_252(31 downto 31) <= "0";
    bit_fu_252(33 downto 33) <= "0";
    bit_fu_252(35 downto 35) <= "0";
    bit_fu_252(37 downto 37) <= "0";
    bit_fu_252(39 downto 39) <= "0";
    bit_fu_252(41 downto 41) <= "0";
    bit_fu_252(43 downto 43) <= "0";
    bit_fu_252(45 downto 45) <= "0";
    bit_fu_252(47 downto 47) <= "0";
    bit_fu_252(49 downto 49) <= "0";
    bit_fu_252(51 downto 51) <= "0";
    bit_fu_252(53 downto 53) <= "0";
    bit_fu_252(55 downto 55) <= "0";
    bit_fu_252(57 downto 57) <= "0";
    bit_fu_252(59 downto 59) <= "0";
    bit_fu_252(61) <= '0';
    bit_2_fu_264(1) <= '0';
    bit_2_fu_264(3 downto 3) <= "0";
    bit_2_fu_264(5 downto 5) <= "0";
    bit_2_fu_264(7 downto 7) <= "0";
    bit_2_fu_264(9 downto 9) <= "0";
    bit_2_fu_264(11 downto 11) <= "0";
    bit_2_fu_264(13 downto 13) <= "0";
    bit_2_fu_264(15 downto 15) <= "0";
    bit_2_fu_264(17 downto 17) <= "0";
    bit_2_fu_264(19 downto 19) <= "0";
    bit_2_fu_264(21 downto 21) <= "0";
    bit_2_fu_264(23 downto 23) <= "0";
    bit_2_fu_264(25 downto 25) <= "0";
    bit_2_fu_264(27 downto 27) <= "0";
    bit_2_fu_264(29 downto 29) <= "0";
    bit_2_fu_264(31 downto 31) <= "0";
    bit_2_fu_264(33 downto 33) <= "0";
    bit_2_fu_264(35 downto 35) <= "0";
    bit_2_fu_264(37 downto 37) <= "0";
    bit_2_fu_264(39 downto 39) <= "0";
    bit_2_fu_264(41 downto 41) <= "0";
    bit_2_fu_264(43 downto 43) <= "0";
    bit_2_fu_264(45 downto 45) <= "0";
    bit_2_fu_264(47 downto 47) <= "0";
    bit_2_fu_264(49 downto 49) <= "0";
    bit_2_fu_264(51 downto 51) <= "0";
    bit_2_fu_264(53 downto 53) <= "0";
    bit_2_fu_264(55 downto 55) <= "0";
    bit_2_fu_264(57 downto 57) <= "0";
    bit_2_fu_264(59 downto 59) <= "0";
    bit_2_fu_264(61) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state2, tmp_16_fu_444_p3, ap_CS_fsm_state9, and_ln95_fu_1313_p2, ap_CS_fsm_state19, grp_build_frame_fu_400_ap_done, ap_CS_fsm_state21, icmp_ln36_fu_658_p2, icmp_ln33_fu_509_p2, ap_CS_fsm_state13, icmp_ln49_fu_988_p2, ap_CS_fsm_state14, icmp_ln52_fu_1029_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_16_fu_444_p3 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state24;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln33_fu_509_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((icmp_ln36_fu_658_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((icmp_ln49_fu_988_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                if (((icmp_ln52_fu_1029_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                if (((ap_const_lv1_0 = and_ln95_fu_1313_p2) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state24;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state21) and (grp_build_frame_fu_400_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_state21;
                end if;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    accumulator_1_fu_929_p2 <= std_logic_vector(signed(sext_ln38_3_fu_925_p1) + signed(reg_353));
    add_ln12_fu_721_p2 <= std_logic_vector(unsigned(reg_353) + unsigned(ap_const_lv34_4000));
    add_ln22_1_fu_971_p2 <= std_logic_vector(unsigned(add_ln22_fu_965_p2) + unsigned(sext_ln22_1_fu_957_p1));
    add_ln22_fu_965_p2 <= std_logic_vector(signed(sext_ln22_fu_953_p1) + signed(sext_ln22_2_fu_961_p1));
    add_ln31_fu_462_p2 <= std_logic_vector(unsigned(trunc_ln1_fu_452_p4) + unsigned(ap_const_lv64_1));
    add_ln33_fu_838_p2 <= std_logic_vector(unsigned(empty_reg_1441) + unsigned(ap_const_lv4_1));
    add_ln34_fu_619_p2 <= std_logic_vector(unsigned(add_ln56_reg_1436) + unsigned(sub_ln34_fu_613_p2));
    add_ln35_fu_1329_p2 <= std_logic_vector(unsigned(trunc_ln2_fu_1319_p4) + unsigned(ap_const_lv64_1));
    add_ln38_fu_883_p2 <= std_logic_vector(signed(sext_ln38_fu_879_p1) + signed(zext_ln38_fu_852_p1));
    add_ln53_fu_1042_p2 <= std_logic_vector(unsigned(result_fu_260) + unsigned(zext_ln44_1_fu_1038_p1));
    add_ln56_1_fu_1141_p2 <= std_logic_vector(unsigned(trunc_ln8_fu_1131_p4) + unsigned(ap_const_lv64_68));
    add_ln56_fu_574_p2 <= std_logic_vector(unsigned(shl_ln56_2_fu_567_p3) + unsigned(zext_ln56_fu_563_p1));
    add_ln90_fu_1208_p2 <= std_logic_vector(unsigned(and_ln_reg_1519) + unsigned(sub_ln90_fu_1202_p2));
    add_ln92_fu_1253_p2 <= std_logic_vector(unsigned(trunc_ln_fu_1243_p4) + unsigned(ap_const_lv7_1));
    add_ln93_fu_1276_p2 <= std_logic_vector(unsigned(trunc_ln93_fu_1272_p1) + unsigned(ap_const_lv64_1));
    and_ln95_fu_1313_p2 <= (icmp_ln96_fu_1307_p2 and icmp_ln95_fu_1301_p2);
    and_ln_fu_1157_p3 <= (tmp_22_reg_1514 & ap_const_lv2_0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;

    ap_ST_fsm_state21_blk_assign_proc : process(grp_build_frame_fu_400_ap_done)
    begin
        if ((grp_build_frame_fu_400_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state21_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state21_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state24)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state24) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state24)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    axis_fu_515_p2 <= std_logic_vector(unsigned(axis_2_fu_236) + unsigned(ap_const_lv2_1));
    bit_4_fu_993_p4 <= bit_fu_252(62 downto 2);
    bit_6_fu_1102_p4 <= bit_2_fu_264(62 downto 2);

    core_address0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state19, grp_build_frame_fu_400_core_address0, ap_CS_fsm_state21, zext_ln34_4_fu_588_p1, ap_CS_fsm_state6, zext_ln38_1_fu_708_p1, zext_ln90_4_fu_1177_p1, ap_CS_fsm_state17, icmp_ln33_fu_509_p2, ap_CS_fsm_state14, ap_CS_fsm_state7, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            core_address0 <= ap_const_lv4_D;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            core_address0 <= zext_ln90_4_fu_1177_p1(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state19))) then 
            core_address0 <= ap_const_lv4_C;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            core_address0 <= zext_ln38_1_fu_708_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            core_address0 <= zext_ln34_4_fu_588_p1(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or ((icmp_ln33_fu_509_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((icmp_ln33_fu_509_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            core_address0 <= ap_const_lv4_2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            core_address0 <= ap_const_lv4_E;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            core_address0 <= grp_build_frame_fu_400_core_address0;
        else 
            core_address0 <= "XXXX";
        end if; 
    end process;


    core_address1_assign_proc : process(ap_CS_fsm_state19, ap_CS_fsm_state18, ap_CS_fsm_state22, ap_CS_fsm_state23, ap_CS_fsm_state24)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state22))) then 
            core_address1 <= ap_const_lv4_E;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            core_address1 <= ap_const_lv4_D;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            core_address1 <= ap_const_lv4_C;
        else 
            core_address1 <= "XXXX";
        end if; 
    end process;


    core_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state19, grp_build_frame_fu_400_core_ce0, ap_CS_fsm_state21, ap_CS_fsm_state6, ap_CS_fsm_state17, icmp_ln33_fu_509_p2, ap_CS_fsm_state14, ap_CS_fsm_state7, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((icmp_ln33_fu_509_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln33_fu_509_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            core_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            core_ce0 <= grp_build_frame_fu_400_core_ce0;
        else 
            core_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    core_ce1_assign_proc : process(ap_CS_fsm_state19, ap_CS_fsm_state18, ap_CS_fsm_state22, ap_CS_fsm_state23, ap_CS_fsm_state24)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state19))) then 
            core_ce1 <= ap_const_logic_1;
        else 
            core_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    core_d0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state2, ap_CS_fsm_state19, grp_build_frame_fu_400_core_d0, ap_CS_fsm_state21, ap_CS_fsm_state6, ap_CS_fsm_state17, icmp_ln33_fu_509_p2, zext_ln31_fu_476_p1, zext_ln44_fu_536_p1, shl_ln34_2_fu_647_p2, shl_ln90_2_fu_1236_p2, zext_ln92_fu_1267_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            core_d0 <= zext_ln92_fu_1267_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            core_d0 <= shl_ln90_2_fu_1236_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            core_d0 <= shl_ln34_2_fu_647_p2;
        elsif (((icmp_ln33_fu_509_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            core_d0 <= zext_ln44_fu_536_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            core_d0 <= zext_ln31_fu_476_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            core_d0 <= grp_build_frame_fu_400_core_d0;
        else 
            core_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    core_d1_assign_proc : process(ap_CS_fsm_state19, zext_ln93_fu_1286_p1, ap_CS_fsm_state22, ap_CS_fsm_state24, zext_ln35_fu_1343_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            core_d1 <= zext_ln35_fu_1343_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            core_d1 <= ap_const_lv384_lc_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            core_d1 <= zext_ln93_fu_1286_p1;
        else 
            core_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    core_we0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state2, tmp_16_fu_444_p3, ap_CS_fsm_state19, grp_build_frame_fu_400_core_we0, ap_CS_fsm_state21, ap_CS_fsm_state6, ap_CS_fsm_state17, icmp_ln33_fu_509_p2, shl_ln34_fu_628_p2, shl_ln90_fu_1217_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            core_we0 <= ap_const_lv48_FF0000000000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            core_we0 <= shl_ln90_fu_1217_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            core_we0 <= shl_ln34_fu_628_p2;
        elsif (((icmp_ln33_fu_509_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            core_we0 <= ap_const_lv48_FF;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_16_fu_444_p3 = ap_const_lv1_0))) then 
            core_we0 <= ap_const_lv48_FF000000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            core_we0 <= grp_build_frame_fu_400_core_we0;
        else 
            core_we0 <= ap_const_lv48_0;
        end if; 
    end process;


    core_we1_assign_proc : process(tmp_16_reg_1368, and_ln95_reg_1524, ap_CS_fsm_state19, ap_CS_fsm_state22, ap_CS_fsm_state24)
    begin
        if (((ap_const_lv1_1 = and_ln95_reg_1524) and (ap_const_logic_1 = ap_CS_fsm_state24) and (tmp_16_reg_1368 = ap_const_lv1_0))) then 
            core_we1 <= ap_const_lv48_FF00000000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            core_we1 <= ap_const_lv48_10000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            core_we1 <= ap_const_lv48_FF;
        else 
            core_we1 <= ap_const_lv48_0;
        end if; 
    end process;

    empty_fu_654_p1 <= core_q0(4 - 1 downto 0);
    grp_build_frame_fu_400_ap_start <= grp_build_frame_fu_400_ap_start_reg;

    grp_fu_365_p0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state11, ap_CS_fsm_state5, ap_CS_fsm_state16, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state12, sext_ln19_fu_541_p1, zext_ln34_1_fu_580_p1, zext_ln38_2_fu_693_p1, sext_ln189_fu_915_p1, sext_ln20_fu_938_p1, sext_ln21_fu_947_p1, zext_ln90_2_fu_1164_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            grp_fu_365_p0 <= zext_ln90_2_fu_1164_p1(65 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_365_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln21_fu_947_p1),65));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_365_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln20_fu_938_p1),65));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_365_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln189_fu_915_p1),65));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_365_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(zext_ln38_2_fu_693_p1),65));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_365_p0 <= zext_ln34_1_fu_580_p1(65 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_365_p0 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln19_fu_541_p1),65));
        else 
            grp_fu_365_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_365_p1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state11, ap_CS_fsm_state5, ap_CS_fsm_state16, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state12, sext_ln19_fu_541_p1, sext_ln20_fu_938_p1, sext_ln21_fu_947_p1, sext_ln38_2_fu_920_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln21_fu_947_p1),67));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln20_fu_938_p1),67));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln38_2_fu_920_p1),67));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_const_lv15_AB),67));
        elsif (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            grp_fu_365_p1 <= ap_const_lv129_lc_2(67 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln19_fu_541_p1),67));
        else 
            grp_fu_365_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln27_fu_785_p2 <= "1" when (signed(tmp_19_fu_775_p4) > signed(ap_const_lv5_0)) else "0";
    icmp_ln30_fu_791_p2 <= "1" when (signed(select_ln11_fu_767_p3) < signed(ap_const_lv20_F8000)) else "0";
    icmp_ln33_fu_509_p2 <= "1" when (axis_2_fu_236 = ap_const_lv2_3) else "0";
    icmp_ln36_fu_658_p2 <= "1" when (tap_1_reg_342 = ap_const_lv5_10) else "0";
    icmp_ln49_fu_988_p2 <= "1" when (unsigned(zext_ln47_fu_984_p1) > unsigned(sext_ln44_reg_1481)) else "0";
    icmp_ln52_fu_1029_p2 <= "1" when (bit_2_fu_264 = ap_const_lv63_0) else "0";
    icmp_ln53_fu_1048_p2 <= "1" when (unsigned(value_assign_18_fu_256) < unsigned(add_ln53_fu_1042_p2)) else "0";
    icmp_ln95_fu_1301_p2 <= "0" when (tmp_25_fu_1291_p4 = ap_const_lv57_0) else "1";
    icmp_ln96_fu_1307_p2 <= "1" when (trunc_ln93_1_fu_1282_p1 = ap_const_lv6_0) else "0";
    lshr_ln38_fu_905_p2 <= std_logic_vector(shift_right(unsigned(core_q0),to_integer(unsigned('0' & zext_ln38_4_fu_901_p1(31-1 downto 0)))));
    or_ln27_fu_809_p2 <= (icmp_ln30_fu_791_p2 or icmp_ln27_fu_785_p2);
    or_ln_fu_684_p4 <= ((axis_2_fu_236 & sub_ln56_fu_679_p2) & ap_const_lv1_0);
    output_0_fu_815_p3 <= 
        select_ln27_fu_801_p3 when (or_ln27_fu_809_p2(0) = '1') else 
        trunc_ln33_fu_797_p1;
    result_1_fu_1080_p2 <= std_logic_vector(unsigned(zext_ln55_fu_1076_p1) + unsigned(zext_ln44_1_fu_1038_p1));
    result_2_fu_1066_p4 <= result_fu_260(63 downto 1);
    result_3_fu_1086_p3 <= 
        result_1_fu_1080_p2 when (xor_ln53_fu_1054_p2(0) = '1') else 
        zext_ln55_fu_1076_p1;
    select_ln11_fu_767_p3 <= 
        sub_ln14_1_fu_761_p2 when (tmp_18_fu_713_p3(0) = '1') else 
        sext_ln14_fu_737_p1;
    select_ln27_fu_801_p3 <= 
        ap_const_lv16_7FFF when (icmp_ln27_fu_785_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln53_1_fu_1094_p3 <= 
        sub_ln54_fu_1060_p2 when (xor_ln53_fu_1054_p2(0) = '1') else 
        value_assign_18_fu_256;
        sext_ln14_1_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln4_fu_747_p4),20));

        sext_ln14_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln3_fu_727_p4),20));

        sext_ln189_fu_915_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln38_fu_911_p1),31));

        sext_ln19_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_fu_240),32));

        sext_ln20_fu_938_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(y_fu_244),32));

        sext_ln21_fu_947_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(z_fu_248),32));

        sext_ln22_1_fu_957_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln22_1_reg_377),33));

    sext_ln22_2_fu_961_p0 <= grp_fu_365_p2(32 - 1 downto 0);
        sext_ln22_2_fu_961_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln22_2_fu_961_p0),33));

    sext_ln22_fu_953_p0 <= reg_353(32 - 1 downto 0);
        sext_ln22_fu_953_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln22_fu_953_p0),33));

        sext_ln38_1_fu_897_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_21_fu_889_p3),67));

        sext_ln38_2_fu_920_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(zmpio_step1_kFirCoefficientsQ15_q0),31));

    sext_ln38_3_fu_925_p0 <= grp_fu_365_p2(31 - 1 downto 0);
        sext_ln38_3_fu_925_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln38_3_fu_925_p0),34));

        sext_ln38_fu_879_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_fu_873_p2),9));

        sext_ln44_fu_977_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln22_1_fu_971_p2),64));

    shl_ln1_fu_556_p3 <= (axis_2_fu_236 & ap_const_lv5_0);
    shl_ln2_fu_1259_p3 <= (add_ln92_fu_1253_p2 & ap_const_lv320_lc_3);
    shl_ln34_1_fu_635_p3 <= (add_ln34_fu_619_p2 & ap_const_lv3_0);
    shl_ln34_2_fu_647_p2 <= std_logic_vector(shift_left(unsigned(zext_ln34_fu_585_p1),to_integer(unsigned('0' & zext_ln34_3_fu_643_p1(31-1 downto 0)))));
    shl_ln34_3_fu_593_p3 <= (reg_440 & ap_const_lv6_0);
    shl_ln34_4_fu_601_p3 <= (reg_436 & ap_const_lv4_0);
    shl_ln34_fu_628_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv48_3),to_integer(unsigned('0' & trunc_ln34_fu_624_p1(31-1 downto 0)))));
    shl_ln38_1_fu_855_p3 <= (tmp_20_reg_1460 & ap_const_lv6_0);
    shl_ln38_2_fu_862_p3 <= (tmp_20_reg_1460 & ap_const_lv4_0);
    shl_ln3_fu_1335_p3 <= (add_ln35_fu_1329_p2 & ap_const_lv256_lc_3);
    shl_ln56_2_fu_567_p3 <= (trunc_ln56_reg_1431 & ap_const_lv1_0);
    shl_ln90_1_fu_1224_p3 <= (add_ln90_fu_1208_p2 & ap_const_lv3_0);
    shl_ln90_2_fu_1236_p2 <= std_logic_vector(shift_left(unsigned(zext_ln90_fu_1173_p1),to_integer(unsigned('0' & zext_ln90_3_fu_1232_p1(31-1 downto 0)))));
    shl_ln90_3_fu_1182_p3 <= (reg_440 & ap_const_lv6_0);
    shl_ln90_4_fu_1190_p3 <= (reg_436 & ap_const_lv4_0);
    shl_ln90_fu_1217_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv48_F),to_integer(unsigned('0' & trunc_ln90_fu_1213_p1(31-1 downto 0)))));
    shl_ln_fu_468_p3 <= (add_ln31_fu_462_p2 & ap_const_lv192_lc_3);
    sub_ln14_1_fu_761_p2 <= std_logic_vector(unsigned(ap_const_lv20_0) - unsigned(sext_ln14_1_fu_757_p1));
    sub_ln14_fu_741_p2 <= std_logic_vector(unsigned(ap_const_lv34_4000) - unsigned(reg_353));
    sub_ln34_fu_613_p2 <= std_logic_vector(unsigned(zext_ln34_2_fu_609_p1) - unsigned(shl_ln34_3_fu_593_p3));
    sub_ln38_fu_873_p2 <= std_logic_vector(unsigned(zext_ln38_3_fu_869_p1) - unsigned(shl_ln38_1_fu_855_p3));
    sub_ln54_fu_1060_p2 <= std_logic_vector(unsigned(value_assign_18_fu_256) - unsigned(add_ln53_fu_1042_p2));
    sub_ln56_fu_679_p2 <= std_logic_vector(unsigned(empty_reg_1441) - unsigned(trunc_ln37_fu_675_p1));
    sub_ln90_fu_1202_p2 <= std_logic_vector(unsigned(zext_ln90_1_fu_1198_p1) - unsigned(shl_ln90_3_fu_1182_p3));
    tap_fu_664_p2 <= std_logic_vector(unsigned(tap_1_reg_342) + unsigned(ap_const_lv5_1));
    tmp_16_fu_444_p3 <= core_q0(128 downto 128);
    tmp_18_fu_713_p3 <= reg_353(33 downto 33);
    tmp_19_fu_775_p4 <= select_ln11_fu_767_p3(19 downto 15);
    tmp_20_fu_698_p1 <= grp_fu_365_p2(15 - 1 downto 0);
    tmp_20_fu_698_p4 <= tmp_20_fu_698_p1(14 downto 13);
    tmp_21_fu_889_p3 <= (add_ln38_fu_883_p2 & ap_const_lv3_0);
    tmp_25_fu_1291_p4 <= add_ln93_fu_1276_p2(63 downto 7);
    trunc_ln1_fu_452_p4 <= core_q0(255 downto 192);
    trunc_ln2_fu_1319_p4 <= core_q1(319 downto 256);
    trunc_ln33_fu_797_p1 <= select_ln11_fu_767_p3(16 - 1 downto 0);
    trunc_ln34_fu_624_p1 <= add_ln34_fu_619_p2(48 - 1 downto 0);
    trunc_ln37_fu_675_p1 <= tap_1_reg_342(4 - 1 downto 0);
    trunc_ln38_fu_911_p1 <= lshr_ln38_fu_905_p2(16 - 1 downto 0);
    trunc_ln3_fu_727_p4 <= add_ln12_fu_721_p2(33 downto 15);
    trunc_ln4_fu_747_p4 <= sub_ln14_fu_741_p2(33 downto 15);
    trunc_ln56_fu_552_p1 <= core_q0(63 - 1 downto 0);
    trunc_ln61_fu_1169_p1 <= result_fu_260(32 - 1 downto 0);
    trunc_ln8_fu_1131_p4 <= core_q0(381 downto 318);
    trunc_ln90_fu_1213_p1 <= add_ln90_fu_1208_p2(48 - 1 downto 0);
    trunc_ln93_1_fu_1282_p1 <= add_ln93_fu_1276_p2(6 - 1 downto 0);
    trunc_ln93_fu_1272_p1 <= core_q0(64 - 1 downto 0);
    trunc_ln_fu_1243_p4 <= core_q1(326 downto 320);
    xor_ln53_fu_1054_p2 <= (icmp_ln53_fu_1048_p2 xor ap_const_lv1_1);
    zext_ln31_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_468_p3),384));
    zext_ln34_1_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_fu_574_p2),129));
    zext_ln34_2_fu_609_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln34_4_fu_601_p3),64));
    zext_ln34_3_fu_643_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln34_1_fu_635_p3),384));
    zext_ln34_4_fu_588_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_436),64));
    zext_ln34_fu_585_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_1419),384));
    zext_ln35_fu_1343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln3_fu_1335_p3),384));
    zext_ln36_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tap_1_reg_342),64));
    zext_ln38_1_fu_708_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_20_fu_698_p4),64));
    zext_ln38_2_fu_693_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_684_p4),15));
    zext_ln38_3_fu_869_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln38_2_fu_862_p3),8));
    zext_ln38_4_fu_901_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln38_1_fu_897_p1),384));
    zext_ln38_fu_852_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_reg_1455),9));
    zext_ln44_1_fu_1038_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bit_2_fu_264),64));
    zext_ln44_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(phi_ln44_fu_232),384));
    zext_ln47_fu_984_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bit_fu_252),64));
    zext_ln50_fu_1003_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bit_4_fu_993_p4),63));
    zext_ln55_fu_1076_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_2_fu_1066_p4),64));
    zext_ln56_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_556_p3),64));
    zext_ln59_fu_1112_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bit_6_fu_1102_p4),63));
    zext_ln90_1_fu_1198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln90_4_fu_1190_p3),64));
    zext_ln90_2_fu_1164_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln_fu_1157_p3),129));
    zext_ln90_3_fu_1232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln90_1_fu_1224_p3),384));
    zext_ln90_4_fu_1177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_436),64));
    zext_ln90_fu_1173_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln61_fu_1169_p1),384));
    zext_ln92_fu_1267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_1259_p3),384));
    zext_ln93_fu_1286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_fu_1276_p2),384));
    zmpio_step1_kFirCoefficientsQ15_address0 <= zext_ln36_fu_670_p1(4 - 1 downto 0);

    zmpio_step1_kFirCoefficientsQ15_ce0_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            zmpio_step1_kFirCoefficientsQ15_ce0 <= ap_const_logic_1;
        else 
            zmpio_step1_kFirCoefficientsQ15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
