-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dsp_core_axis_top_fft128_real is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_real_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    output_real_ce0 : OUT STD_LOGIC;
    output_real_we0 : OUT STD_LOGIC;
    output_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_real_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_imag_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    output_imag_ce0 : OUT STD_LOGIC;
    output_imag_we0 : OUT STD_LOGIC;
    output_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_imag_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of dsp_core_axis_top_fft128_real is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (24 downto 0) := "0000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (24 downto 0) := "0000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (24 downto 0) := "0000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (24 downto 0) := "0000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (24 downto 0) := "0000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (24 downto 0) := "0000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (24 downto 0) := "0001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (24 downto 0) := "0010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (24 downto 0) := "0100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv9_2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv9_81 : STD_LOGIC_VECTOR (8 downto 0) := "010000001";
    constant ap_const_lv9_80 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv47_4000 : STD_LOGIC_VECTOR (46 downto 0) := "00000000000000000000000000000000100000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv33_1 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal zmpio_step1_kTwiddleRealQ15_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal zmpio_step1_kTwiddleRealQ15_ce0 : STD_LOGIC;
    signal zmpio_step1_kTwiddleRealQ15_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal zmpio_step1_kTwiddleImagQ15_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal zmpio_step1_kTwiddleImagQ15_ce0 : STD_LOGIC;
    signal zmpio_step1_kTwiddleImagQ15_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_258_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal reg_213 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal index_fu_295_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal index_reg_870 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln39_fu_301_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln39_reg_875 : STD_LOGIC_VECTOR (63 downto 0);
    signal input_load_reg_892 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln15_fu_317_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal reversed_1_fu_340_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln43_fu_373_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln43_reg_916 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal trunc_ln_reg_921 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln50_fu_385_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln50_reg_927 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln46_fu_397_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln46_reg_935 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal offset_1_fu_416_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal offset_1_reg_943 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal add_ln48_fu_422_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln48_reg_948 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln50_1_fu_438_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln50_1_reg_953 : STD_LOGIC_VECTOR (5 downto 0);
    signal output_real_addr_2_reg_958 : STD_LOGIC_VECTOR (6 downto 0);
    signal output_imag_addr_2_reg_968 : STD_LOGIC_VECTOR (6 downto 0);
    signal base_1_fu_449_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln189_fu_454_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln189_reg_983 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln27_fu_459_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln27_reg_988 : STD_LOGIC_VECTOR (47 downto 0);
    signal zmpio_step1_kTwiddleImagQ15_load_reg_993 : STD_LOGIC_VECTOR (15 downto 0);
    signal output_real_addr_1_reg_998 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal output_imag_addr_1_reg_1003 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln56_fu_469_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln56_reg_1008 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln28_fu_474_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln28_reg_1013 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln26_fu_484_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal trunc_ln26_reg_1018 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_26_reg_1024 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln19_2_fu_660_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln19_2_reg_1029 : STD_LOGIC_VECTOR (31 downto 0);
    signal odd_imag_fu_724_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal odd_imag_reg_1034 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal select_ln19_3_fu_852_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln19_3_reg_1039 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal bit_reg_202 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln15_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal base_reg_224 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln47_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal offset_reg_236 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_389_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal index_4_reg_247 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln39_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln15_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln50_fu_432_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_fu_443_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_fu_464_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal index_3_fu_98 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal span_fu_102 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal span_2_fu_401_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal select_ln19_fu_599_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln19_1_fu_791_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_258_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_258_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln15_1_fu_323_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln16_fu_327_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln16_1_fu_336_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln16_1_fu_336_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln16_fu_332_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln15_fu_348_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_367_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln50_fu_427_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln189_fu_454_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln56_fu_469_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal real_fu_478_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln12_fu_496_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal sub_ln14_fu_511_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal trunc_ln4_fu_516_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln14_1_fu_526_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln3_fu_501_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln52_fu_539_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal odd_real_fu_532_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln52_1_fu_543_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln52_fu_539_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln52_fu_547_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln20_fu_561_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln22_fu_577_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln6_fu_583_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_28_fu_553_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln22_1_fu_593_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln5_fu_567_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln56_fu_608_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln20_2_fu_622_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln22_4_fu_638_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln22_2_fu_644_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_30_fu_614_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln22_5_fu_654_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln20_2_fu_628_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_fu_668_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln29_fu_674_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal add_ln12_1_fu_686_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal sub_ln14_2_fu_702_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal trunc_ln14_1_fu_708_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_27_fu_678_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln14_3_fu_718_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln12_1_fu_692_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln53_fu_732_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln53_1_fu_736_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln53_fu_732_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln53_fu_739_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln20_1_fu_753_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln22_2_fu_769_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln22_1_fu_775_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_fu_745_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln22_3_fu_785_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln20_1_fu_759_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln57_fu_800_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln20_3_fu_814_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln22_6_fu_830_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln22_3_fu_836_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_31_fu_806_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln22_7_fu_846_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln20_3_fu_820_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln43_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_367_ap_start : STD_LOGIC;
    signal grp_fu_367_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dsp_core_axis_top_mul_32s_16s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component dsp_core_axis_top_udiv_9ns_9ns_6_13_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component dsp_core_axis_top_fft128_real_zmpio_step1_kTwiddleRealQ15_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dsp_core_axis_top_fft128_real_zmpio_step1_kTwiddleImagQ15_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    zmpio_step1_kTwiddleRealQ15_U : component dsp_core_axis_top_fft128_real_zmpio_step1_kTwiddleRealQ15_ROM_AUTO_1R
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => zmpio_step1_kTwiddleRealQ15_address0,
        ce0 => zmpio_step1_kTwiddleRealQ15_ce0,
        q0 => zmpio_step1_kTwiddleRealQ15_q0);

    zmpio_step1_kTwiddleImagQ15_U : component dsp_core_axis_top_fft128_real_zmpio_step1_kTwiddleImagQ15_ROM_AUTO_1R
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => zmpio_step1_kTwiddleImagQ15_address0,
        ce0 => zmpio_step1_kTwiddleImagQ15_ce0,
        q0 => zmpio_step1_kTwiddleImagQ15_q0);

    mul_32s_16s_48_1_1_U1 : component dsp_core_axis_top_mul_32s_16s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 16,
        dout_WIDTH => 48)
    port map (
        din0 => grp_fu_258_p0,
        din1 => grp_fu_258_p1,
        dout => grp_fu_258_p2);

    udiv_9ns_9ns_6_13_seq_1_U2 : component dsp_core_axis_top_udiv_9ns_9ns_6_13_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 13,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_367_ap_start,
        done => grp_fu_367_ap_done,
        din0 => ap_const_lv9_80,
        din1 => span_fu_102,
        ce => ap_const_logic_1,
        dout => grp_fu_367_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    base_reg_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln47_fu_411_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then 
                base_reg_224 <= base_1_fu_449_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                base_reg_224 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    bit_reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                bit_reg_202 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln15_fu_311_p2 = ap_const_lv1_0))) then 
                bit_reg_202 <= add_ln15_fu_317_p2;
            end if; 
        end if;
    end process;

    index_3_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                index_3_fu_98 <= ap_const_lv8_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln15_fu_311_p2 = ap_const_lv1_1))) then 
                index_3_fu_98 <= index_reg_870;
            end if; 
        end if;
    end process;

    index_4_reg_247_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
                index_4_reg_247 <= add_ln50_1_reg_953;
            elsif (((tmp_fu_389_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                index_4_reg_247 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    offset_reg_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
                offset_reg_236 <= offset_1_reg_943;
            elsif (((tmp_fu_389_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                offset_reg_236 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    reg_213_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                reg_213 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_const_lv7_0),48));
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln15_fu_311_p2 = ap_const_lv1_0))) then 
                reg_213 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reversed_1_fu_340_p3),48));
            elsif (((ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
                reg_213 <= grp_fu_258_p2;
            end if; 
        end if;
    end process;

    span_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_289_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                span_fu_102(1) <= '1';
                span_fu_102(2) <= '0';
                span_fu_102(3) <= '0';
                span_fu_102(4) <= '0';
                span_fu_102(5) <= '0';
                span_fu_102(6) <= '0';
                span_fu_102(7) <= '0';
                span_fu_102(8) <= '0';
            elsif (((tmp_fu_389_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                                span_fu_102(8 downto 1) <= span_2_fu_401_p2(8 downto 1);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                add_ln48_reg_948 <= add_ln48_fu_422_p2;
                add_ln50_1_reg_953 <= add_ln50_1_fu_438_p2;
                offset_1_reg_943 <= offset_1_fu_416_p2;
                output_imag_addr_2_reg_968 <= zext_ln50_fu_432_p1(7 - 1 downto 0);
                output_real_addr_2_reg_958 <= zext_ln50_fu_432_p1(7 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                index_reg_870 <= index_fu_295_p2;
                    zext_ln39_reg_875(7 downto 0) <= zext_ln39_fu_301_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                input_load_reg_892 <= input_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then
                odd_imag_reg_1034 <= odd_imag_fu_724_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then
                output_imag_addr_1_reg_1003 <= zext_ln48_fu_464_p1(7 - 1 downto 0);
                output_real_addr_1_reg_998 <= zext_ln48_fu_464_p1(7 - 1 downto 0);
                sext_ln28_reg_1013 <= sext_ln28_fu_474_p1;
                sext_ln56_reg_1008 <= sext_ln56_fu_469_p1;
                tmp_26_reg_1024 <= real_fu_478_p2(47 downto 47);
                trunc_ln26_reg_1018 <= trunc_ln26_fu_484_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state22)) then
                select_ln19_2_reg_1029 <= select_ln19_2_fu_660_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state24)) then
                select_ln19_3_reg_1039 <= select_ln19_3_fu_852_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                sext_ln189_reg_983 <= sext_ln189_fu_454_p1;
                sext_ln27_reg_988 <= sext_ln27_fu_459_p1;
                zmpio_step1_kTwiddleImagQ15_load_reg_993 <= zmpio_step1_kTwiddleImagQ15_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                    trunc_ln43_reg_916(7 downto 1) <= trunc_ln43_fu_373_p1(7 downto 1);
                trunc_ln50_reg_927 <= trunc_ln50_fu_385_p1;
                trunc_ln_reg_921 <= span_fu_102(7 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                trunc_ln46_reg_935 <= trunc_ln46_fu_397_p1;
            end if;
        end if;
    end process;
    zext_ln39_reg_875(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    trunc_ln43_reg_916(0) <= '0';
    span_fu_102(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state18, ap_CS_fsm_state19, icmp_ln15_fu_311_p2, icmp_ln47_fu_411_p2, tmp_fu_389_p3, icmp_ln39_fu_289_p2, ap_CS_fsm_state5, icmp_ln43_fu_361_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln39_fu_289_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln15_fu_311_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln43_fu_361_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                if (((tmp_fu_389_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state19 => 
                if (((icmp_ln47_fu_411_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln12_1_fu_686_p2 <= std_logic_vector(unsigned(trunc_ln29_fu_674_p1) + unsigned(ap_const_lv47_4000));
    add_ln12_fu_496_p2 <= std_logic_vector(unsigned(trunc_ln26_reg_1018) + unsigned(ap_const_lv47_4000));
    add_ln15_fu_317_p2 <= std_logic_vector(unsigned(bit_reg_202) + unsigned(ap_const_lv3_1));
    add_ln20_1_fu_753_p2 <= std_logic_vector(unsigned(add_ln53_fu_739_p2) + unsigned(ap_const_lv33_1));
    add_ln20_2_fu_622_p2 <= std_logic_vector(unsigned(sub_ln56_fu_608_p2) + unsigned(ap_const_lv33_1));
    add_ln20_3_fu_814_p2 <= std_logic_vector(unsigned(sub_ln57_fu_800_p2) + unsigned(ap_const_lv33_1));
    add_ln20_fu_561_p2 <= std_logic_vector(unsigned(add_ln52_fu_547_p2) + unsigned(ap_const_lv33_1));
    add_ln48_fu_422_p2 <= std_logic_vector(unsigned(offset_reg_236) + unsigned(trunc_ln46_reg_935));
    add_ln50_1_fu_438_p2 <= std_logic_vector(unsigned(index_4_reg_247) + unsigned(trunc_ln50_reg_927));
    add_ln50_fu_427_p2 <= std_logic_vector(unsigned(add_ln48_fu_422_p2) + unsigned(trunc_ln_reg_921));
    add_ln52_fu_547_p2 <= std_logic_vector(signed(sext_ln52_1_fu_543_p1) + signed(sext_ln52_fu_539_p1));
    add_ln53_fu_739_p2 <= std_logic_vector(signed(sext_ln53_1_fu_736_p1) + signed(sext_ln53_fu_732_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5, icmp_ln43_fu_361_p2)
    begin
        if ((((icmp_ln43_fu_361_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, icmp_ln43_fu_361_p2)
    begin
        if (((icmp_ln43_fu_361_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    base_1_fu_449_p2 <= std_logic_vector(unsigned(trunc_ln43_reg_916) + unsigned(base_reg_224));

    grp_fu_258_p0_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state22, sext_ln189_fu_454_p1, sext_ln189_reg_983, ap_CS_fsm_state21, sext_ln56_fu_469_p1, sext_ln56_reg_1008, ap_CS_fsm_state23)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            grp_fu_258_p0 <= sext_ln56_reg_1008(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            grp_fu_258_p0 <= sext_ln189_reg_983(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            grp_fu_258_p0 <= sext_ln56_fu_469_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_258_p0 <= sext_ln189_fu_454_p1(32 - 1 downto 0);
        else 
            grp_fu_258_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_258_p1_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state22, sext_ln27_fu_459_p1, sext_ln27_reg_988, ap_CS_fsm_state21, sext_ln28_fu_474_p1, sext_ln28_reg_1013, ap_CS_fsm_state23)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            grp_fu_258_p1 <= sext_ln27_reg_988(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            grp_fu_258_p1 <= sext_ln28_reg_1013(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            grp_fu_258_p1 <= sext_ln28_fu_474_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_258_p1 <= sext_ln27_fu_459_p1(16 - 1 downto 0);
        else 
            grp_fu_258_p1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_367_ap_start_assign_proc : process(ap_CS_fsm_state5, icmp_ln43_fu_361_p2)
    begin
        if (((icmp_ln43_fu_361_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            grp_fu_367_ap_start <= ap_const_logic_1;
        else 
            grp_fu_367_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln15_fu_311_p2 <= "1" when (bit_reg_202 = ap_const_lv3_7) else "0";
    icmp_ln39_fu_289_p2 <= "1" when (index_3_fu_98 = ap_const_lv8_80) else "0";
    icmp_ln43_fu_361_p2 <= "1" when (unsigned(span_fu_102) < unsigned(ap_const_lv9_81)) else "0";
    icmp_ln47_fu_411_p2 <= "1" when (offset_reg_236 = trunc_ln_reg_921) else "0";
    imag_fu_668_p2 <= std_logic_vector(unsigned(reg_213) + unsigned(grp_fu_258_p2));
    index_fu_295_p2 <= std_logic_vector(unsigned(index_3_fu_98) + unsigned(ap_const_lv8_1));
    input_r_address0 <= zext_ln39_fu_301_p1(7 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln16_fu_327_p2 <= std_logic_vector(shift_right(unsigned(zext_ln39_reg_875),to_integer(unsigned('0' & zext_ln15_1_fu_323_p1(31-1 downto 0)))));
    odd_imag_fu_724_p3 <= 
        sub_ln14_3_fu_718_p2 when (tmp_27_fu_678_p3(0) = '1') else 
        trunc_ln12_1_fu_692_p4;
    odd_real_fu_532_p3 <= 
        sub_ln14_1_fu_526_p2 when (tmp_26_reg_1024(0) = '1') else 
        trunc_ln3_fu_501_p4;
    offset_1_fu_416_p2 <= std_logic_vector(unsigned(offset_reg_236) + unsigned(ap_const_lv7_1));

    output_imag_address0_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state4, output_imag_addr_2_reg_968, output_imag_addr_1_reg_1003, ap_CS_fsm_state23, ap_CS_fsm_state24, ap_CS_fsm_state25, zext_ln15_fu_348_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state23))) then 
            output_imag_address0 <= output_imag_addr_1_reg_1003;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state25))) then 
            output_imag_address0 <= output_imag_addr_2_reg_968;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_imag_address0 <= zext_ln15_fu_348_p1(7 - 1 downto 0);
        else 
            output_imag_address0 <= "XXXXXXX";
        end if; 
    end process;


    output_imag_ce0_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state4, ap_CS_fsm_state23, ap_CS_fsm_state24, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_imag_ce0 <= ap_const_logic_1;
        else 
            output_imag_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_imag_d0_assign_proc : process(ap_CS_fsm_state4, select_ln19_3_reg_1039, ap_CS_fsm_state24, ap_CS_fsm_state25, select_ln19_1_fu_791_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            output_imag_d0 <= select_ln19_3_reg_1039;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            output_imag_d0 <= select_ln19_1_fu_791_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_imag_d0 <= ap_const_lv32_0;
        else 
            output_imag_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_imag_we0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state24, icmp_ln15_fu_311_p2, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state24) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln15_fu_311_p2 = ap_const_lv1_1)))) then 
            output_imag_we0 <= ap_const_logic_1;
        else 
            output_imag_we0 <= ap_const_logic_0;
        end if; 
    end process;


    output_real_address0_assign_proc : process(ap_CS_fsm_state22, ap_CS_fsm_state4, ap_CS_fsm_state19, output_real_addr_2_reg_958, output_real_addr_1_reg_998, ap_CS_fsm_state21, ap_CS_fsm_state23, zext_ln15_fu_348_p1, zext_ln50_fu_432_p1, zext_ln48_fu_464_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            output_real_address0 <= output_real_addr_2_reg_958;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            output_real_address0 <= output_real_addr_1_reg_998;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            output_real_address0 <= zext_ln48_fu_464_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            output_real_address0 <= zext_ln50_fu_432_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_real_address0 <= zext_ln15_fu_348_p1(7 - 1 downto 0);
        else 
            output_real_address0 <= "XXXXXXX";
        end if; 
    end process;


    output_real_ce0_assign_proc : process(ap_CS_fsm_state22, ap_CS_fsm_state4, ap_CS_fsm_state19, ap_CS_fsm_state21, ap_CS_fsm_state23)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_real_ce0 <= ap_const_logic_1;
        else 
            output_real_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_real_d0_assign_proc : process(ap_CS_fsm_state22, input_load_reg_892, ap_CS_fsm_state4, select_ln19_2_reg_1029, ap_CS_fsm_state23, select_ln19_fu_599_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            output_real_d0 <= select_ln19_2_reg_1029;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            output_real_d0 <= select_ln19_fu_599_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_real_d0 <= input_load_reg_892;
        else 
            output_real_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_real_we0_assign_proc : process(ap_CS_fsm_state22, ap_CS_fsm_state4, ap_CS_fsm_state23, icmp_ln15_fu_311_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state23) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln15_fu_311_p2 = ap_const_lv1_1)))) then 
            output_real_we0 <= ap_const_logic_1;
        else 
            output_real_we0 <= ap_const_logic_0;
        end if; 
    end process;

    real_fu_478_p2 <= std_logic_vector(unsigned(reg_213) - unsigned(grp_fu_258_p2));
    reversed_1_fu_340_p3 <= (trunc_ln16_1_fu_336_p1 & trunc_ln16_fu_332_p1);
    select_ln19_1_fu_791_p3 <= 
        sub_ln22_3_fu_785_p2 when (tmp_29_fu_745_p3(0) = '1') else 
        trunc_ln20_1_fu_759_p4;
    select_ln19_2_fu_660_p3 <= 
        sub_ln22_5_fu_654_p2 when (tmp_30_fu_614_p3(0) = '1') else 
        trunc_ln20_2_fu_628_p4;
    select_ln19_3_fu_852_p3 <= 
        sub_ln22_7_fu_846_p2 when (tmp_31_fu_806_p3(0) = '1') else 
        trunc_ln20_3_fu_820_p4;
    select_ln19_fu_599_p3 <= 
        sub_ln22_1_fu_593_p2 when (tmp_28_fu_553_p3(0) = '1') else 
        trunc_ln5_fu_567_p4;
    sext_ln189_fu_454_p0 <= output_real_q0;
        sext_ln189_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln189_fu_454_p0),48));

        sext_ln27_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(zmpio_step1_kTwiddleRealQ15_q0),48));

        sext_ln28_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(zmpio_step1_kTwiddleImagQ15_load_reg_993),48));

        sext_ln52_1_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(odd_real_fu_532_p3),33));

    sext_ln52_fu_539_p0 <= output_real_q0;
        sext_ln52_fu_539_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln52_fu_539_p0),33));

        sext_ln53_1_fu_736_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(odd_imag_reg_1034),33));

    sext_ln53_fu_732_p0 <= output_imag_q0;
        sext_ln53_fu_732_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln53_fu_732_p0),33));

    sext_ln56_fu_469_p0 <= output_imag_q0;
        sext_ln56_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_fu_469_p0),48));

    span_2_fu_401_p2 <= std_logic_vector(shift_left(unsigned(span_fu_102),to_integer(unsigned('0' & ap_const_lv9_1(9-1 downto 0)))));
    sub_ln14_1_fu_526_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln4_fu_516_p4));
    sub_ln14_2_fu_702_p2 <= std_logic_vector(unsigned(ap_const_lv47_4000) - unsigned(trunc_ln29_fu_674_p1));
    sub_ln14_3_fu_718_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln14_1_fu_708_p4));
    sub_ln14_fu_511_p2 <= std_logic_vector(unsigned(ap_const_lv47_4000) - unsigned(trunc_ln26_reg_1018));
    sub_ln22_1_fu_593_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln6_fu_583_p4));
    sub_ln22_2_fu_769_p2 <= std_logic_vector(unsigned(ap_const_lv33_1) - unsigned(add_ln53_fu_739_p2));
    sub_ln22_3_fu_785_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln22_1_fu_775_p4));
    sub_ln22_4_fu_638_p2 <= std_logic_vector(unsigned(ap_const_lv33_1) - unsigned(sub_ln56_fu_608_p2));
    sub_ln22_5_fu_654_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln22_2_fu_644_p4));
    sub_ln22_6_fu_830_p2 <= std_logic_vector(unsigned(ap_const_lv33_1) - unsigned(sub_ln57_fu_800_p2));
    sub_ln22_7_fu_846_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln22_3_fu_836_p4));
    sub_ln22_fu_577_p2 <= std_logic_vector(unsigned(ap_const_lv33_1) - unsigned(add_ln52_fu_547_p2));
    sub_ln56_fu_608_p2 <= std_logic_vector(signed(sext_ln52_fu_539_p1) - signed(sext_ln52_1_fu_543_p1));
    sub_ln57_fu_800_p2 <= std_logic_vector(signed(sext_ln53_fu_732_p1) - signed(sext_ln53_1_fu_736_p1));
    tmp_27_fu_678_p3 <= imag_fu_668_p2(47 downto 47);
    tmp_28_fu_553_p3 <= add_ln52_fu_547_p2(32 downto 32);
    tmp_29_fu_745_p3 <= add_ln53_fu_739_p2(32 downto 32);
    tmp_30_fu_614_p3 <= sub_ln56_fu_608_p2(32 downto 32);
    tmp_31_fu_806_p3 <= sub_ln57_fu_800_p2(32 downto 32);
    tmp_fu_389_p3 <= base_reg_224(7 downto 7);
    trunc_ln12_1_fu_692_p4 <= add_ln12_1_fu_686_p2(46 downto 15);
    trunc_ln14_1_fu_708_p4 <= sub_ln14_2_fu_702_p2(46 downto 15);
    trunc_ln16_1_fu_336_p0 <= reg_213(7 - 1 downto 0);
    trunc_ln16_1_fu_336_p1 <= trunc_ln16_1_fu_336_p0(6 - 1 downto 0);
    trunc_ln16_fu_332_p1 <= lshr_ln16_fu_327_p2(1 - 1 downto 0);
    trunc_ln20_1_fu_759_p4 <= add_ln20_1_fu_753_p2(32 downto 1);
    trunc_ln20_2_fu_628_p4 <= add_ln20_2_fu_622_p2(32 downto 1);
    trunc_ln20_3_fu_820_p4 <= add_ln20_3_fu_814_p2(32 downto 1);
    trunc_ln22_1_fu_775_p4 <= sub_ln22_2_fu_769_p2(32 downto 1);
    trunc_ln22_2_fu_644_p4 <= sub_ln22_4_fu_638_p2(32 downto 1);
    trunc_ln22_3_fu_836_p4 <= sub_ln22_6_fu_830_p2(32 downto 1);
    trunc_ln26_fu_484_p1 <= real_fu_478_p2(47 - 1 downto 0);
    trunc_ln29_fu_674_p1 <= imag_fu_668_p2(47 - 1 downto 0);
    trunc_ln3_fu_501_p4 <= add_ln12_fu_496_p2(46 downto 15);
    trunc_ln43_fu_373_p1 <= span_fu_102(8 - 1 downto 0);
    trunc_ln46_fu_397_p1 <= base_reg_224(7 - 1 downto 0);
    trunc_ln4_fu_516_p4 <= sub_ln14_fu_511_p2(46 downto 15);
    trunc_ln50_fu_385_p1 <= grp_fu_367_p2(6 - 1 downto 0);
    trunc_ln5_fu_567_p4 <= add_ln20_fu_561_p2(32 downto 1);
    trunc_ln6_fu_583_p4 <= sub_ln22_fu_577_p2(32 downto 1);
    zext_ln15_1_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bit_reg_202),64));
    zext_ln15_fu_348_p0 <= reg_213(7 - 1 downto 0);
    zext_ln15_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln15_fu_348_p0),64));
    zext_ln21_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_4_reg_247),64));
    zext_ln39_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index_3_fu_98),64));
    zext_ln48_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln48_reg_948),64));
    zext_ln50_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln50_fu_427_p2),64));
    zmpio_step1_kTwiddleImagQ15_address0 <= zext_ln21_fu_443_p1(6 - 1 downto 0);

    zmpio_step1_kTwiddleImagQ15_ce0_assign_proc : process(ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            zmpio_step1_kTwiddleImagQ15_ce0 <= ap_const_logic_1;
        else 
            zmpio_step1_kTwiddleImagQ15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    zmpio_step1_kTwiddleRealQ15_address0 <= zext_ln21_fu_443_p1(6 - 1 downto 0);

    zmpio_step1_kTwiddleRealQ15_ce0_assign_proc : process(ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            zmpio_step1_kTwiddleRealQ15_ce0 <= ap_const_logic_1;
        else 
            zmpio_step1_kTwiddleRealQ15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
