-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dsp_core_axis_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    sample_axis_in_TDATA : IN STD_LOGIC_VECTOR (159 downto 0);
    sample_axis_in_TVALID : IN STD_LOGIC;
    sample_axis_in_TREADY : OUT STD_LOGIC;
    sample_axis_in_TKEEP : IN STD_LOGIC_VECTOR (19 downto 0);
    sample_axis_in_TSTRB : IN STD_LOGIC_VECTOR (19 downto 0);
    sample_axis_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sample_axis_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    sample_axis_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    sample_axis_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    feature_axis_out_TDATA : OUT STD_LOGIC_VECTOR (383 downto 0);
    feature_axis_out_TVALID : OUT STD_LOGIC;
    feature_axis_out_TREADY : IN STD_LOGIC;
    feature_axis_out_TKEEP : OUT STD_LOGIC_VECTOR (47 downto 0);
    feature_axis_out_TSTRB : OUT STD_LOGIC_VECTOR (47 downto 0);
    feature_axis_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    feature_axis_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    feature_axis_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    feature_axis_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of dsp_core_axis_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dsp_core_axis_top_dsp_core_axis_top,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=14.407000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=33,HLS_SYN_DSP=0,HLS_SYN_FF=4516,HLS_SYN_LUT=20842,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv48_FFFFFFFFFFFF : STD_LOGIC_VECTOR (47 downto 0) := "111111111111111111111111111111111111111111111111";
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv384_lc_3 : STD_LOGIC_VECTOR (383 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv48_FF : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000011111111";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv48_FF0000000000 : STD_LOGIC_VECTOR (47 downto 0) := "111111110000000000000000000000000000000000000000";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv48_FFFFFFFF0FFF : STD_LOGIC_VECTOR (47 downto 0) := "111111111111111111111111111111110000111111111111";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv48_FFFF010000 : STD_LOGIC_VECTOR (47 downto 0) := "000000001111111111111111000000010000000000000000";
    constant ap_const_lv48_FFFFFFFF0000 : STD_LOGIC_VECTOR (47 downto 0) := "111111111111111111111111111111110000000000000000";
    constant ap_const_lv48_FFFF01FFFF : STD_LOGIC_VECTOR (47 downto 0) := "000000001111111111111111000000011111111111111111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv48_10000 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000010000000000000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv9_16 : STD_LOGIC_VECTOR (8 downto 0) := "000010110";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv15_AB : STD_LOGIC_VECTOR (14 downto 0) := "000000010101011";
    constant ap_const_lv48_3 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000011";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv10_68 : STD_LOGIC_VECTOR (9 downto 0) := "0001101000";
    constant ap_const_lv21_556 : STD_LOGIC_VECTOR (20 downto 0) := "000000000010101010110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv16_F : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal core_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal core_ce0 : STD_LOGIC;
    signal core_we0 : STD_LOGIC_VECTOR (47 downto 0);
    signal core_d0 : STD_LOGIC_VECTOR (383 downto 0);
    signal core_q0 : STD_LOGIC_VECTOR (383 downto 0);
    signal core_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal core_ce1 : STD_LOGIC;
    signal core_we1 : STD_LOGIC_VECTOR (47 downto 0);
    signal core_d1 : STD_LOGIC_VECTOR (383 downto 0);
    signal core_q1 : STD_LOGIC_VECTOR (383 downto 0);
    signal sample_axis_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal feature_axis_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal tmp_13_reg_1198 : STD_LOGIC_VECTOR (0 downto 0);
    signal guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_reg_1075 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln19_fu_554_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln19_reg_1109 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln752_fu_571_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal empty_64_fu_713_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_64_reg_1132 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln19_1_fu_874_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln19_1_reg_1161 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal add_ln752_1_fu_886_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_nbreadreq_fu_258_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1174 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal sample_accel_x_fu_1007_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sample_accel_x_reg_1178 : STD_LOGIC_VECTOR (15 downto 0);
    signal sample_accel_y_reg_1183 : STD_LOGIC_VECTOR (15 downto 0);
    signal sample_accel_z_reg_1188 : STD_LOGIC_VECTOR (15 downto 0);
    signal sample_sample_sequence_reg_1193 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_1045_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal trunc_ln39_fu_1053_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal trunc_ln39_reg_1202 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_push_fu_388_ap_start : STD_LOGIC;
    signal grp_push_fu_388_ap_done : STD_LOGIC;
    signal grp_push_fu_388_ap_idle : STD_LOGIC;
    signal grp_push_fu_388_ap_ready : STD_LOGIC;
    signal grp_push_fu_388_core_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_push_fu_388_core_ce0 : STD_LOGIC;
    signal grp_push_fu_388_core_we0 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_push_fu_388_core_d0 : STD_LOGIC_VECTOR (383 downto 0);
    signal grp_push_fu_388_core_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_push_fu_388_core_ce1 : STD_LOGIC;
    signal grp_push_fu_388_core_we1 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_push_fu_388_core_d1 : STD_LOGIC_VECTOR (383 downto 0);
    signal idx171_reg_366 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln19_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln753_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal idx169_reg_377 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln19_1_fu_868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln753_1_fu_880_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_push_fu_388_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal p_cast24_fu_458_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal exitcond_i_i6_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln754_fu_614_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast26_fu_748_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln754_4_fu_929_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_mul_fu_234 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal next_mul_fu_442_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_fu_238 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal empty_57_fu_436_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal idx_fu_242 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal empty_61_fu_246 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal empty_62_fu_691_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal exitcond_i10_i4_fu_685_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_68_fu_250 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal empty_69_fu_822_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal exitcond_i3_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal idx166_fu_254 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal empty_60_fu_523_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln754_fu_671_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal empty_67_fu_806_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal p_cast29_fu_850_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln754_1_fu_986_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal regslice_both_feature_axis_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state16 : BOOLEAN;
    signal ap_block_state16_io : BOOLEAN;
    signal tmp_1_fu_448_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal phi_mul_cast_fu_426_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_fu_463_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_479_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_6_fu_491_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_cast3_fu_487_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_3_fu_471_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_58_fu_503_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_cast4_fu_509_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_cast5_fu_499_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_59_fu_513_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_cast25_fu_519_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln752_fu_577_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_first_assign_fu_581_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln754_fu_594_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln754_fu_594_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln754_fu_594_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_10_fu_604_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln754_5_fu_600_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_11_fu_619_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln754_3_fu_635_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln754_2_fu_643_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln754_2_fu_627_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln754_fu_651_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln754_fu_657_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln754_3_fu_647_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln754_fu_661_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln754_1_fu_667_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal empty_63_fu_697_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_fu_701_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_cast17_fu_709_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul4_fu_732_p0 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul4_fu_732_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul4_fu_732_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_4_fu_738_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_753_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_763_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_9_fu_775_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_cast19_fu_783_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_cast20_fu_771_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_65_fu_790_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_cast21_fu_787_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_66_fu_796_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_cast27_fu_802_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal empty_70_fu_828_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_832_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_cast23_fu_840_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_71_fu_844_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln752_1_fu_892_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_first_assign_1_fu_896_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln754_1_fu_909_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln754_1_fu_909_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln754_1_fu_909_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_14_fu_919_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln754_9_fu_915_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_15_fu_934_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln754_5_fu_950_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln754_6_fu_958_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln754_4_fu_942_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln754_1_fu_966_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln754_2_fu_972_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln754_7_fu_962_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln754_1_fu_976_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln754_3_fu_982_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_16_fu_1057_p4 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_block_state12_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal sample_axis_in_TDATA_int_regslice : STD_LOGIC_VECTOR (159 downto 0);
    signal sample_axis_in_TVALID_int_regslice : STD_LOGIC;
    signal sample_axis_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal sample_axis_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (19 downto 0);
    signal regslice_both_sample_axis_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal sample_axis_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (19 downto 0);
    signal regslice_both_sample_axis_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_user_V_U_apdone_blk : STD_LOGIC;
    signal sample_axis_in_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_sample_axis_in_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal sample_axis_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_sample_axis_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_id_V_U_apdone_blk : STD_LOGIC;
    signal sample_axis_in_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_sample_axis_in_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal sample_axis_in_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_sample_axis_in_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_sample_axis_in_V_dest_V_U_ack_in : STD_LOGIC;
    signal feature_axis_out_TDATA_int_regslice : STD_LOGIC_VECTOR (383 downto 0);
    signal feature_axis_out_TVALID_int_regslice : STD_LOGIC;
    signal feature_axis_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_feature_axis_out_V_dest_V_U_vld_out : STD_LOGIC;
    signal mul4_fu_732_p00 : STD_LOGIC_VECTOR (20 downto 0);
    signal mul_ln754_1_fu_909_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln754_fu_594_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component dsp_core_axis_top_push IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sample_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
        sample_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
        sample_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
        sample_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
        core_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        core_ce0 : OUT STD_LOGIC;
        core_we0 : OUT STD_LOGIC_VECTOR (47 downto 0);
        core_d0 : OUT STD_LOGIC_VECTOR (383 downto 0);
        core_q0 : IN STD_LOGIC_VECTOR (383 downto 0);
        core_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        core_ce1 : OUT STD_LOGIC;
        core_we1 : OUT STD_LOGIC_VECTOR (47 downto 0);
        core_d1 : OUT STD_LOGIC_VECTOR (383 downto 0);
        core_q1 : IN STD_LOGIC_VECTOR (383 downto 0) );
    end component;


    component dsp_core_axis_top_mul_7ns_9ns_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dsp_core_axis_top_mul_10ns_12ns_21_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component dsp_core_axis_top_core_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC_VECTOR (47 downto 0);
        d0 : IN STD_LOGIC_VECTOR (383 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (383 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC_VECTOR (47 downto 0);
        d1 : IN STD_LOGIC_VECTOR (383 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (383 downto 0) );
    end component;


    component dsp_core_axis_top_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    core_U : component dsp_core_axis_top_core_RAM_AUTO_1R1W
    generic map (
        DataWidth => 384,
        AddressRange => 15,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => core_address0,
        ce0 => core_ce0,
        we0 => core_we0,
        d0 => core_d0,
        q0 => core_q0,
        address1 => core_address1,
        ce1 => core_ce1,
        we1 => core_we1,
        d1 => core_d1,
        q1 => core_q1);

    grp_push_fu_388 : component dsp_core_axis_top_push
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_push_fu_388_ap_start,
        ap_done => grp_push_fu_388_ap_done,
        ap_idle => grp_push_fu_388_ap_idle,
        ap_ready => grp_push_fu_388_ap_ready,
        sample_0_val => sample_accel_x_reg_1178,
        sample_1_val => sample_accel_y_reg_1183,
        sample_2_val => sample_accel_z_reg_1188,
        sample_8_val => sample_sample_sequence_reg_1193,
        core_address0 => grp_push_fu_388_core_address0,
        core_ce0 => grp_push_fu_388_core_ce0,
        core_we0 => grp_push_fu_388_core_we0,
        core_d0 => grp_push_fu_388_core_d0,
        core_q0 => core_q0,
        core_address1 => grp_push_fu_388_core_address1,
        core_ce1 => grp_push_fu_388_core_ce1,
        core_we1 => grp_push_fu_388_core_we1,
        core_d1 => grp_push_fu_388_core_d1,
        core_q1 => core_q1);

    mul_7ns_9ns_15_1_1_U32 : component dsp_core_axis_top_mul_7ns_9ns_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 7,
        din1_WIDTH => 9,
        dout_WIDTH => 15)
    port map (
        din0 => mul_ln754_fu_594_p0,
        din1 => mul_ln754_fu_594_p1,
        dout => mul_ln754_fu_594_p2);

    mul_10ns_12ns_21_1_1_U33 : component dsp_core_axis_top_mul_10ns_12ns_21_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 12,
        dout_WIDTH => 21)
    port map (
        din0 => mul4_fu_732_p0,
        din1 => mul4_fu_732_p1,
        dout => mul4_fu_732_p2);

    mul_7ns_9ns_15_1_1_U34 : component dsp_core_axis_top_mul_7ns_9ns_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 7,
        din1_WIDTH => 9,
        dout_WIDTH => 15)
    port map (
        din0 => mul_ln754_1_fu_909_p0,
        din1 => mul_ln754_1_fu_909_p1,
        dout => mul_ln754_1_fu_909_p2);

    regslice_both_sample_axis_in_V_data_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 160)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => sample_axis_in_TDATA,
        vld_in => sample_axis_in_TVALID,
        ack_in => regslice_both_sample_axis_in_V_data_V_U_ack_in,
        data_out => sample_axis_in_TDATA_int_regslice,
        vld_out => sample_axis_in_TVALID_int_regslice,
        ack_out => sample_axis_in_TREADY_int_regslice,
        apdone_blk => regslice_both_sample_axis_in_V_data_V_U_apdone_blk);

    regslice_both_sample_axis_in_V_keep_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 20)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => sample_axis_in_TKEEP,
        vld_in => sample_axis_in_TVALID,
        ack_in => regslice_both_sample_axis_in_V_keep_V_U_ack_in,
        data_out => sample_axis_in_TKEEP_int_regslice,
        vld_out => regslice_both_sample_axis_in_V_keep_V_U_vld_out,
        ack_out => sample_axis_in_TREADY_int_regslice,
        apdone_blk => regslice_both_sample_axis_in_V_keep_V_U_apdone_blk);

    regslice_both_sample_axis_in_V_strb_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 20)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => sample_axis_in_TSTRB,
        vld_in => sample_axis_in_TVALID,
        ack_in => regslice_both_sample_axis_in_V_strb_V_U_ack_in,
        data_out => sample_axis_in_TSTRB_int_regslice,
        vld_out => regslice_both_sample_axis_in_V_strb_V_U_vld_out,
        ack_out => sample_axis_in_TREADY_int_regslice,
        apdone_blk => regslice_both_sample_axis_in_V_strb_V_U_apdone_blk);

    regslice_both_sample_axis_in_V_user_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => sample_axis_in_TUSER,
        vld_in => sample_axis_in_TVALID,
        ack_in => regslice_both_sample_axis_in_V_user_V_U_ack_in,
        data_out => sample_axis_in_TUSER_int_regslice,
        vld_out => regslice_both_sample_axis_in_V_user_V_U_vld_out,
        ack_out => sample_axis_in_TREADY_int_regslice,
        apdone_blk => regslice_both_sample_axis_in_V_user_V_U_apdone_blk);

    regslice_both_sample_axis_in_V_last_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => sample_axis_in_TLAST,
        vld_in => sample_axis_in_TVALID,
        ack_in => regslice_both_sample_axis_in_V_last_V_U_ack_in,
        data_out => sample_axis_in_TLAST_int_regslice,
        vld_out => regslice_both_sample_axis_in_V_last_V_U_vld_out,
        ack_out => sample_axis_in_TREADY_int_regslice,
        apdone_blk => regslice_both_sample_axis_in_V_last_V_U_apdone_blk);

    regslice_both_sample_axis_in_V_id_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => sample_axis_in_TID,
        vld_in => sample_axis_in_TVALID,
        ack_in => regslice_both_sample_axis_in_V_id_V_U_ack_in,
        data_out => sample_axis_in_TID_int_regslice,
        vld_out => regslice_both_sample_axis_in_V_id_V_U_vld_out,
        ack_out => sample_axis_in_TREADY_int_regslice,
        apdone_blk => regslice_both_sample_axis_in_V_id_V_U_apdone_blk);

    regslice_both_sample_axis_in_V_dest_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => sample_axis_in_TDEST,
        vld_in => sample_axis_in_TVALID,
        ack_in => regslice_both_sample_axis_in_V_dest_V_U_ack_in,
        data_out => sample_axis_in_TDEST_int_regslice,
        vld_out => regslice_both_sample_axis_in_V_dest_V_U_vld_out,
        ack_out => sample_axis_in_TREADY_int_regslice,
        apdone_blk => regslice_both_sample_axis_in_V_dest_V_U_apdone_blk);

    regslice_both_feature_axis_out_V_data_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 384)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => feature_axis_out_TDATA_int_regslice,
        vld_in => feature_axis_out_TVALID_int_regslice,
        ack_in => feature_axis_out_TREADY_int_regslice,
        data_out => feature_axis_out_TDATA,
        vld_out => regslice_both_feature_axis_out_V_data_V_U_vld_out,
        ack_out => feature_axis_out_TREADY,
        apdone_blk => regslice_both_feature_axis_out_V_data_V_U_apdone_blk);

    regslice_both_feature_axis_out_V_keep_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 48)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv48_FFFFFFFFFFFF,
        vld_in => feature_axis_out_TVALID_int_regslice,
        ack_in => regslice_both_feature_axis_out_V_keep_V_U_ack_in_dummy,
        data_out => feature_axis_out_TKEEP,
        vld_out => regslice_both_feature_axis_out_V_keep_V_U_vld_out,
        ack_out => feature_axis_out_TREADY,
        apdone_blk => regslice_both_feature_axis_out_V_keep_V_U_apdone_blk);

    regslice_both_feature_axis_out_V_strb_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 48)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv48_FFFFFFFFFFFF,
        vld_in => feature_axis_out_TVALID_int_regslice,
        ack_in => regslice_both_feature_axis_out_V_strb_V_U_ack_in_dummy,
        data_out => feature_axis_out_TSTRB,
        vld_out => regslice_both_feature_axis_out_V_strb_V_U_vld_out,
        ack_out => feature_axis_out_TREADY,
        apdone_blk => regslice_both_feature_axis_out_V_strb_V_U_apdone_blk);

    regslice_both_feature_axis_out_V_user_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_1,
        vld_in => feature_axis_out_TVALID_int_regslice,
        ack_in => regslice_both_feature_axis_out_V_user_V_U_ack_in_dummy,
        data_out => feature_axis_out_TUSER,
        vld_out => regslice_both_feature_axis_out_V_user_V_U_vld_out,
        ack_out => feature_axis_out_TREADY,
        apdone_blk => regslice_both_feature_axis_out_V_user_V_U_apdone_blk);

    regslice_both_feature_axis_out_V_last_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_1,
        vld_in => feature_axis_out_TVALID_int_regslice,
        ack_in => regslice_both_feature_axis_out_V_last_V_U_ack_in_dummy,
        data_out => feature_axis_out_TLAST,
        vld_out => regslice_both_feature_axis_out_V_last_V_U_vld_out,
        ack_out => feature_axis_out_TREADY,
        apdone_blk => regslice_both_feature_axis_out_V_last_V_U_apdone_blk);

    regslice_both_feature_axis_out_V_id_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => feature_axis_out_TVALID_int_regslice,
        ack_in => regslice_both_feature_axis_out_V_id_V_U_ack_in_dummy,
        data_out => feature_axis_out_TID,
        vld_out => regslice_both_feature_axis_out_V_id_V_U_vld_out,
        ack_out => feature_axis_out_TREADY,
        apdone_blk => regslice_both_feature_axis_out_V_id_V_U_apdone_blk);

    regslice_both_feature_axis_out_V_dest_V_U : component dsp_core_axis_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => feature_axis_out_TVALID_int_regslice,
        ack_in => regslice_both_feature_axis_out_V_dest_V_U_ack_in_dummy,
        data_out => feature_axis_out_TDEST,
        vld_out => regslice_both_feature_axis_out_V_dest_V_U_vld_out,
        ack_out => feature_axis_out_TREADY,
        apdone_blk => regslice_both_feature_axis_out_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_push_fu_388_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_push_fu_388_ap_start_reg <= ap_const_logic_0;
            else
                if (((sample_axis_in_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                    grp_push_fu_388_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_push_fu_388_ap_ready = ap_const_logic_1)) then 
                    grp_push_fu_388_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    empty_61_fu_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln19_fu_548_p2 = ap_const_lv1_1))) then 
                empty_61_fu_246 <= ap_const_lv7_0;
            elsif (((exitcond_i10_i4_fu_685_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                empty_61_fu_246 <= empty_62_fu_691_p2;
            end if; 
        end if;
    end process;

    empty_68_fu_250_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_i10_i4_fu_685_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                empty_68_fu_250 <= ap_const_lv3_0;
            elsif (((exitcond_i3_fu_816_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                empty_68_fu_250 <= empty_69_fu_822_p2;
            end if; 
        end if;
    end process;

    empty_fu_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                empty_fu_238 <= ap_const_lv4_0;
            elsif (((exitcond_i_i6_fu_430_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                empty_fu_238 <= empty_57_fu_436_p2;
            end if; 
        end if;
    end process;

    idx166_fu_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_i3_fu_816_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                idx166_fu_254 <= ap_const_lv2_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln753_1_fu_880_p2 = ap_const_lv1_1))) then 
                idx166_fu_254 <= add_ln19_1_reg_1161;
            end if; 
        end if;
    end process;

    idx169_reg_377_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln753_1_fu_880_p2 = ap_const_lv1_0))) then 
                idx169_reg_377 <= add_ln752_1_fu_886_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln19_1_fu_868_p2 = ap_const_lv1_0))) then 
                idx169_reg_377 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    idx171_reg_366_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln753_fu_565_p2 = ap_const_lv1_0))) then 
                idx171_reg_366 <= add_ln752_fu_571_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln19_fu_548_p2 = ap_const_lv1_0))) then 
                idx171_reg_366 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    idx_fu_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_i_i6_fu_430_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                idx_fu_242 <= ap_const_lv2_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln753_fu_565_p2 = ap_const_lv1_1))) then 
                idx_fu_242 <= add_ln19_reg_1109;
            end if; 
        end if;
    end process;

    phi_mul_fu_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                phi_mul_fu_234 <= ap_const_lv9_0;
            elsif (((exitcond_i_i6_fu_430_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                phi_mul_fu_234 <= next_mul_fu_442_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln19_1_reg_1161 <= add_ln19_1_fu_874_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln19_reg_1109 <= add_ln19_fu_554_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    empty_64_reg_1132(9 downto 3) <= empty_64_fu_713_p2(9 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_reg_1075 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core <= ap_const_lv1_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_reg_1075 <= guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                sample_accel_x_reg_1178 <= sample_accel_x_fu_1007_p1;
                sample_accel_y_reg_1183 <= sample_axis_in_TDATA_int_regslice(31 downto 16);
                sample_accel_z_reg_1188 <= sample_axis_in_TDATA_int_regslice(47 downto 32);
                sample_sample_sequence_reg_1193 <= sample_axis_in_TDATA_int_regslice(159 downto 128);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                tmp_13_reg_1198 <= core_q0(128 downto 128);
                trunc_ln39_reg_1202 <= trunc_ln39_fu_1053_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                tmp_reg_1174 <= tmp_nbreadreq_fu_258_p9;
            end if;
        end if;
    end process;
    empty_64_reg_1132(2 downto 0) <= "000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state11, ap_CS_fsm_state15, ap_CS_fsm_state16, guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state9, tmp_nbreadreq_fu_258_p9, ap_CS_fsm_state10, tmp_13_fu_1045_p3, ap_CS_fsm_state14, icmp_ln19_fu_548_p2, icmp_ln753_fu_565_p2, icmp_ln19_1_fu_868_p2, icmp_ln753_1_fu_880_p2, ap_CS_fsm_state12, ap_CS_fsm_state2, exitcond_i_i6_fu_430_p2, exitcond_i10_i4_fu_685_p2, ap_CS_fsm_state7, exitcond_i3_fu_816_p2, ap_block_state16, ap_block_state16_io, ap_block_state12_on_subcall_done, sample_axis_in_TVALID_int_regslice, feature_axis_out_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond_i_i6_fu_430_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln19_fu_548_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln753_fu_565_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((exitcond_i10_i4_fu_685_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state7 => 
                if (((exitcond_i3_fu_816_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln19_1_fu_868_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln753_1_fu_880_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (tmp_nbreadreq_fu_258_p9 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                if (((sample_axis_in_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((ap_const_boolean_0 = ap_block_state12_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state14) and (tmp_13_fu_1045_p3 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state15 => 
                if (((feature_axis_out_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state16 => 
                if ((not(((ap_const_boolean_1 = ap_block_state16_io) or (ap_const_boolean_1 = ap_block_state16))) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln19_1_fu_874_p2 <= std_logic_vector(unsigned(idx166_fu_254) + unsigned(ap_const_lv2_1));
    add_ln19_fu_554_p2 <= std_logic_vector(unsigned(idx_fu_242) + unsigned(ap_const_lv2_1));
    add_ln752_1_fu_886_p2 <= std_logic_vector(unsigned(idx169_reg_377) + unsigned(ap_const_lv5_1));
    add_ln752_fu_571_p2 <= std_logic_vector(unsigned(idx171_reg_366) + unsigned(ap_const_lv5_1));
    add_ln754_1_fu_976_p2 <= std_logic_vector(signed(sext_ln754_2_fu_972_p1) + signed(zext_ln754_7_fu_962_p1));
    add_ln754_fu_661_p2 <= std_logic_vector(signed(sext_ln754_fu_657_p1) + signed(zext_ln754_3_fu_647_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(sample_axis_in_TVALID_int_regslice)
    begin
        if ((sample_axis_in_TVALID_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state12_blk_assign_proc : process(ap_block_state12_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state12_on_subcall_done)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;

    ap_ST_fsm_state15_blk_assign_proc : process(feature_axis_out_TREADY_int_regslice)
    begin
        if ((feature_axis_out_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state15_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state15_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state16_blk_assign_proc : process(ap_block_state16, ap_block_state16_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state16_io) or (ap_const_boolean_1 = ap_block_state16))) then 
            ap_ST_fsm_state16_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state16_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state12_on_subcall_done_assign_proc : process(tmp_reg_1174, grp_push_fu_388_ap_done)
    begin
                ap_block_state12_on_subcall_done <= ((grp_push_fu_388_ap_done = ap_const_logic_0) and (tmp_reg_1174 = ap_const_lv1_1));
    end process;


    ap_block_state16_assign_proc : process(tmp_13_reg_1198, regslice_both_feature_axis_out_V_data_V_U_apdone_blk, feature_axis_out_TREADY_int_regslice)
    begin
                ap_block_state16 <= ((regslice_both_feature_axis_out_V_data_V_U_apdone_blk = ap_const_logic_1) or ((feature_axis_out_TREADY_int_regslice = ap_const_logic_0) and (tmp_13_reg_1198 = ap_const_lv1_1)));
    end process;


    ap_block_state16_io_assign_proc : process(tmp_13_reg_1198, feature_axis_out_TREADY_int_regslice)
    begin
                ap_block_state16_io <= ((feature_axis_out_TREADY_int_regslice = ap_const_logic_0) and (tmp_13_reg_1198 = ap_const_lv1_1));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    core_address0_assign_proc : process(ap_CS_fsm_state16, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state9, tmp_reg_1174, grp_push_fu_388_core_address0, ap_CS_fsm_state12, p_cast24_fu_458_p1, ap_CS_fsm_state2, zext_ln754_fu_614_p1, zext_ln754_4_fu_929_p1, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            core_address0 <= ap_const_lv4_E;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            core_address0 <= zext_ln754_4_fu_929_p1(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            core_address0 <= ap_const_lv4_D;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            core_address0 <= zext_ln754_fu_614_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            core_address0 <= ap_const_lv4_2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            core_address0 <= p_cast24_fu_458_p1(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_reg_1174 = ap_const_lv1_1))) then 
            core_address0 <= grp_push_fu_388_core_address0;
        else 
            core_address0 <= "XXXX";
        end if; 
    end process;


    core_address1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state8, tmp_reg_1174, ap_CS_fsm_state10, ap_CS_fsm_state14, grp_push_fu_388_core_address1, ap_CS_fsm_state12, p_cast26_fu_748_p1, ap_CS_fsm_state6, ap_CS_fsm_state7, exitcond_i3_fu_816_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            core_address1 <= ap_const_lv4_D;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            core_address1 <= ap_const_lv4_2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or ((exitcond_i3_fu_816_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((exitcond_i3_fu_816_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            core_address1 <= ap_const_lv4_E;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            core_address1 <= p_cast26_fu_748_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            core_address1 <= ap_const_lv4_C;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_reg_1174 = ap_const_lv1_1))) then 
            core_address1 <= grp_push_fu_388_core_address1;
        else 
            core_address1 <= "XXXX";
        end if; 
    end process;


    core_ce0_assign_proc : process(ap_CS_fsm_state16, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state9, tmp_reg_1174, grp_push_fu_388_core_ce0, ap_CS_fsm_state12, ap_CS_fsm_state2, ap_CS_fsm_state13, ap_block_state16, ap_block_state16_io)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (not(((ap_const_boolean_1 = ap_block_state16_io) or (ap_const_boolean_1 = ap_block_state16))) and (ap_const_logic_1 = ap_CS_fsm_state16)))) then 
            core_ce0 <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_reg_1174 = ap_const_lv1_1))) then 
            core_ce0 <= grp_push_fu_388_core_ce0;
        else 
            core_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    core_ce1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state8, tmp_reg_1174, ap_CS_fsm_state10, ap_CS_fsm_state14, grp_push_fu_388_core_ce1, ap_CS_fsm_state12, ap_CS_fsm_state6, ap_CS_fsm_state7, exitcond_i3_fu_816_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((exitcond_i3_fu_816_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((exitcond_i3_fu_816_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            core_ce1 <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_reg_1174 = ap_const_lv1_1))) then 
            core_ce1 <= grp_push_fu_388_core_ce1;
        else 
            core_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    core_d0_assign_proc : process(ap_CS_fsm_state16, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state9, tmp_reg_1174, grp_push_fu_388_core_d0, ap_CS_fsm_state12, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            core_d0 <= ap_const_lv384_lc_3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_reg_1174 = ap_const_lv1_1))) then 
            core_d0 <= grp_push_fu_388_core_d0;
        else 
            core_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    core_d1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state8, tmp_reg_1174, ap_CS_fsm_state10, grp_push_fu_388_core_d1, ap_CS_fsm_state12, ap_CS_fsm_state6, ap_CS_fsm_state7, exitcond_i3_fu_816_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((exitcond_i3_fu_816_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((exitcond_i3_fu_816_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            core_d1 <= ap_const_lv384_lc_3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_reg_1174 = ap_const_lv1_1))) then 
            core_d1 <= grp_push_fu_388_core_d1;
        else 
            core_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    core_we0_assign_proc : process(ap_CS_fsm_state16, tmp_13_reg_1198, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state9, tmp_reg_1174, grp_push_fu_388_core_we0, icmp_ln19_fu_548_p2, icmp_ln753_fu_565_p2, icmp_ln19_1_fu_868_p2, icmp_ln753_1_fu_880_p2, ap_CS_fsm_state12, ap_CS_fsm_state2, exitcond_i_i6_fu_430_p2, exitcond_i10_i4_fu_685_p2, empty_60_fu_523_p2, shl_ln754_fu_671_p2, shl_ln754_1_fu_986_p2, ap_block_state16, ap_block_state16_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state16_io) or (ap_const_boolean_1 = ap_block_state16))) and (tmp_13_reg_1198 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            core_we0 <= ap_const_lv48_10000;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln753_1_fu_880_p2 = ap_const_lv1_0))) then 
            core_we0 <= shl_ln754_1_fu_986_p2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln19_1_fu_868_p2 = ap_const_lv1_1))) then 
            core_we0 <= ap_const_lv48_FFFFFFFF0000;
        elsif (((exitcond_i10_i4_fu_685_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            core_we0 <= ap_const_lv48_FFFFFFFF0FFF;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln753_fu_565_p2 = ap_const_lv1_0))) then 
            core_we0 <= shl_ln754_fu_671_p2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln19_fu_548_p2 = ap_const_lv1_1))) then 
            core_we0 <= ap_const_lv48_FF;
        elsif (((exitcond_i_i6_fu_430_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            core_we0 <= empty_60_fu_523_p2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_reg_1174 = ap_const_lv1_1))) then 
            core_we0 <= grp_push_fu_388_core_we0;
        else 
            core_we0 <= ap_const_lv48_0;
        end if; 
    end process;


    core_we1_assign_proc : process(guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_reg_1075, ap_CS_fsm_state5, ap_CS_fsm_state8, tmp_reg_1174, ap_CS_fsm_state10, grp_push_fu_388_core_we1, icmp_ln19_1_fu_868_p2, ap_CS_fsm_state12, ap_CS_fsm_state6, exitcond_i10_i4_fu_685_p2, ap_CS_fsm_state7, exitcond_i3_fu_816_p2, empty_67_fu_806_p2, p_cast29_fu_850_p1)
    begin
        if (((guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_reg_1075 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            core_we1 <= ap_const_lv48_FFFF01FFFF;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln19_1_fu_868_p2 = ap_const_lv1_1))) then 
            core_we1 <= ap_const_lv48_FF;
        elsif (((exitcond_i3_fu_816_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            core_we1 <= ap_const_lv48_FFFF010000;
        elsif (((exitcond_i3_fu_816_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            core_we1 <= p_cast29_fu_850_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            core_we1 <= empty_67_fu_806_p2;
        elsif (((exitcond_i10_i4_fu_685_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            core_we1 <= ap_const_lv48_FF0000000000;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_reg_1174 = ap_const_lv1_1))) then 
            core_we1 <= grp_push_fu_388_core_we1;
        else 
            core_we1 <= ap_const_lv48_0;
        end if; 
    end process;

    empty_57_fu_436_p2 <= std_logic_vector(unsigned(empty_fu_238) + unsigned(ap_const_lv4_1));
    empty_58_fu_503_p2 <= std_logic_vector(unsigned(p_cast3_fu_487_p1) - unsigned(tmp_3_fu_471_p3));
    empty_59_fu_513_p2 <= std_logic_vector(signed(p_cast4_fu_509_p1) + signed(p_cast5_fu_499_p1));
    empty_60_fu_523_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv48_FF),to_integer(unsigned('0' & p_cast25_fu_519_p1(31-1 downto 0)))));
    empty_62_fu_691_p2 <= std_logic_vector(unsigned(empty_61_fu_246) + unsigned(ap_const_lv7_1));
    empty_63_fu_697_p1 <= empty_61_fu_246(6 - 1 downto 0);
    empty_64_fu_713_p2 <= std_logic_vector(unsigned(p_cast17_fu_709_p1) + unsigned(ap_const_lv10_68));
    empty_65_fu_790_p2 <= std_logic_vector(unsigned(p_cast19_fu_783_p1) - unsigned(p_cast20_fu_771_p1));
    empty_66_fu_796_p2 <= std_logic_vector(unsigned(empty_65_fu_790_p2) + unsigned(p_cast21_fu_787_p1));
    empty_67_fu_806_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv48_FF),to_integer(unsigned('0' & p_cast27_fu_802_p1(31-1 downto 0)))));
    empty_69_fu_822_p2 <= std_logic_vector(unsigned(empty_68_fu_250) + unsigned(ap_const_lv3_1));
    empty_70_fu_828_p1 <= empty_68_fu_250(2 - 1 downto 0);
    empty_71_fu_844_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv16_F),to_integer(unsigned('0' & p_cast23_fu_840_p1(16-1 downto 0)))));
    exitcond_i10_i4_fu_685_p2 <= "1" when (empty_61_fu_246 = ap_const_lv7_40) else "0";
    exitcond_i3_fu_816_p2 <= "1" when (empty_68_fu_250 = ap_const_lv3_4) else "0";
    exitcond_i_i6_fu_430_p2 <= "1" when (empty_fu_238 = ap_const_lv4_C) else "0";

    feature_axis_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state15, ap_CS_fsm_state16, tmp_13_reg_1198, feature_axis_out_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) or ((tmp_13_reg_1198 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16)))) then 
            feature_axis_out_TDATA_blk_n <= feature_axis_out_TREADY_int_regslice;
        else 
            feature_axis_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    feature_axis_out_TDATA_int_regslice <= (trunc_ln39_reg_1202 & tmp_16_fu_1057_p4);
    feature_axis_out_TVALID <= regslice_both_feature_axis_out_V_data_V_U_vld_out;

    feature_axis_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state15, feature_axis_out_TREADY_int_regslice)
    begin
        if (((feature_axis_out_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then 
            feature_axis_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            feature_axis_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    grp_push_fu_388_ap_start <= grp_push_fu_388_ap_start_reg;
    guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1 <= guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core;
    icmp_ln19_1_fu_868_p2 <= "1" when (idx166_fu_254 = ap_const_lv2_3) else "0";
    icmp_ln19_fu_548_p2 <= "1" when (idx_fu_242 = ap_const_lv2_3) else "0";
    icmp_ln753_1_fu_880_p2 <= "1" when (idx169_reg_377 = ap_const_lv5_10) else "0";
    icmp_ln753_fu_565_p2 <= "1" when (idx171_reg_366 = ap_const_lv5_10) else "0";
    mul4_fu_732_p0 <= mul4_fu_732_p00(10 - 1 downto 0);
    mul4_fu_732_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_64_reg_1132),21));
    mul4_fu_732_p1 <= ap_const_lv21_556(12 - 1 downto 0);
    mul_ln754_1_fu_909_p0 <= mul_ln754_1_fu_909_p00(7 - 1 downto 0);
    mul_ln754_1_fu_909_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_first_assign_1_fu_896_p4),15));
    mul_ln754_1_fu_909_p1 <= ap_const_lv15_AB(9 - 1 downto 0);
    mul_ln754_fu_594_p0 <= mul_ln754_fu_594_p00(7 - 1 downto 0);
    mul_ln754_fu_594_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_first_assign_fu_581_p4),15));
    mul_ln754_fu_594_p1 <= ap_const_lv15_AB(9 - 1 downto 0);
    next_mul_fu_442_p2 <= std_logic_vector(unsigned(phi_mul_fu_234) + unsigned(ap_const_lv9_16));
    p_cast17_fu_709_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_701_p3),10));
    p_cast19_fu_783_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_775_p3),11));
    p_cast20_fu_771_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_763_p3),11));
    p_cast21_fu_787_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_64_reg_1132),11));
    p_cast23_fu_840_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_832_p3),16));
    p_cast24_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_448_p4),64));
        p_cast25_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_59_fu_513_p2),48));

    p_cast26_fu_748_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_738_p4),64));
        p_cast27_fu_802_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_66_fu_796_p2),48));

    p_cast29_fu_850_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_71_fu_844_p2),48));
    p_cast3_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_479_p3),7));
        p_cast4_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_58_fu_503_p2),8));

    p_cast5_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_491_p3),8));
    p_first_assign_1_fu_896_p4 <= ((idx166_fu_254 & trunc_ln752_1_fu_892_p1) & ap_const_lv1_0);
    p_first_assign_fu_581_p4 <= ((idx_fu_242 & trunc_ln752_fu_577_p1) & ap_const_lv1_0);
    phi_mul_cast_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(phi_mul_fu_234),12));
    sample_accel_x_fu_1007_p1 <= sample_axis_in_TDATA_int_regslice(16 - 1 downto 0);

    sample_axis_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state11, sample_axis_in_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            sample_axis_in_TDATA_blk_n <= sample_axis_in_TVALID_int_regslice;
        else 
            sample_axis_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sample_axis_in_TREADY <= regslice_both_sample_axis_in_V_data_V_U_ack_in;

    sample_axis_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state11, sample_axis_in_TVALID_int_regslice)
    begin
        if (((sample_axis_in_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            sample_axis_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            sample_axis_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln754_1_fu_667_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln754_fu_661_p2),48));

        sext_ln754_2_fu_972_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln754_1_fu_966_p2),8));

        sext_ln754_3_fu_982_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln754_1_fu_976_p2),48));

        sext_ln754_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln754_fu_651_p2),8));

    shl_ln754_1_fu_986_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv48_3),to_integer(unsigned('0' & sext_ln754_3_fu_982_p1(31-1 downto 0)))));
    shl_ln754_2_fu_627_p3 <= (tmp_11_fu_619_p3 & ap_const_lv6_0);
    shl_ln754_3_fu_635_p3 <= (tmp_11_fu_619_p3 & ap_const_lv4_0);
    shl_ln754_4_fu_942_p3 <= (tmp_15_fu_934_p3 & ap_const_lv6_0);
    shl_ln754_5_fu_950_p3 <= (tmp_15_fu_934_p3 & ap_const_lv4_0);
    shl_ln754_fu_671_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv48_3),to_integer(unsigned('0' & sext_ln754_1_fu_667_p1(31-1 downto 0)))));
    sub_ln754_1_fu_966_p2 <= std_logic_vector(unsigned(zext_ln754_6_fu_958_p1) - unsigned(shl_ln754_4_fu_942_p3));
    sub_ln754_fu_651_p2 <= std_logic_vector(unsigned(zext_ln754_2_fu_643_p1) - unsigned(shl_ln754_2_fu_627_p3));
    tmp_10_fu_604_p4 <= mul_ln754_fu_594_p2(14 downto 13);
    tmp_11_fu_619_p3 <= zext_ln754_5_fu_600_p1(13 downto 13);
    tmp_12_fu_832_p3 <= (empty_70_fu_828_p1 & ap_const_lv2_0);
    tmp_13_fu_1045_p3 <= core_q0(128 downto 128);
    tmp_14_fu_919_p4 <= mul_ln754_1_fu_909_p2(14 downto 13);
    tmp_15_fu_934_p3 <= zext_ln754_9_fu_915_p1(13 downto 13);
    tmp_16_fu_1057_p4 <= core_q1(383 downto 128);
    tmp_1_fu_448_p4 <= phi_mul_fu_234(8 downto 7);
    tmp_2_fu_463_p3 <= phi_mul_cast_fu_426_p1(7 downto 7);
    tmp_3_fu_471_p3 <= (tmp_2_fu_463_p3 & ap_const_lv6_0);
    tmp_4_fu_738_p4 <= mul4_fu_732_p2(20 downto 16);
    tmp_5_fu_479_p3 <= (tmp_2_fu_463_p3 & ap_const_lv4_0);
    tmp_6_fu_491_p3 <= (empty_fu_238 & ap_const_lv3_0);
    tmp_7_fu_763_p3 <= (tmp_s_fu_753_p4 & ap_const_lv6_0);
    tmp_8_fu_701_p3 <= (empty_63_fu_697_p1 & ap_const_lv3_0);
    tmp_9_fu_775_p3 <= (tmp_s_fu_753_p4 & ap_const_lv4_0);
    tmp_nbreadreq_fu_258_p9 <= (0=>(sample_axis_in_TVALID_int_regslice), others=>'-');
    tmp_s_fu_753_p4 <= mul4_fu_732_p2(19 downto 16);
    trunc_ln39_fu_1053_p1 <= core_q0(128 - 1 downto 0);
    trunc_ln752_1_fu_892_p1 <= idx169_reg_377(4 - 1 downto 0);
    trunc_ln752_fu_577_p1 <= idx171_reg_366(4 - 1 downto 0);
    zext_ln754_2_fu_643_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln754_3_fu_635_p3),7));
    zext_ln754_3_fu_647_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_first_assign_fu_581_p4),8));
    zext_ln754_4_fu_929_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_919_p4),64));
    zext_ln754_5_fu_600_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln754_fu_594_p2),21));
    zext_ln754_6_fu_958_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln754_5_fu_950_p3),7));
    zext_ln754_7_fu_962_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_first_assign_1_fu_896_p4),8));
    zext_ln754_9_fu_915_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln754_1_fu_909_p2),21));
    zext_ln754_fu_614_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_604_p4),64));
end behav;
