-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity dsp_core_axis_top_fft128_real_zmpio_step1_kTwiddleImagQ15_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 16; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of dsp_core_axis_top_fft128_real_zmpio_step1_kTwiddleImagQ15_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000000000000000", 1 => "1111100110111000", 2 => "1111001101110100", 3 => "1110110100111000", 
    4 => "1110011100000111", 5 => "1110000011100110", 6 => "1101101011011000", 7 => "1101010011100001", 
    8 => "1100111100000101", 9 => "1100100101000110", 10 => "1100001110101010", 11 => "1011111000110010", 
    12 => "1011100011100100", 13 => "1011001111000001", 14 => "1010111011001101", 15 => "1010101000001011", 
    16 => "1010010101111110", 17 => "1010000100101001", 18 => "1001110100001111", 19 => "1001100100110001", 
    20 => "1001010110010011", 21 => "1001001000110111", 22 => "1000111100011110", 23 => "1000110001001011", 
    24 => "1000100110111111", 25 => "1000011101111100", 26 => "1000010110000100", 27 => "1000001111010111", 
    28 => "1000001001110111", 29 => "1000000101100100", 30 => "1000000010011111", 31 => "1000000000101000", 
    32 => "1000000000000001", 33 => "1000000000101000", 34 => "1000000010011111", 35 => "1000000101100100", 
    36 => "1000001001110111", 37 => "1000001111010111", 38 => "1000010110000100", 39 => "1000011101111100", 
    40 => "1000100110111111", 41 => "1000110001001011", 42 => "1000111100011110", 43 => "1001001000110111", 
    44 => "1001010110010011", 45 => "1001100100110001", 46 => "1001110100001111", 47 => "1010000100101001", 
    48 => "1010010101111110", 49 => "1010101000001011", 50 => "1010111011001101", 51 => "1011001111000001", 
    52 => "1011100011100100", 53 => "1011111000110010", 54 => "1100001110101010", 55 => "1100100101000110", 
    56 => "1100111100000101", 57 => "1101010011100001", 58 => "1101101011011000", 59 => "1110000011100110", 
    60 => "1110011100000111", 61 => "1110110100111000", 62 => "1111001101110100", 63 => "1111100110111000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

