#ifndef ZMPIO_ABI_V3_LAYOUT_HASH_H
#define ZMPIO_ABI_V3_LAYOUT_HASH_H

/* Generated by tools/gen_layout_hash.py -- do not hand edit.
 * Re-run `python tools/gen_layout_hash.py` after changing any ABI-relevant
 * field, size, or enum value in common/zmpio_abi_v3.h (and update that
 * script's SPEC list to match first). */
#define ZMPIO_ABI_V3_LAYOUT_HASH 0x7CF622B4U

#endif
