// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dsp_core_axis_top_push (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sample_0_val,
        sample_1_val,
        sample_2_val,
        sample_8_val,
        core_address0,
        core_ce0,
        core_we0,
        core_d0,
        core_q0,
        core_address1,
        core_ce1,
        core_we1,
        core_d1,
        core_q1
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] sample_0_val;
input  [15:0] sample_1_val;
input  [15:0] sample_2_val;
input  [31:0] sample_8_val;
output  [3:0] core_address0;
output   core_ce0;
output  [47:0] core_we0;
output  [383:0] core_d0;
input  [383:0] core_q0;
output  [3:0] core_address1;
output   core_ce1;
output  [47:0] core_we1;
output  [383:0] core_d1;
input  [383:0] core_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] core_address0;
reg core_ce0;
reg[47:0] core_we0;
reg[383:0] core_d0;
reg[3:0] core_address1;
reg core_ce1;
reg[47:0] core_we1;
reg[383:0] core_d1;

(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] zmpio_step1_kFirCoefficientsQ15_address0;
reg    zmpio_step1_kFirCoefficientsQ15_ce0;
wire   [14:0] zmpio_step1_kFirCoefficientsQ15_q0;
wire   [128:0] grp_fu_365_p2;
reg   [33:0] reg_353;
wire    ap_CS_fsm_state3;
reg   [31:0] mul_ln22_1_reg_377;
wire    ap_CS_fsm_state11;
reg   [58:0] reg_436;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state16;
reg   [57:0] reg_440;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_16_fu_444_p3;
reg   [0:0] tmp_16_reg_1368;
reg   [1:0] axis_1_reg_1407;
wire   [1:0] axis_fu_515_p2;
reg   [1:0] axis_reg_1414;
wire   [15:0] tmp_fu_521_p5;
reg   [15:0] tmp_reg_1419;
wire   [62:0] trunc_ln56_fu_552_p1;
reg   [62:0] trunc_ln56_reg_1431;
wire    ap_CS_fsm_state4;
wire   [63:0] add_ln56_fu_574_p2;
reg   [63:0] add_ln56_reg_1436;
wire   [3:0] empty_fu_654_p1;
reg   [3:0] empty_reg_1441;
wire    ap_CS_fsm_state8;
wire   [4:0] tap_fu_664_p2;
reg   [4:0] tap_reg_1450;
wire    ap_CS_fsm_state9;
wire   [6:0] or_ln_fu_684_p4;
reg   [6:0] or_ln_reg_1455;
wire   [1:0] tmp_20_fu_698_p4;
reg   [1:0] tmp_20_reg_1460;
wire   [33:0] accumulator_1_fu_929_p2;
wire    ap_CS_fsm_state10;
wire  signed [63:0] sext_ln44_fu_977_p1;
reg  signed [63:0] sext_ln44_reg_1481;
wire    ap_CS_fsm_state12;
reg   [61:0] tmp_22_reg_1514;
wire    ap_CS_fsm_state15;
wire   [63:0] and_ln_fu_1157_p3;
reg   [63:0] and_ln_reg_1519;
wire   [0:0] and_ln95_fu_1313_p2;
reg   [0:0] and_ln95_reg_1524;
wire    ap_CS_fsm_state19;
wire    grp_build_frame_fu_400_ap_start;
wire    grp_build_frame_fu_400_ap_done;
wire    grp_build_frame_fu_400_ap_idle;
wire    grp_build_frame_fu_400_ap_ready;
wire   [3:0] grp_build_frame_fu_400_core_address0;
wire    grp_build_frame_fu_400_core_ce0;
wire   [47:0] grp_build_frame_fu_400_core_we0;
wire   [383:0] grp_build_frame_fu_400_core_d0;
reg   [4:0] tap_1_reg_342;
reg    grp_build_frame_fu_400_ap_start_reg;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire   [63:0] zext_ln34_4_fu_588_p1;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln38_1_fu_708_p1;
wire   [0:0] icmp_ln36_fu_658_p2;
wire   [63:0] zext_ln36_fu_670_p1;
wire   [63:0] zext_ln90_4_fu_1177_p1;
wire    ap_CS_fsm_state17;
reg   [3:0] phi_ln44_fu_232;
wire   [3:0] add_ln33_fu_838_p2;
wire   [0:0] icmp_ln33_fu_509_p2;
reg   [1:0] axis_2_fu_236;
reg   [15:0] x_fu_240;
wire   [15:0] output_0_fu_815_p3;
reg   [15:0] y_fu_244;
reg   [15:0] z_fu_248;
reg   [62:0] bit_fu_252;
wire   [62:0] zext_ln50_fu_1003_p1;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln49_fu_988_p2;
reg   [63:0] value_assign_18_fu_256;
wire   [63:0] select_ln53_1_fu_1094_p3;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln52_fu_1029_p2;
reg   [63:0] result_fu_260;
wire   [63:0] result_3_fu_1086_p3;
reg   [62:0] bit_2_fu_264;
wire   [62:0] zext_ln59_fu_1112_p1;
wire   [383:0] zext_ln31_fu_476_p1;
wire   [383:0] zext_ln44_fu_536_p1;
wire   [383:0] shl_ln34_2_fu_647_p2;
wire   [47:0] shl_ln34_fu_628_p2;
wire    ap_CS_fsm_state7;
wire   [383:0] shl_ln90_2_fu_1236_p2;
wire   [47:0] shl_ln90_fu_1217_p2;
wire    ap_CS_fsm_state18;
wire   [383:0] zext_ln92_fu_1267_p1;
wire   [383:0] zext_ln93_fu_1286_p1;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire   [383:0] zext_ln35_fu_1343_p1;
reg  signed [64:0] grp_fu_365_p0;
wire  signed [31:0] sext_ln19_fu_541_p1;
wire   [128:0] zext_ln34_1_fu_580_p1;
wire   [14:0] zext_ln38_2_fu_693_p1;
wire  signed [30:0] sext_ln189_fu_915_p1;
wire  signed [31:0] sext_ln20_fu_938_p1;
wire  signed [31:0] sext_ln21_fu_947_p1;
wire   [128:0] zext_ln90_2_fu_1164_p1;
reg  signed [66:0] grp_fu_365_p1;
wire  signed [30:0] sext_ln38_2_fu_920_p1;
wire   [63:0] trunc_ln1_fu_452_p4;
wire   [63:0] add_ln31_fu_462_p2;
wire   [255:0] shl_ln_fu_468_p3;
wire   [6:0] shl_ln1_fu_556_p3;
wire   [63:0] shl_ln56_2_fu_567_p3;
wire   [63:0] zext_ln56_fu_563_p1;
wire   [62:0] shl_ln34_4_fu_601_p3;
wire   [63:0] zext_ln34_2_fu_609_p1;
wire   [63:0] shl_ln34_3_fu_593_p3;
wire   [63:0] sub_ln34_fu_613_p2;
wire   [63:0] add_ln34_fu_619_p2;
wire   [47:0] trunc_ln34_fu_624_p1;
wire   [66:0] shl_ln34_1_fu_635_p3;
wire   [383:0] zext_ln34_fu_585_p1;
wire   [383:0] zext_ln34_3_fu_643_p1;
wire   [3:0] trunc_ln37_fu_675_p1;
wire   [3:0] sub_ln56_fu_679_p2;
wire   [14:0] tmp_20_fu_698_p1;
wire   [33:0] add_ln12_fu_721_p2;
wire   [18:0] trunc_ln3_fu_727_p4;
wire   [33:0] sub_ln14_fu_741_p2;
wire   [18:0] trunc_ln4_fu_747_p4;
wire  signed [19:0] sext_ln14_1_fu_757_p1;
wire   [0:0] tmp_18_fu_713_p3;
wire   [19:0] sub_ln14_1_fu_761_p2;
wire  signed [19:0] sext_ln14_fu_737_p1;
wire   [19:0] select_ln11_fu_767_p3;
wire   [4:0] tmp_19_fu_775_p4;
wire   [0:0] icmp_ln27_fu_785_p2;
wire   [0:0] icmp_ln30_fu_791_p2;
wire   [0:0] or_ln27_fu_809_p2;
wire   [15:0] select_ln27_fu_801_p3;
wire   [15:0] trunc_ln33_fu_797_p1;
wire   [5:0] shl_ln38_2_fu_862_p3;
wire   [7:0] zext_ln38_3_fu_869_p1;
wire   [7:0] shl_ln38_1_fu_855_p3;
wire   [7:0] sub_ln38_fu_873_p2;
wire  signed [8:0] sext_ln38_fu_879_p1;
wire   [8:0] zext_ln38_fu_852_p1;
wire   [8:0] add_ln38_fu_883_p2;
wire   [11:0] tmp_21_fu_889_p3;
wire  signed [66:0] sext_ln38_1_fu_897_p1;
wire   [383:0] zext_ln38_4_fu_901_p1;
wire   [383:0] lshr_ln38_fu_905_p2;
wire   [15:0] trunc_ln38_fu_911_p1;
wire   [30:0] sext_ln38_3_fu_925_p0;
wire  signed [33:0] sext_ln38_3_fu_925_p1;
wire   [31:0] sext_ln22_fu_953_p0;
wire   [31:0] sext_ln22_2_fu_961_p0;
wire  signed [32:0] sext_ln22_fu_953_p1;
wire  signed [32:0] sext_ln22_2_fu_961_p1;
wire   [32:0] add_ln22_fu_965_p2;
wire  signed [32:0] sext_ln22_1_fu_957_p1;
wire   [32:0] add_ln22_1_fu_971_p2;
wire   [63:0] zext_ln47_fu_984_p1;
wire   [60:0] bit_4_fu_993_p4;
wire   [63:0] zext_ln44_1_fu_1038_p1;
wire   [63:0] add_ln53_fu_1042_p2;
wire   [0:0] icmp_ln53_fu_1048_p2;
wire   [62:0] result_2_fu_1066_p4;
wire   [63:0] zext_ln55_fu_1076_p1;
wire   [0:0] xor_ln53_fu_1054_p2;
wire   [63:0] result_1_fu_1080_p2;
wire   [63:0] sub_ln54_fu_1060_p2;
wire   [60:0] bit_6_fu_1102_p4;
wire   [63:0] trunc_ln8_fu_1131_p4;
wire   [63:0] add_ln56_1_fu_1141_p2;
wire   [31:0] trunc_ln61_fu_1169_p1;
wire   [62:0] shl_ln90_4_fu_1190_p3;
wire   [63:0] zext_ln90_1_fu_1198_p1;
wire   [63:0] shl_ln90_3_fu_1182_p3;
wire   [63:0] sub_ln90_fu_1202_p2;
wire   [63:0] add_ln90_fu_1208_p2;
wire   [47:0] trunc_ln90_fu_1213_p1;
wire   [66:0] shl_ln90_1_fu_1224_p3;
wire   [383:0] zext_ln90_fu_1173_p1;
wire   [383:0] zext_ln90_3_fu_1232_p1;
wire   [6:0] trunc_ln_fu_1243_p4;
wire   [6:0] add_ln92_fu_1253_p2;
wire   [326:0] shl_ln2_fu_1259_p3;
wire   [63:0] trunc_ln93_fu_1272_p1;
wire   [63:0] add_ln93_fu_1276_p2;
wire   [56:0] tmp_25_fu_1291_p4;
wire   [5:0] trunc_ln93_1_fu_1282_p1;
wire   [0:0] icmp_ln95_fu_1301_p2;
wire   [0:0] icmp_ln96_fu_1307_p2;
wire   [63:0] trunc_ln2_fu_1319_p4;
wire   [63:0] add_ln35_fu_1329_p2;
wire   [319:0] shl_ln3_fu_1335_p3;
reg   [23:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 grp_build_frame_fu_400_ap_start_reg = 1'b0;
#0 phi_ln44_fu_232 = 4'd0;
#0 axis_2_fu_236 = 2'd0;
#0 x_fu_240 = 16'd0;
#0 y_fu_244 = 16'd0;
#0 z_fu_248 = 16'd0;
#0 bit_fu_252 = 63'd0;
#0 value_assign_18_fu_256 = 64'd0;
#0 result_fu_260 = 64'd0;
#0 bit_2_fu_264 = 63'd0;
end

dsp_core_axis_top_push_zmpio_step1_kFirCoefficientsQ15_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
zmpio_step1_kFirCoefficientsQ15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(zmpio_step1_kFirCoefficientsQ15_address0),
    .ce0(zmpio_step1_kFirCoefficientsQ15_ce0),
    .q0(zmpio_step1_kFirCoefficientsQ15_q0)
);

dsp_core_axis_top_build_frame grp_build_frame_fu_400(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_build_frame_fu_400_ap_start),
    .ap_done(grp_build_frame_fu_400_ap_done),
    .ap_idle(grp_build_frame_fu_400_ap_idle),
    .ap_ready(grp_build_frame_fu_400_ap_ready),
    .sample_sequence(sample_8_val),
    .core_address0(grp_build_frame_fu_400_core_address0),
    .core_ce0(grp_build_frame_fu_400_core_ce0),
    .core_we0(grp_build_frame_fu_400_core_we0),
    .core_d0(grp_build_frame_fu_400_core_d0),
    .core_q0(core_q0)
);

dsp_core_axis_top_mul_65s_67s_129_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 67 ),
    .dout_WIDTH( 129 ))
mul_65s_67s_129_1_1_U22(
    .din0(grp_fu_365_p0),
    .din1(grp_fu_365_p1),
    .dout(grp_fu_365_p2)
);

dsp_core_axis_top_mux_3_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_3_2_16_1_1_U23(
    .din0(sample_0_val),
    .din1(sample_1_val),
    .din2(sample_2_val),
    .din3(axis_2_fu_236),
    .dout(tmp_fu_521_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_build_frame_fu_400_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            grp_build_frame_fu_400_ap_start_reg <= 1'b1;
        end else if ((grp_build_frame_fu_400_ap_ready == 1'b1)) begin
            grp_build_frame_fu_400_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_16_fu_444_p3 == 1'd0))) begin
        axis_2_fu_236 <= 2'd0;
    end else if (((icmp_ln36_fu_658_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        axis_2_fu_236 <= axis_reg_1414;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_fu_988_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
                bit_2_fu_264[0] <= bit_fu_252[0];
        bit_2_fu_264[2] <= bit_fu_252[2];
        bit_2_fu_264[4] <= bit_fu_252[4];
        bit_2_fu_264[6] <= bit_fu_252[6];
        bit_2_fu_264[8] <= bit_fu_252[8];
        bit_2_fu_264[10] <= bit_fu_252[10];
        bit_2_fu_264[12] <= bit_fu_252[12];
        bit_2_fu_264[14] <= bit_fu_252[14];
        bit_2_fu_264[16] <= bit_fu_252[16];
        bit_2_fu_264[18] <= bit_fu_252[18];
        bit_2_fu_264[20] <= bit_fu_252[20];
        bit_2_fu_264[22] <= bit_fu_252[22];
        bit_2_fu_264[24] <= bit_fu_252[24];
        bit_2_fu_264[26] <= bit_fu_252[26];
        bit_2_fu_264[28] <= bit_fu_252[28];
        bit_2_fu_264[30] <= bit_fu_252[30];
        bit_2_fu_264[32] <= bit_fu_252[32];
        bit_2_fu_264[34] <= bit_fu_252[34];
        bit_2_fu_264[36] <= bit_fu_252[36];
        bit_2_fu_264[38] <= bit_fu_252[38];
        bit_2_fu_264[40] <= bit_fu_252[40];
        bit_2_fu_264[42] <= bit_fu_252[42];
        bit_2_fu_264[44] <= bit_fu_252[44];
        bit_2_fu_264[46] <= bit_fu_252[46];
        bit_2_fu_264[48] <= bit_fu_252[48];
        bit_2_fu_264[50] <= bit_fu_252[50];
        bit_2_fu_264[52] <= bit_fu_252[52];
        bit_2_fu_264[54] <= bit_fu_252[54];
        bit_2_fu_264[56] <= bit_fu_252[56];
        bit_2_fu_264[58] <= bit_fu_252[58];
        bit_2_fu_264[60] <= bit_fu_252[60];
        bit_2_fu_264[62] <= bit_fu_252[62];
    end else if (((icmp_ln52_fu_1029_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
                bit_2_fu_264[0] <= zext_ln59_fu_1112_p1[0];
        bit_2_fu_264[2] <= zext_ln59_fu_1112_p1[2];
        bit_2_fu_264[4] <= zext_ln59_fu_1112_p1[4];
        bit_2_fu_264[6] <= zext_ln59_fu_1112_p1[6];
        bit_2_fu_264[8] <= zext_ln59_fu_1112_p1[8];
        bit_2_fu_264[10] <= zext_ln59_fu_1112_p1[10];
        bit_2_fu_264[12] <= zext_ln59_fu_1112_p1[12];
        bit_2_fu_264[14] <= zext_ln59_fu_1112_p1[14];
        bit_2_fu_264[16] <= zext_ln59_fu_1112_p1[16];
        bit_2_fu_264[18] <= zext_ln59_fu_1112_p1[18];
        bit_2_fu_264[20] <= zext_ln59_fu_1112_p1[20];
        bit_2_fu_264[22] <= zext_ln59_fu_1112_p1[22];
        bit_2_fu_264[24] <= zext_ln59_fu_1112_p1[24];
        bit_2_fu_264[26] <= zext_ln59_fu_1112_p1[26];
        bit_2_fu_264[28] <= zext_ln59_fu_1112_p1[28];
        bit_2_fu_264[30] <= zext_ln59_fu_1112_p1[30];
        bit_2_fu_264[32] <= zext_ln59_fu_1112_p1[32];
        bit_2_fu_264[34] <= zext_ln59_fu_1112_p1[34];
        bit_2_fu_264[36] <= zext_ln59_fu_1112_p1[36];
        bit_2_fu_264[38] <= zext_ln59_fu_1112_p1[38];
        bit_2_fu_264[40] <= zext_ln59_fu_1112_p1[40];
        bit_2_fu_264[42] <= zext_ln59_fu_1112_p1[42];
        bit_2_fu_264[44] <= zext_ln59_fu_1112_p1[44];
        bit_2_fu_264[46] <= zext_ln59_fu_1112_p1[46];
        bit_2_fu_264[48] <= zext_ln59_fu_1112_p1[48];
        bit_2_fu_264[50] <= zext_ln59_fu_1112_p1[50];
        bit_2_fu_264[52] <= zext_ln59_fu_1112_p1[52];
        bit_2_fu_264[54] <= zext_ln59_fu_1112_p1[54];
        bit_2_fu_264[56] <= zext_ln59_fu_1112_p1[56];
        bit_2_fu_264[58] <= zext_ln59_fu_1112_p1[58];
        bit_2_fu_264[60] <= zext_ln59_fu_1112_p1[60];
        bit_2_fu_264[62] <= zext_ln59_fu_1112_p1[62];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln33_fu_509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                bit_fu_252[0] <= 1'b0;
        bit_fu_252[2] <= 1'b0;
        bit_fu_252[4] <= 1'b0;
        bit_fu_252[6] <= 1'b0;
        bit_fu_252[8] <= 1'b0;
        bit_fu_252[10] <= 1'b0;
        bit_fu_252[12] <= 1'b0;
        bit_fu_252[14] <= 1'b0;
        bit_fu_252[16] <= 1'b0;
        bit_fu_252[18] <= 1'b0;
        bit_fu_252[20] <= 1'b0;
        bit_fu_252[22] <= 1'b0;
        bit_fu_252[24] <= 1'b0;
        bit_fu_252[26] <= 1'b0;
        bit_fu_252[28] <= 1'b0;
        bit_fu_252[30] <= 1'b0;
        bit_fu_252[32] <= 1'b0;
        bit_fu_252[34] <= 1'b0;
        bit_fu_252[36] <= 1'b0;
        bit_fu_252[38] <= 1'b0;
        bit_fu_252[40] <= 1'b0;
        bit_fu_252[42] <= 1'b0;
        bit_fu_252[44] <= 1'b0;
        bit_fu_252[46] <= 1'b0;
        bit_fu_252[48] <= 1'b0;
        bit_fu_252[50] <= 1'b0;
        bit_fu_252[52] <= 1'b0;
        bit_fu_252[54] <= 1'b0;
        bit_fu_252[56] <= 1'b0;
        bit_fu_252[58] <= 1'b0;
        bit_fu_252[60] <= 1'b0;
        bit_fu_252[62] <= 1'b1;
    end else if (((icmp_ln49_fu_988_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
                bit_fu_252[0] <= zext_ln50_fu_1003_p1[0];
        bit_fu_252[2] <= zext_ln50_fu_1003_p1[2];
        bit_fu_252[4] <= zext_ln50_fu_1003_p1[4];
        bit_fu_252[6] <= zext_ln50_fu_1003_p1[6];
        bit_fu_252[8] <= zext_ln50_fu_1003_p1[8];
        bit_fu_252[10] <= zext_ln50_fu_1003_p1[10];
        bit_fu_252[12] <= zext_ln50_fu_1003_p1[12];
        bit_fu_252[14] <= zext_ln50_fu_1003_p1[14];
        bit_fu_252[16] <= zext_ln50_fu_1003_p1[16];
        bit_fu_252[18] <= zext_ln50_fu_1003_p1[18];
        bit_fu_252[20] <= zext_ln50_fu_1003_p1[20];
        bit_fu_252[22] <= zext_ln50_fu_1003_p1[22];
        bit_fu_252[24] <= zext_ln50_fu_1003_p1[24];
        bit_fu_252[26] <= zext_ln50_fu_1003_p1[26];
        bit_fu_252[28] <= zext_ln50_fu_1003_p1[28];
        bit_fu_252[30] <= zext_ln50_fu_1003_p1[30];
        bit_fu_252[32] <= zext_ln50_fu_1003_p1[32];
        bit_fu_252[34] <= zext_ln50_fu_1003_p1[34];
        bit_fu_252[36] <= zext_ln50_fu_1003_p1[36];
        bit_fu_252[38] <= zext_ln50_fu_1003_p1[38];
        bit_fu_252[40] <= zext_ln50_fu_1003_p1[40];
        bit_fu_252[42] <= zext_ln50_fu_1003_p1[42];
        bit_fu_252[44] <= zext_ln50_fu_1003_p1[44];
        bit_fu_252[46] <= zext_ln50_fu_1003_p1[46];
        bit_fu_252[48] <= zext_ln50_fu_1003_p1[48];
        bit_fu_252[50] <= zext_ln50_fu_1003_p1[50];
        bit_fu_252[52] <= zext_ln50_fu_1003_p1[52];
        bit_fu_252[54] <= zext_ln50_fu_1003_p1[54];
        bit_fu_252[56] <= zext_ln50_fu_1003_p1[56];
        bit_fu_252[58] <= zext_ln50_fu_1003_p1[58];
        bit_fu_252[60] <= zext_ln50_fu_1003_p1[60];
        bit_fu_252[62] <= zext_ln50_fu_1003_p1[62];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_16_fu_444_p3 == 1'd0))) begin
        phi_ln44_fu_232 <= 4'd0;
    end else if (((icmp_ln36_fu_658_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        phi_ln44_fu_232 <= add_ln33_fu_838_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_353 <= accumulator_1_fu_929_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_353 <= 34'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        reg_353 <= grp_fu_365_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_fu_988_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        result_fu_260 <= 64'd0;
    end else if (((icmp_ln52_fu_1029_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        result_fu_260 <= result_3_fu_1086_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tap_1_reg_342 <= tap_reg_1450;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        tap_1_reg_342 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_fu_988_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        value_assign_18_fu_256 <= sext_ln44_reg_1481;
    end else if (((icmp_ln52_fu_1029_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        value_assign_18_fu_256 <= select_ln53_1_fu_1094_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_16_fu_444_p3 == 1'd0))) begin
        x_fu_240 <= 16'd0;
    end else if (((icmp_ln36_fu_658_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9) & (axis_1_reg_1407 == 2'd0))) begin
        x_fu_240 <= output_0_fu_815_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_16_fu_444_p3 == 1'd0))) begin
        y_fu_244 <= 16'd0;
    end else if (((icmp_ln36_fu_658_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9) & (axis_1_reg_1407 == 2'd1))) begin
        y_fu_244 <= output_0_fu_815_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_16_fu_444_p3 == 1'd0))) begin
        z_fu_248 <= 16'd0;
    end else if ((~(axis_1_reg_1407 == 2'd1) & ~(axis_1_reg_1407 == 2'd0) & (icmp_ln36_fu_658_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        z_fu_248 <= output_0_fu_815_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln56_reg_1436[63 : 1] <= add_ln56_fu_574_p2[63 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        and_ln95_reg_1524 <= and_ln95_fu_1313_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        and_ln_reg_1519[63 : 2] <= and_ln_fu_1157_p3[63 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        axis_1_reg_1407 <= axis_2_fu_236;
        axis_reg_1414 <= axis_fu_515_p2;
        tmp_reg_1419 <= tmp_fu_521_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        empty_reg_1441 <= empty_fu_654_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        mul_ln22_1_reg_377 <= grp_fu_365_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        or_ln_reg_1455[6 : 1] <= or_ln_fu_684_p4[6 : 1];
        tap_reg_1450 <= tap_fu_664_p2;
        tmp_20_reg_1460 <= {{tmp_20_fu_698_p1[14:13]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_436 <= {{grp_fu_365_p2[128:70]}};
        reg_440 <= {{grp_fu_365_p2[127:70]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        sext_ln44_reg_1481 <= sext_ln44_fu_977_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_16_reg_1368 <= core_q0[32'd128];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        tmp_22_reg_1514 <= {{add_ln56_1_fu_1141_p2[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln56_reg_1431 <= trunc_ln56_fu_552_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_build_frame_fu_400_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        core_address0 = 4'd13;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        core_address0 = zext_ln90_4_fu_1177_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state19))) begin
        core_address0 = 4'd12;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        core_address0 = zext_ln38_1_fu_708_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        core_address0 = zext_ln34_4_fu_588_p1;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((icmp_ln33_fu_509_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln33_fu_509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        core_address0 = 4'd2;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        core_address0 = 4'd14;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        core_address0 = grp_build_frame_fu_400_core_address0;
    end else begin
        core_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        core_address1 = 4'd14;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        core_address1 = 4'd13;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        core_address1 = 4'd12;
    end else begin
        core_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2) | ((icmp_ln33_fu_509_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln33_fu_509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        core_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        core_ce0 = grp_build_frame_fu_400_core_ce0;
    end else begin
        core_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state19))) begin
        core_ce1 = 1'b1;
    end else begin
        core_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        core_d0 = zext_ln92_fu_1267_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        core_d0 = shl_ln90_2_fu_1236_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        core_d0 = shl_ln34_2_fu_647_p2;
    end else if (((icmp_ln33_fu_509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        core_d0 = zext_ln44_fu_536_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        core_d0 = zext_ln31_fu_476_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        core_d0 = grp_build_frame_fu_400_core_d0;
    end else begin
        core_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        core_d1 = zext_ln35_fu_1343_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        core_d1 = 384'd340282366920938463463374607431768211456;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        core_d1 = zext_ln93_fu_1286_p1;
    end else begin
        core_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        core_we0 = 48'd280375465082880;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        core_we0 = shl_ln90_fu_1217_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        core_we0 = shl_ln34_fu_628_p2;
    end else if (((icmp_ln33_fu_509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        core_we0 = 48'd255;
    end else if (((1'b1 == ap_CS_fsm_state2) & (tmp_16_fu_444_p3 == 1'd0))) begin
        core_we0 = 48'd4278190080;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        core_we0 = grp_build_frame_fu_400_core_we0;
    end else begin
        core_we0 = 48'd0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln95_reg_1524) & (1'b1 == ap_CS_fsm_state24) & (tmp_16_reg_1368 == 1'd0))) begin
        core_we1 = 48'd1095216660480;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        core_we1 = 48'd65536;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        core_we1 = 48'd255;
    end else begin
        core_we1 = 48'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_365_p0 = zext_ln90_2_fu_1164_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_365_p0 = sext_ln21_fu_947_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_365_p0 = sext_ln20_fu_938_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_365_p0 = sext_ln189_fu_915_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_365_p0 = zext_ln38_2_fu_693_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_365_p0 = zext_ln34_1_fu_580_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_365_p0 = sext_ln19_fu_541_p1;
    end else begin
        grp_fu_365_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_365_p1 = sext_ln21_fu_947_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_365_p1 = sext_ln20_fu_938_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_365_p1 = sext_ln38_2_fu_920_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_365_p1 = 15'd171;
    end else if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state5))) begin
        grp_fu_365_p1 = 129'd24595658764946068822;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_365_p1 = sext_ln19_fu_541_p1;
    end else begin
        grp_fu_365_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        zmpio_step1_kFirCoefficientsQ15_ce0 = 1'b1;
    end else begin
        zmpio_step1_kFirCoefficientsQ15_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (tmp_16_fu_444_p3 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln33_fu_509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln36_fu_658_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((icmp_ln49_fu_988_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln52_fu_1029_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((1'd0 == and_ln95_fu_1313_p2) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((1'b1 == ap_CS_fsm_state21) & (grp_build_frame_fu_400_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accumulator_1_fu_929_p2 = ($signed(sext_ln38_3_fu_925_p1) + $signed(reg_353));

assign add_ln12_fu_721_p2 = (reg_353 + 34'd16384);

assign add_ln22_1_fu_971_p2 = ($signed(add_ln22_fu_965_p2) + $signed(sext_ln22_1_fu_957_p1));

assign add_ln22_fu_965_p2 = ($signed(sext_ln22_fu_953_p1) + $signed(sext_ln22_2_fu_961_p1));

assign add_ln31_fu_462_p2 = (trunc_ln1_fu_452_p4 + 64'd1);

assign add_ln33_fu_838_p2 = (empty_reg_1441 + 4'd1);

assign add_ln34_fu_619_p2 = (add_ln56_reg_1436 + sub_ln34_fu_613_p2);

assign add_ln35_fu_1329_p2 = (trunc_ln2_fu_1319_p4 + 64'd1);

assign add_ln38_fu_883_p2 = ($signed(sext_ln38_fu_879_p1) + $signed(zext_ln38_fu_852_p1));

assign add_ln53_fu_1042_p2 = (result_fu_260 + zext_ln44_1_fu_1038_p1);

assign add_ln56_1_fu_1141_p2 = (trunc_ln8_fu_1131_p4 + 64'd104);

assign add_ln56_fu_574_p2 = (shl_ln56_2_fu_567_p3 + zext_ln56_fu_563_p1);

assign add_ln90_fu_1208_p2 = (and_ln_reg_1519 + sub_ln90_fu_1202_p2);

assign add_ln92_fu_1253_p2 = (trunc_ln_fu_1243_p4 + 7'd1);

assign add_ln93_fu_1276_p2 = (trunc_ln93_fu_1272_p1 + 64'd1);

assign and_ln95_fu_1313_p2 = (icmp_ln96_fu_1307_p2 & icmp_ln95_fu_1301_p2);

assign and_ln_fu_1157_p3 = {{tmp_22_reg_1514}, {2'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign axis_fu_515_p2 = (axis_2_fu_236 + 2'd1);

assign bit_4_fu_993_p4 = {{bit_fu_252[62:2]}};

assign bit_6_fu_1102_p4 = {{bit_2_fu_264[62:2]}};

assign empty_fu_654_p1 = core_q0[3:0];

assign grp_build_frame_fu_400_ap_start = grp_build_frame_fu_400_ap_start_reg;

assign icmp_ln27_fu_785_p2 = (($signed(tmp_19_fu_775_p4) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_791_p2 = (($signed(select_ln11_fu_767_p3) < $signed(20'd1015808)) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_509_p2 = ((axis_2_fu_236 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_658_p2 = ((tap_1_reg_342 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_988_p2 = ((zext_ln47_fu_984_p1 > sext_ln44_reg_1481) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_1029_p2 = ((bit_2_fu_264 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_1048_p2 = ((value_assign_18_fu_256 < add_ln53_fu_1042_p2) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_1301_p2 = ((tmp_25_fu_1291_p4 != 57'd0) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_1307_p2 = ((trunc_ln93_1_fu_1282_p1 == 6'd0) ? 1'b1 : 1'b0);

assign lshr_ln38_fu_905_p2 = core_q0 >> zext_ln38_4_fu_901_p1;

assign or_ln27_fu_809_p2 = (icmp_ln30_fu_791_p2 | icmp_ln27_fu_785_p2);

assign or_ln_fu_684_p4 = {{{axis_2_fu_236}, {sub_ln56_fu_679_p2}}, {1'd0}};

assign output_0_fu_815_p3 = ((or_ln27_fu_809_p2[0:0] == 1'b1) ? select_ln27_fu_801_p3 : trunc_ln33_fu_797_p1);

assign result_1_fu_1080_p2 = (zext_ln55_fu_1076_p1 + zext_ln44_1_fu_1038_p1);

assign result_2_fu_1066_p4 = {{result_fu_260[63:1]}};

assign result_3_fu_1086_p3 = ((xor_ln53_fu_1054_p2[0:0] == 1'b1) ? result_1_fu_1080_p2 : zext_ln55_fu_1076_p1);

assign select_ln11_fu_767_p3 = ((tmp_18_fu_713_p3[0:0] == 1'b1) ? sub_ln14_1_fu_761_p2 : sext_ln14_fu_737_p1);

assign select_ln27_fu_801_p3 = ((icmp_ln27_fu_785_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln53_1_fu_1094_p3 = ((xor_ln53_fu_1054_p2[0:0] == 1'b1) ? sub_ln54_fu_1060_p2 : value_assign_18_fu_256);

assign sext_ln14_1_fu_757_p1 = $signed(trunc_ln4_fu_747_p4);

assign sext_ln14_fu_737_p1 = $signed(trunc_ln3_fu_727_p4);

assign sext_ln189_fu_915_p1 = $signed(trunc_ln38_fu_911_p1);

assign sext_ln19_fu_541_p1 = $signed(x_fu_240);

assign sext_ln20_fu_938_p1 = $signed(y_fu_244);

assign sext_ln21_fu_947_p1 = $signed(z_fu_248);

assign sext_ln22_1_fu_957_p1 = $signed(mul_ln22_1_reg_377);

assign sext_ln22_2_fu_961_p0 = grp_fu_365_p2;

assign sext_ln22_2_fu_961_p1 = $signed(sext_ln22_2_fu_961_p0);

assign sext_ln22_fu_953_p0 = reg_353;

assign sext_ln22_fu_953_p1 = $signed(sext_ln22_fu_953_p0);

assign sext_ln38_1_fu_897_p1 = $signed(tmp_21_fu_889_p3);

assign sext_ln38_2_fu_920_p1 = $signed(zmpio_step1_kFirCoefficientsQ15_q0);

assign sext_ln38_3_fu_925_p0 = grp_fu_365_p2;

assign sext_ln38_3_fu_925_p1 = $signed(sext_ln38_3_fu_925_p0);

assign sext_ln38_fu_879_p1 = $signed(sub_ln38_fu_873_p2);

assign sext_ln44_fu_977_p1 = $signed(add_ln22_1_fu_971_p2);

assign shl_ln1_fu_556_p3 = {{axis_2_fu_236}, {5'd0}};

assign shl_ln2_fu_1259_p3 = {{add_ln92_fu_1253_p2}, {320'd0}};

assign shl_ln34_1_fu_635_p3 = {{add_ln34_fu_619_p2}, {3'd0}};

assign shl_ln34_2_fu_647_p2 = zext_ln34_fu_585_p1 << zext_ln34_3_fu_643_p1;

assign shl_ln34_3_fu_593_p3 = {{reg_440}, {6'd0}};

assign shl_ln34_4_fu_601_p3 = {{reg_436}, {4'd0}};

assign shl_ln34_fu_628_p2 = 48'd3 << trunc_ln34_fu_624_p1;

assign shl_ln38_1_fu_855_p3 = {{tmp_20_reg_1460}, {6'd0}};

assign shl_ln38_2_fu_862_p3 = {{tmp_20_reg_1460}, {4'd0}};

assign shl_ln3_fu_1335_p3 = {{add_ln35_fu_1329_p2}, {256'd0}};

assign shl_ln56_2_fu_567_p3 = {{trunc_ln56_reg_1431}, {1'd0}};

assign shl_ln90_1_fu_1224_p3 = {{add_ln90_fu_1208_p2}, {3'd0}};

assign shl_ln90_2_fu_1236_p2 = zext_ln90_fu_1173_p1 << zext_ln90_3_fu_1232_p1;

assign shl_ln90_3_fu_1182_p3 = {{reg_440}, {6'd0}};

assign shl_ln90_4_fu_1190_p3 = {{reg_436}, {4'd0}};

assign shl_ln90_fu_1217_p2 = 48'd15 << trunc_ln90_fu_1213_p1;

assign shl_ln_fu_468_p3 = {{add_ln31_fu_462_p2}, {192'd0}};

assign sub_ln14_1_fu_761_p2 = ($signed(20'd0) - $signed(sext_ln14_1_fu_757_p1));

assign sub_ln14_fu_741_p2 = (34'd16384 - reg_353);

assign sub_ln34_fu_613_p2 = (zext_ln34_2_fu_609_p1 - shl_ln34_3_fu_593_p3);

assign sub_ln38_fu_873_p2 = (zext_ln38_3_fu_869_p1 - shl_ln38_1_fu_855_p3);

assign sub_ln54_fu_1060_p2 = (value_assign_18_fu_256 - add_ln53_fu_1042_p2);

assign sub_ln56_fu_679_p2 = (empty_reg_1441 - trunc_ln37_fu_675_p1);

assign sub_ln90_fu_1202_p2 = (zext_ln90_1_fu_1198_p1 - shl_ln90_3_fu_1182_p3);

assign tap_fu_664_p2 = (tap_1_reg_342 + 5'd1);

assign tmp_16_fu_444_p3 = core_q0[32'd128];

assign tmp_18_fu_713_p3 = reg_353[32'd33];

assign tmp_19_fu_775_p4 = {{select_ln11_fu_767_p3[19:15]}};

assign tmp_20_fu_698_p1 = grp_fu_365_p2;

assign tmp_20_fu_698_p4 = {{tmp_20_fu_698_p1[14:13]}};

assign tmp_21_fu_889_p3 = {{add_ln38_fu_883_p2}, {3'd0}};

assign tmp_25_fu_1291_p4 = {{add_ln93_fu_1276_p2[63:7]}};

assign trunc_ln1_fu_452_p4 = {{core_q0[255:192]}};

assign trunc_ln2_fu_1319_p4 = {{core_q1[319:256]}};

assign trunc_ln33_fu_797_p1 = select_ln11_fu_767_p3[15:0];

assign trunc_ln34_fu_624_p1 = add_ln34_fu_619_p2[47:0];

assign trunc_ln37_fu_675_p1 = tap_1_reg_342[3:0];

assign trunc_ln38_fu_911_p1 = lshr_ln38_fu_905_p2[15:0];

assign trunc_ln3_fu_727_p4 = {{add_ln12_fu_721_p2[33:15]}};

assign trunc_ln4_fu_747_p4 = {{sub_ln14_fu_741_p2[33:15]}};

assign trunc_ln56_fu_552_p1 = core_q0[62:0];

assign trunc_ln61_fu_1169_p1 = result_fu_260[31:0];

assign trunc_ln8_fu_1131_p4 = {{core_q0[381:318]}};

assign trunc_ln90_fu_1213_p1 = add_ln90_fu_1208_p2[47:0];

assign trunc_ln93_1_fu_1282_p1 = add_ln93_fu_1276_p2[5:0];

assign trunc_ln93_fu_1272_p1 = core_q0[63:0];

assign trunc_ln_fu_1243_p4 = {{core_q1[326:320]}};

assign xor_ln53_fu_1054_p2 = (icmp_ln53_fu_1048_p2 ^ 1'd1);

assign zext_ln31_fu_476_p1 = shl_ln_fu_468_p3;

assign zext_ln34_1_fu_580_p1 = add_ln56_fu_574_p2;

assign zext_ln34_2_fu_609_p1 = shl_ln34_4_fu_601_p3;

assign zext_ln34_3_fu_643_p1 = shl_ln34_1_fu_635_p3;

assign zext_ln34_4_fu_588_p1 = reg_436;

assign zext_ln34_fu_585_p1 = tmp_reg_1419;

assign zext_ln35_fu_1343_p1 = shl_ln3_fu_1335_p3;

assign zext_ln36_fu_670_p1 = tap_1_reg_342;

assign zext_ln38_1_fu_708_p1 = tmp_20_fu_698_p4;

assign zext_ln38_2_fu_693_p1 = or_ln_fu_684_p4;

assign zext_ln38_3_fu_869_p1 = shl_ln38_2_fu_862_p3;

assign zext_ln38_4_fu_901_p1 = $unsigned(sext_ln38_1_fu_897_p1);

assign zext_ln38_fu_852_p1 = or_ln_reg_1455;

assign zext_ln44_1_fu_1038_p1 = bit_2_fu_264;

assign zext_ln44_fu_536_p1 = phi_ln44_fu_232;

assign zext_ln47_fu_984_p1 = bit_fu_252;

assign zext_ln50_fu_1003_p1 = bit_4_fu_993_p4;

assign zext_ln55_fu_1076_p1 = result_2_fu_1066_p4;

assign zext_ln56_fu_563_p1 = shl_ln1_fu_556_p3;

assign zext_ln59_fu_1112_p1 = bit_6_fu_1102_p4;

assign zext_ln90_1_fu_1198_p1 = shl_ln90_4_fu_1190_p3;

assign zext_ln90_2_fu_1164_p1 = and_ln_fu_1157_p3;

assign zext_ln90_3_fu_1232_p1 = shl_ln90_1_fu_1224_p3;

assign zext_ln90_4_fu_1177_p1 = reg_436;

assign zext_ln90_fu_1173_p1 = trunc_ln61_fu_1169_p1;

assign zext_ln92_fu_1267_p1 = shl_ln2_fu_1259_p3;

assign zext_ln93_fu_1286_p1 = add_ln93_fu_1276_p2;

assign zmpio_step1_kFirCoefficientsQ15_address0 = zext_ln36_fu_670_p1;

always @ (posedge ap_clk) begin
    add_ln56_reg_1436[0] <= 1'b0;
    or_ln_reg_1455[0] <= 1'b0;
    and_ln_reg_1519[1:0] <= 2'b00;
    bit_fu_252[1] <= 1'b0;
    bit_fu_252[3:3] <= 1'b0;
    bit_fu_252[5:5] <= 1'b0;
    bit_fu_252[7:7] <= 1'b0;
    bit_fu_252[9:9] <= 1'b0;
    bit_fu_252[11:11] <= 1'b0;
    bit_fu_252[13:13] <= 1'b0;
    bit_fu_252[15:15] <= 1'b0;
    bit_fu_252[17:17] <= 1'b0;
    bit_fu_252[19:19] <= 1'b0;
    bit_fu_252[21:21] <= 1'b0;
    bit_fu_252[23:23] <= 1'b0;
    bit_fu_252[25:25] <= 1'b0;
    bit_fu_252[27:27] <= 1'b0;
    bit_fu_252[29:29] <= 1'b0;
    bit_fu_252[31:31] <= 1'b0;
    bit_fu_252[33:33] <= 1'b0;
    bit_fu_252[35:35] <= 1'b0;
    bit_fu_252[37:37] <= 1'b0;
    bit_fu_252[39:39] <= 1'b0;
    bit_fu_252[41:41] <= 1'b0;
    bit_fu_252[43:43] <= 1'b0;
    bit_fu_252[45:45] <= 1'b0;
    bit_fu_252[47:47] <= 1'b0;
    bit_fu_252[49:49] <= 1'b0;
    bit_fu_252[51:51] <= 1'b0;
    bit_fu_252[53:53] <= 1'b0;
    bit_fu_252[55:55] <= 1'b0;
    bit_fu_252[57:57] <= 1'b0;
    bit_fu_252[59:59] <= 1'b0;
    bit_fu_252[61] <= 1'b0;
    bit_2_fu_264[1] <= 1'b0;
    bit_2_fu_264[3:3] <= 1'b0;
    bit_2_fu_264[5:5] <= 1'b0;
    bit_2_fu_264[7:7] <= 1'b0;
    bit_2_fu_264[9:9] <= 1'b0;
    bit_2_fu_264[11:11] <= 1'b0;
    bit_2_fu_264[13:13] <= 1'b0;
    bit_2_fu_264[15:15] <= 1'b0;
    bit_2_fu_264[17:17] <= 1'b0;
    bit_2_fu_264[19:19] <= 1'b0;
    bit_2_fu_264[21:21] <= 1'b0;
    bit_2_fu_264[23:23] <= 1'b0;
    bit_2_fu_264[25:25] <= 1'b0;
    bit_2_fu_264[27:27] <= 1'b0;
    bit_2_fu_264[29:29] <= 1'b0;
    bit_2_fu_264[31:31] <= 1'b0;
    bit_2_fu_264[33:33] <= 1'b0;
    bit_2_fu_264[35:35] <= 1'b0;
    bit_2_fu_264[37:37] <= 1'b0;
    bit_2_fu_264[39:39] <= 1'b0;
    bit_2_fu_264[41:41] <= 1'b0;
    bit_2_fu_264[43:43] <= 1'b0;
    bit_2_fu_264[45:45] <= 1'b0;
    bit_2_fu_264[47:47] <= 1'b0;
    bit_2_fu_264[49:49] <= 1'b0;
    bit_2_fu_264[51:51] <= 1'b0;
    bit_2_fu_264[53:53] <= 1'b0;
    bit_2_fu_264[55:55] <= 1'b0;
    bit_2_fu_264[57:57] <= 1'b0;
    bit_2_fu_264[59:59] <= 1'b0;
    bit_2_fu_264[61] <= 1'b0;
end

endmodule //dsp_core_axis_top_push
