// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dsp_core_axis_top_dsp_core_axis_top,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=14.407000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=33,HLS_SYN_DSP=0,HLS_SYN_FF=4516,HLS_SYN_LUT=20842,HLS_VERSION=2023_2}" *)

module dsp_core_axis_top (
        ap_clk,
        ap_rst_n,
        sample_axis_in_TDATA,
        sample_axis_in_TVALID,
        sample_axis_in_TREADY,
        sample_axis_in_TKEEP,
        sample_axis_in_TSTRB,
        sample_axis_in_TUSER,
        sample_axis_in_TLAST,
        sample_axis_in_TID,
        sample_axis_in_TDEST,
        feature_axis_out_TDATA,
        feature_axis_out_TVALID,
        feature_axis_out_TREADY,
        feature_axis_out_TKEEP,
        feature_axis_out_TSTRB,
        feature_axis_out_TUSER,
        feature_axis_out_TLAST,
        feature_axis_out_TID,
        feature_axis_out_TDEST
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst_n;
input  [159:0] sample_axis_in_TDATA;
input   sample_axis_in_TVALID;
output   sample_axis_in_TREADY;
input  [19:0] sample_axis_in_TKEEP;
input  [19:0] sample_axis_in_TSTRB;
input  [0:0] sample_axis_in_TUSER;
input  [0:0] sample_axis_in_TLAST;
input  [0:0] sample_axis_in_TID;
input  [0:0] sample_axis_in_TDEST;
output  [383:0] feature_axis_out_TDATA;
output   feature_axis_out_TVALID;
input   feature_axis_out_TREADY;
output  [47:0] feature_axis_out_TKEEP;
output  [47:0] feature_axis_out_TSTRB;
output  [0:0] feature_axis_out_TUSER;
output  [0:0] feature_axis_out_TLAST;
output  [0:0] feature_axis_out_TID;
output  [0:0] feature_axis_out_TDEST;

 reg    ap_rst_n_inv;
reg   [0:0] guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core;
reg   [3:0] core_address0;
reg    core_ce0;
reg   [47:0] core_we0;
reg   [383:0] core_d0;
wire   [383:0] core_q0;
reg   [3:0] core_address1;
reg    core_ce1;
reg   [47:0] core_we1;
reg   [383:0] core_d1;
wire   [383:0] core_q1;
reg    sample_axis_in_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state11;
reg    feature_axis_out_TDATA_blk_n;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
reg   [0:0] tmp_13_reg_1198;
wire   [0:0] guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1;
reg   [0:0] guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_reg_1075;
wire    ap_CS_fsm_state1;
wire   [1:0] add_ln19_fu_554_p2;
reg   [1:0] add_ln19_reg_1109;
wire    ap_CS_fsm_state3;
wire   [4:0] add_ln752_fu_571_p2;
wire    ap_CS_fsm_state4;
wire   [9:0] empty_64_fu_713_p2;
reg   [9:0] empty_64_reg_1132;
wire    ap_CS_fsm_state5;
wire   [1:0] add_ln19_1_fu_874_p2;
reg   [1:0] add_ln19_1_reg_1161;
wire    ap_CS_fsm_state8;
wire   [4:0] add_ln752_1_fu_886_p2;
wire    ap_CS_fsm_state9;
wire   [0:0] tmp_nbreadreq_fu_258_p9;
reg   [0:0] tmp_reg_1174;
wire    ap_CS_fsm_state10;
wire   [15:0] sample_accel_x_fu_1007_p1;
reg   [15:0] sample_accel_x_reg_1178;
reg   [15:0] sample_accel_y_reg_1183;
reg   [15:0] sample_accel_z_reg_1188;
reg   [31:0] sample_sample_sequence_reg_1193;
wire   [0:0] tmp_13_fu_1045_p3;
wire    ap_CS_fsm_state14;
wire   [127:0] trunc_ln39_fu_1053_p1;
reg   [127:0] trunc_ln39_reg_1202;
wire    grp_push_fu_388_ap_start;
wire    grp_push_fu_388_ap_done;
wire    grp_push_fu_388_ap_idle;
wire    grp_push_fu_388_ap_ready;
wire   [3:0] grp_push_fu_388_core_address0;
wire    grp_push_fu_388_core_ce0;
wire   [47:0] grp_push_fu_388_core_we0;
wire   [383:0] grp_push_fu_388_core_d0;
wire   [3:0] grp_push_fu_388_core_address1;
wire    grp_push_fu_388_core_ce1;
wire   [47:0] grp_push_fu_388_core_we1;
wire   [383:0] grp_push_fu_388_core_d1;
reg   [4:0] idx171_reg_366;
wire   [0:0] icmp_ln19_fu_548_p2;
wire   [0:0] icmp_ln753_fu_565_p2;
reg   [4:0] idx169_reg_377;
wire   [0:0] icmp_ln19_1_fu_868_p2;
wire   [0:0] icmp_ln753_1_fu_880_p2;
reg    grp_push_fu_388_ap_start_reg;
wire    ap_CS_fsm_state12;
wire   [63:0] p_cast24_fu_458_p1;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond_i_i6_fu_430_p2;
wire   [63:0] zext_ln754_fu_614_p1;
wire   [63:0] p_cast26_fu_748_p1;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln754_4_fu_929_p1;
reg   [8:0] phi_mul_fu_234;
wire   [8:0] next_mul_fu_442_p2;
reg   [3:0] empty_fu_238;
wire   [3:0] empty_57_fu_436_p2;
reg   [1:0] idx_fu_242;
reg   [6:0] empty_61_fu_246;
wire   [6:0] empty_62_fu_691_p2;
wire   [0:0] exitcond_i10_i4_fu_685_p2;
reg   [2:0] empty_68_fu_250;
wire   [2:0] empty_69_fu_822_p2;
wire    ap_CS_fsm_state7;
wire   [0:0] exitcond_i3_fu_816_p2;
reg   [1:0] idx166_fu_254;
wire   [47:0] empty_60_fu_523_p2;
wire   [47:0] shl_ln754_fu_671_p2;
wire   [47:0] empty_67_fu_806_p2;
wire   [47:0] p_cast29_fu_850_p1;
wire   [47:0] shl_ln754_1_fu_986_p2;
wire    ap_CS_fsm_state13;
wire    regslice_both_feature_axis_out_V_data_V_U_apdone_blk;
reg    ap_block_state16;
reg    ap_block_state16_io;
wire   [1:0] tmp_1_fu_448_p4;
wire   [11:0] phi_mul_cast_fu_426_p1;
wire   [0:0] tmp_2_fu_463_p3;
wire   [4:0] tmp_5_fu_479_p3;
wire   [6:0] tmp_6_fu_491_p3;
wire   [6:0] p_cast3_fu_487_p1;
wire   [6:0] tmp_3_fu_471_p3;
wire   [6:0] empty_58_fu_503_p2;
wire  signed [7:0] p_cast4_fu_509_p1;
wire   [7:0] p_cast5_fu_499_p1;
wire   [7:0] empty_59_fu_513_p2;
wire  signed [47:0] p_cast25_fu_519_p1;
wire   [3:0] trunc_ln752_fu_577_p1;
wire   [6:0] p_first_assign_fu_581_p4;
wire   [6:0] mul_ln754_fu_594_p0;
wire   [8:0] mul_ln754_fu_594_p1;
wire   [14:0] mul_ln754_fu_594_p2;
wire   [1:0] tmp_10_fu_604_p4;
wire   [20:0] zext_ln754_5_fu_600_p1;
wire   [0:0] tmp_11_fu_619_p3;
wire   [4:0] shl_ln754_3_fu_635_p3;
wire   [6:0] zext_ln754_2_fu_643_p1;
wire   [6:0] shl_ln754_2_fu_627_p3;
wire   [6:0] sub_ln754_fu_651_p2;
wire  signed [7:0] sext_ln754_fu_657_p1;
wire   [7:0] zext_ln754_3_fu_647_p1;
wire   [7:0] add_ln754_fu_661_p2;
wire  signed [47:0] sext_ln754_1_fu_667_p1;
wire   [5:0] empty_63_fu_697_p1;
wire   [8:0] tmp_8_fu_701_p3;
wire   [9:0] p_cast17_fu_709_p1;
wire   [9:0] mul4_fu_732_p0;
wire   [11:0] mul4_fu_732_p1;
wire   [20:0] mul4_fu_732_p2;
wire   [4:0] tmp_4_fu_738_p4;
wire   [3:0] tmp_s_fu_753_p4;
wire   [9:0] tmp_7_fu_763_p3;
wire   [7:0] tmp_9_fu_775_p3;
wire   [10:0] p_cast19_fu_783_p1;
wire   [10:0] p_cast20_fu_771_p1;
wire   [10:0] empty_65_fu_790_p2;
wire   [10:0] p_cast21_fu_787_p1;
wire   [10:0] empty_66_fu_796_p2;
wire  signed [47:0] p_cast27_fu_802_p1;
wire   [1:0] empty_70_fu_828_p1;
wire   [3:0] tmp_12_fu_832_p3;
wire   [15:0] p_cast23_fu_840_p1;
wire   [15:0] empty_71_fu_844_p2;
wire   [3:0] trunc_ln752_1_fu_892_p1;
wire   [6:0] p_first_assign_1_fu_896_p4;
wire   [6:0] mul_ln754_1_fu_909_p0;
wire   [8:0] mul_ln754_1_fu_909_p1;
wire   [14:0] mul_ln754_1_fu_909_p2;
wire   [1:0] tmp_14_fu_919_p4;
wire   [20:0] zext_ln754_9_fu_915_p1;
wire   [0:0] tmp_15_fu_934_p3;
wire   [4:0] shl_ln754_5_fu_950_p3;
wire   [6:0] zext_ln754_6_fu_958_p1;
wire   [6:0] shl_ln754_4_fu_942_p3;
wire   [6:0] sub_ln754_1_fu_966_p2;
wire  signed [7:0] sext_ln754_2_fu_972_p1;
wire   [7:0] zext_ln754_7_fu_962_p1;
wire   [7:0] add_ln754_1_fu_976_p2;
wire  signed [47:0] sext_ln754_3_fu_982_p1;
wire   [255:0] tmp_16_fu_1057_p4;
reg   [15:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_block_state12_on_subcall_done;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    regslice_both_sample_axis_in_V_data_V_U_apdone_blk;
wire   [159:0] sample_axis_in_TDATA_int_regslice;
wire    sample_axis_in_TVALID_int_regslice;
reg    sample_axis_in_TREADY_int_regslice;
wire    regslice_both_sample_axis_in_V_data_V_U_ack_in;
wire    regslice_both_sample_axis_in_V_keep_V_U_apdone_blk;
wire   [19:0] sample_axis_in_TKEEP_int_regslice;
wire    regslice_both_sample_axis_in_V_keep_V_U_vld_out;
wire    regslice_both_sample_axis_in_V_keep_V_U_ack_in;
wire    regslice_both_sample_axis_in_V_strb_V_U_apdone_blk;
wire   [19:0] sample_axis_in_TSTRB_int_regslice;
wire    regslice_both_sample_axis_in_V_strb_V_U_vld_out;
wire    regslice_both_sample_axis_in_V_strb_V_U_ack_in;
wire    regslice_both_sample_axis_in_V_user_V_U_apdone_blk;
wire   [0:0] sample_axis_in_TUSER_int_regslice;
wire    regslice_both_sample_axis_in_V_user_V_U_vld_out;
wire    regslice_both_sample_axis_in_V_user_V_U_ack_in;
wire    regslice_both_sample_axis_in_V_last_V_U_apdone_blk;
wire   [0:0] sample_axis_in_TLAST_int_regslice;
wire    regslice_both_sample_axis_in_V_last_V_U_vld_out;
wire    regslice_both_sample_axis_in_V_last_V_U_ack_in;
wire    regslice_both_sample_axis_in_V_id_V_U_apdone_blk;
wire   [0:0] sample_axis_in_TID_int_regslice;
wire    regslice_both_sample_axis_in_V_id_V_U_vld_out;
wire    regslice_both_sample_axis_in_V_id_V_U_ack_in;
wire    regslice_both_sample_axis_in_V_dest_V_U_apdone_blk;
wire   [0:0] sample_axis_in_TDEST_int_regslice;
wire    regslice_both_sample_axis_in_V_dest_V_U_vld_out;
wire    regslice_both_sample_axis_in_V_dest_V_U_ack_in;
wire   [383:0] feature_axis_out_TDATA_int_regslice;
reg    feature_axis_out_TVALID_int_regslice;
wire    feature_axis_out_TREADY_int_regslice;
wire    regslice_both_feature_axis_out_V_data_V_U_vld_out;
wire    regslice_both_feature_axis_out_V_keep_V_U_apdone_blk;
wire    regslice_both_feature_axis_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_feature_axis_out_V_keep_V_U_vld_out;
wire    regslice_both_feature_axis_out_V_strb_V_U_apdone_blk;
wire    regslice_both_feature_axis_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_feature_axis_out_V_strb_V_U_vld_out;
wire    regslice_both_feature_axis_out_V_user_V_U_apdone_blk;
wire    regslice_both_feature_axis_out_V_user_V_U_ack_in_dummy;
wire    regslice_both_feature_axis_out_V_user_V_U_vld_out;
wire    regslice_both_feature_axis_out_V_last_V_U_apdone_blk;
wire    regslice_both_feature_axis_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_feature_axis_out_V_last_V_U_vld_out;
wire    regslice_both_feature_axis_out_V_id_V_U_apdone_blk;
wire    regslice_both_feature_axis_out_V_id_V_U_ack_in_dummy;
wire    regslice_both_feature_axis_out_V_id_V_U_vld_out;
wire    regslice_both_feature_axis_out_V_dest_V_U_apdone_blk;
wire    regslice_both_feature_axis_out_V_dest_V_U_ack_in_dummy;
wire    regslice_both_feature_axis_out_V_dest_V_U_vld_out;
wire   [20:0] mul4_fu_732_p00;
wire   [14:0] mul_ln754_1_fu_909_p00;
wire   [14:0] mul_ln754_fu_594_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core = 1'd0;
#0 ap_CS_fsm = 16'd1;
#0 grp_push_fu_388_ap_start_reg = 1'b0;
#0 phi_mul_fu_234 = 9'd0;
#0 empty_fu_238 = 4'd0;
#0 idx_fu_242 = 2'd0;
#0 empty_61_fu_246 = 7'd0;
#0 empty_68_fu_250 = 3'd0;
#0 idx166_fu_254 = 2'd0;
end

dsp_core_axis_top_core_RAM_AUTO_1R1W #(
    .DataWidth( 384 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
core_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(core_address0),
    .ce0(core_ce0),
    .we0(core_we0),
    .d0(core_d0),
    .q0(core_q0),
    .address1(core_address1),
    .ce1(core_ce1),
    .we1(core_we1),
    .d1(core_d1),
    .q1(core_q1)
);

dsp_core_axis_top_push grp_push_fu_388(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_push_fu_388_ap_start),
    .ap_done(grp_push_fu_388_ap_done),
    .ap_idle(grp_push_fu_388_ap_idle),
    .ap_ready(grp_push_fu_388_ap_ready),
    .sample_0_val(sample_accel_x_reg_1178),
    .sample_1_val(sample_accel_y_reg_1183),
    .sample_2_val(sample_accel_z_reg_1188),
    .sample_8_val(sample_sample_sequence_reg_1193),
    .core_address0(grp_push_fu_388_core_address0),
    .core_ce0(grp_push_fu_388_core_ce0),
    .core_we0(grp_push_fu_388_core_we0),
    .core_d0(grp_push_fu_388_core_d0),
    .core_q0(core_q0),
    .core_address1(grp_push_fu_388_core_address1),
    .core_ce1(grp_push_fu_388_core_ce1),
    .core_we1(grp_push_fu_388_core_we1),
    .core_d1(grp_push_fu_388_core_d1),
    .core_q1(core_q1)
);

dsp_core_axis_top_mul_7ns_9ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 15 ))
mul_7ns_9ns_15_1_1_U32(
    .din0(mul_ln754_fu_594_p0),
    .din1(mul_ln754_fu_594_p1),
    .dout(mul_ln754_fu_594_p2)
);

dsp_core_axis_top_mul_10ns_12ns_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
mul_10ns_12ns_21_1_1_U33(
    .din0(mul4_fu_732_p0),
    .din1(mul4_fu_732_p1),
    .dout(mul4_fu_732_p2)
);

dsp_core_axis_top_mul_7ns_9ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 15 ))
mul_7ns_9ns_15_1_1_U34(
    .din0(mul_ln754_1_fu_909_p0),
    .din1(mul_ln754_1_fu_909_p1),
    .dout(mul_ln754_1_fu_909_p2)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 160 ))
regslice_both_sample_axis_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(sample_axis_in_TDATA),
    .vld_in(sample_axis_in_TVALID),
    .ack_in(regslice_both_sample_axis_in_V_data_V_U_ack_in),
    .data_out(sample_axis_in_TDATA_int_regslice),
    .vld_out(sample_axis_in_TVALID_int_regslice),
    .ack_out(sample_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_sample_axis_in_V_data_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 20 ))
regslice_both_sample_axis_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(sample_axis_in_TKEEP),
    .vld_in(sample_axis_in_TVALID),
    .ack_in(regslice_both_sample_axis_in_V_keep_V_U_ack_in),
    .data_out(sample_axis_in_TKEEP_int_regslice),
    .vld_out(regslice_both_sample_axis_in_V_keep_V_U_vld_out),
    .ack_out(sample_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_sample_axis_in_V_keep_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 20 ))
regslice_both_sample_axis_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(sample_axis_in_TSTRB),
    .vld_in(sample_axis_in_TVALID),
    .ack_in(regslice_both_sample_axis_in_V_strb_V_U_ack_in),
    .data_out(sample_axis_in_TSTRB_int_regslice),
    .vld_out(regslice_both_sample_axis_in_V_strb_V_U_vld_out),
    .ack_out(sample_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_sample_axis_in_V_strb_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_sample_axis_in_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(sample_axis_in_TUSER),
    .vld_in(sample_axis_in_TVALID),
    .ack_in(regslice_both_sample_axis_in_V_user_V_U_ack_in),
    .data_out(sample_axis_in_TUSER_int_regslice),
    .vld_out(regslice_both_sample_axis_in_V_user_V_U_vld_out),
    .ack_out(sample_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_sample_axis_in_V_user_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_sample_axis_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(sample_axis_in_TLAST),
    .vld_in(sample_axis_in_TVALID),
    .ack_in(regslice_both_sample_axis_in_V_last_V_U_ack_in),
    .data_out(sample_axis_in_TLAST_int_regslice),
    .vld_out(regslice_both_sample_axis_in_V_last_V_U_vld_out),
    .ack_out(sample_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_sample_axis_in_V_last_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_sample_axis_in_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(sample_axis_in_TID),
    .vld_in(sample_axis_in_TVALID),
    .ack_in(regslice_both_sample_axis_in_V_id_V_U_ack_in),
    .data_out(sample_axis_in_TID_int_regslice),
    .vld_out(regslice_both_sample_axis_in_V_id_V_U_vld_out),
    .ack_out(sample_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_sample_axis_in_V_id_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_sample_axis_in_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(sample_axis_in_TDEST),
    .vld_in(sample_axis_in_TVALID),
    .ack_in(regslice_both_sample_axis_in_V_dest_V_U_ack_in),
    .data_out(sample_axis_in_TDEST_int_regslice),
    .vld_out(regslice_both_sample_axis_in_V_dest_V_U_vld_out),
    .ack_out(sample_axis_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_sample_axis_in_V_dest_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 384 ))
regslice_both_feature_axis_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(feature_axis_out_TDATA_int_regslice),
    .vld_in(feature_axis_out_TVALID_int_regslice),
    .ack_in(feature_axis_out_TREADY_int_regslice),
    .data_out(feature_axis_out_TDATA),
    .vld_out(regslice_both_feature_axis_out_V_data_V_U_vld_out),
    .ack_out(feature_axis_out_TREADY),
    .apdone_blk(regslice_both_feature_axis_out_V_data_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 48 ))
regslice_both_feature_axis_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(48'd281474976710655),
    .vld_in(feature_axis_out_TVALID_int_regslice),
    .ack_in(regslice_both_feature_axis_out_V_keep_V_U_ack_in_dummy),
    .data_out(feature_axis_out_TKEEP),
    .vld_out(regslice_both_feature_axis_out_V_keep_V_U_vld_out),
    .ack_out(feature_axis_out_TREADY),
    .apdone_blk(regslice_both_feature_axis_out_V_keep_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 48 ))
regslice_both_feature_axis_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(48'd281474976710655),
    .vld_in(feature_axis_out_TVALID_int_regslice),
    .ack_in(regslice_both_feature_axis_out_V_strb_V_U_ack_in_dummy),
    .data_out(feature_axis_out_TSTRB),
    .vld_out(regslice_both_feature_axis_out_V_strb_V_U_vld_out),
    .ack_out(feature_axis_out_TREADY),
    .apdone_blk(regslice_both_feature_axis_out_V_strb_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_feature_axis_out_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd1),
    .vld_in(feature_axis_out_TVALID_int_regslice),
    .ack_in(regslice_both_feature_axis_out_V_user_V_U_ack_in_dummy),
    .data_out(feature_axis_out_TUSER),
    .vld_out(regslice_both_feature_axis_out_V_user_V_U_vld_out),
    .ack_out(feature_axis_out_TREADY),
    .apdone_blk(regslice_both_feature_axis_out_V_user_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_feature_axis_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd1),
    .vld_in(feature_axis_out_TVALID_int_regslice),
    .ack_in(regslice_both_feature_axis_out_V_last_V_U_ack_in_dummy),
    .data_out(feature_axis_out_TLAST),
    .vld_out(regslice_both_feature_axis_out_V_last_V_U_vld_out),
    .ack_out(feature_axis_out_TREADY),
    .apdone_blk(regslice_both_feature_axis_out_V_last_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_feature_axis_out_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(feature_axis_out_TVALID_int_regslice),
    .ack_in(regslice_both_feature_axis_out_V_id_V_U_ack_in_dummy),
    .data_out(feature_axis_out_TID),
    .vld_out(regslice_both_feature_axis_out_V_id_V_U_vld_out),
    .ack_out(feature_axis_out_TREADY),
    .apdone_blk(regslice_both_feature_axis_out_V_id_V_U_apdone_blk)
);

dsp_core_axis_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_feature_axis_out_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(feature_axis_out_TVALID_int_regslice),
    .ack_in(regslice_both_feature_axis_out_V_dest_V_U_ack_in_dummy),
    .data_out(feature_axis_out_TDEST),
    .vld_out(regslice_both_feature_axis_out_V_dest_V_U_vld_out),
    .ack_out(feature_axis_out_TREADY),
    .apdone_blk(regslice_both_feature_axis_out_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_push_fu_388_ap_start_reg <= 1'b0;
    end else begin
        if (((sample_axis_in_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
            grp_push_fu_388_ap_start_reg <= 1'b1;
        end else if ((grp_push_fu_388_ap_ready == 1'b1)) begin
            grp_push_fu_388_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln19_fu_548_p2 == 1'd1))) begin
        empty_61_fu_246 <= 7'd0;
    end else if (((exitcond_i10_i4_fu_685_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        empty_61_fu_246 <= empty_62_fu_691_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i10_i4_fu_685_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        empty_68_fu_250 <= 3'd0;
    end else if (((exitcond_i3_fu_816_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        empty_68_fu_250 <= empty_69_fu_822_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_fu_238 <= 4'd0;
    end else if (((exitcond_i_i6_fu_430_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_fu_238 <= empty_57_fu_436_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i3_fu_816_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        idx166_fu_254 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln753_1_fu_880_p2 == 1'd1))) begin
        idx166_fu_254 <= add_ln19_1_reg_1161;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln753_1_fu_880_p2 == 1'd0))) begin
        idx169_reg_377 <= add_ln752_1_fu_886_p2;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln19_1_fu_868_p2 == 1'd0))) begin
        idx169_reg_377 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln753_fu_565_p2 == 1'd0))) begin
        idx171_reg_366 <= add_ln752_fu_571_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln19_fu_548_p2 == 1'd0))) begin
        idx171_reg_366 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_i6_fu_430_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        idx_fu_242 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln753_fu_565_p2 == 1'd1))) begin
        idx_fu_242 <= add_ln19_reg_1109;
    end
end

always @ (posedge ap_clk) begin
    if (((guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_fu_234 <= 9'd0;
    end else if (((exitcond_i_i6_fu_430_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_mul_fu_234 <= next_mul_fu_442_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln19_1_reg_1161 <= add_ln19_1_fu_874_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln19_reg_1109 <= add_ln19_fu_554_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        empty_64_reg_1132[9 : 3] <= empty_64_fu_713_p2[9 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_reg_1075 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_reg_1075 <= guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        sample_accel_x_reg_1178 <= sample_accel_x_fu_1007_p1;
        sample_accel_y_reg_1183 <= {{sample_axis_in_TDATA_int_regslice[31:16]}};
        sample_accel_z_reg_1188 <= {{sample_axis_in_TDATA_int_regslice[47:32]}};
        sample_sample_sequence_reg_1193 <= {{sample_axis_in_TDATA_int_regslice[159:128]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_13_reg_1198 <= core_q0[32'd128];
        trunc_ln39_reg_1202 <= trunc_ln39_fu_1053_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_reg_1174 <= tmp_nbreadreq_fu_258_p9;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((sample_axis_in_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state12_on_subcall_done)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((feature_axis_out_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16))) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13))) begin
        core_address0 = 4'd14;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        core_address0 = zext_ln754_4_fu_929_p1;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5))) begin
        core_address0 = 4'd13;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        core_address0 = zext_ln754_fu_614_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        core_address0 = 4'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        core_address0 = p_cast24_fu_458_p1;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_reg_1174 == 1'd1))) begin
        core_address0 = grp_push_fu_388_core_address0;
    end else begin
        core_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        core_address1 = 4'd13;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        core_address1 = 4'd2;
    end else if (((1'b1 == ap_CS_fsm_state10) | ((exitcond_i3_fu_816_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((exitcond_i3_fu_816_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        core_address1 = 4'd14;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        core_address1 = p_cast26_fu_748_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        core_address1 = 4'd12;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_reg_1174 == 1'd1))) begin
        core_address1 = grp_push_fu_388_core_address1;
    end else begin
        core_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (~((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16)) & (1'b1 == ap_CS_fsm_state16)))) begin
        core_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_reg_1174 == 1'd1))) begin
        core_ce0 = grp_push_fu_388_core_ce0;
    end else begin
        core_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | ((exitcond_i3_fu_816_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((exitcond_i3_fu_816_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        core_ce1 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_reg_1174 == 1'd1))) begin
        core_ce1 = grp_push_fu_388_core_ce1;
    end else begin
        core_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        core_d0 = 384'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_reg_1174 == 1'd1))) begin
        core_d0 = grp_push_fu_388_core_d0;
    end else begin
        core_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | ((exitcond_i3_fu_816_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((exitcond_i3_fu_816_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7)))) begin
        core_d1 = 384'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_reg_1174 == 1'd1))) begin
        core_d1 = grp_push_fu_388_core_d1;
    end else begin
        core_d1 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16)) & (tmp_13_reg_1198 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        core_we0 = 48'd65536;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln753_1_fu_880_p2 == 1'd0))) begin
        core_we0 = shl_ln754_1_fu_986_p2;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln19_1_fu_868_p2 == 1'd1))) begin
        core_we0 = 48'd281474976645120;
    end else if (((exitcond_i10_i4_fu_685_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        core_we0 = 48'd281474976649215;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln753_fu_565_p2 == 1'd0))) begin
        core_we0 = shl_ln754_fu_671_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln19_fu_548_p2 == 1'd1))) begin
        core_we0 = 48'd255;
    end else if (((exitcond_i_i6_fu_430_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        core_we0 = empty_60_fu_523_p2;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_reg_1174 == 1'd1))) begin
        core_we0 = grp_push_fu_388_core_we0;
    end else begin
        core_we0 = 48'd0;
    end
end

always @ (*) begin
    if (((guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_reg_1075 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        core_we1 = 48'd1099494981631;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln19_1_fu_868_p2 == 1'd1))) begin
        core_we1 = 48'd255;
    end else if (((exitcond_i3_fu_816_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        core_we1 = 48'd1099494916096;
    end else if (((exitcond_i3_fu_816_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        core_we1 = p_cast29_fu_850_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        core_we1 = empty_67_fu_806_p2;
    end else if (((exitcond_i10_i4_fu_685_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        core_we1 = 48'd280375465082880;
    end else if (((1'b1 == ap_CS_fsm_state12) & (tmp_reg_1174 == 1'd1))) begin
        core_we1 = grp_push_fu_388_core_we1;
    end else begin
        core_we1 = 48'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | ((tmp_13_reg_1198 == 1'd1) & (1'b1 == ap_CS_fsm_state16)))) begin
        feature_axis_out_TDATA_blk_n = feature_axis_out_TREADY_int_regslice;
    end else begin
        feature_axis_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((feature_axis_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        feature_axis_out_TVALID_int_regslice = 1'b1;
    end else begin
        feature_axis_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        sample_axis_in_TDATA_blk_n = sample_axis_in_TVALID_int_regslice;
    end else begin
        sample_axis_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((sample_axis_in_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        sample_axis_in_TREADY_int_regslice = 1'b1;
    end else begin
        sample_axis_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_i_i6_fu_430_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln19_fu_548_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln753_fu_565_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond_i10_i4_fu_685_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state7 : begin
            if (((exitcond_i3_fu_816_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln19_1_fu_868_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln753_1_fu_880_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (tmp_nbreadreq_fu_258_p9 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((sample_axis_in_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (tmp_13_fu_1045_p3 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((feature_axis_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if ((~((1'b1 == ap_block_state16_io) | (1'b1 == ap_block_state16)) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln19_1_fu_874_p2 = (idx166_fu_254 + 2'd1);

assign add_ln19_fu_554_p2 = (idx_fu_242 + 2'd1);

assign add_ln752_1_fu_886_p2 = (idx169_reg_377 + 5'd1);

assign add_ln752_fu_571_p2 = (idx171_reg_366 + 5'd1);

assign add_ln754_1_fu_976_p2 = ($signed(sext_ln754_2_fu_972_p1) + $signed(zext_ln754_7_fu_962_p1));

assign add_ln754_fu_661_p2 = ($signed(sext_ln754_fu_657_p1) + $signed(zext_ln754_3_fu_647_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state12_on_subcall_done = ((grp_push_fu_388_ap_done == 1'b0) & (tmp_reg_1174 == 1'd1));
end

always @ (*) begin
    ap_block_state16 = ((regslice_both_feature_axis_out_V_data_V_U_apdone_blk == 1'b1) | ((feature_axis_out_TREADY_int_regslice == 1'b0) & (tmp_13_reg_1198 == 1'd1)));
end

always @ (*) begin
    ap_block_state16_io = ((feature_axis_out_TREADY_int_regslice == 1'b0) & (tmp_13_reg_1198 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_57_fu_436_p2 = (empty_fu_238 + 4'd1);

assign empty_58_fu_503_p2 = (p_cast3_fu_487_p1 - tmp_3_fu_471_p3);

assign empty_59_fu_513_p2 = ($signed(p_cast4_fu_509_p1) + $signed(p_cast5_fu_499_p1));

assign empty_60_fu_523_p2 = 48'd255 << p_cast25_fu_519_p1;

assign empty_62_fu_691_p2 = (empty_61_fu_246 + 7'd1);

assign empty_63_fu_697_p1 = empty_61_fu_246[5:0];

assign empty_64_fu_713_p2 = (p_cast17_fu_709_p1 + 10'd104);

assign empty_65_fu_790_p2 = (p_cast19_fu_783_p1 - p_cast20_fu_771_p1);

assign empty_66_fu_796_p2 = (empty_65_fu_790_p2 + p_cast21_fu_787_p1);

assign empty_67_fu_806_p2 = 48'd255 << p_cast27_fu_802_p1;

assign empty_69_fu_822_p2 = (empty_68_fu_250 + 3'd1);

assign empty_70_fu_828_p1 = empty_68_fu_250[1:0];

assign empty_71_fu_844_p2 = 16'd15 << p_cast23_fu_840_p1;

assign exitcond_i10_i4_fu_685_p2 = ((empty_61_fu_246 == 7'd64) ? 1'b1 : 1'b0);

assign exitcond_i3_fu_816_p2 = ((empty_68_fu_250 == 3'd4) ? 1'b1 : 1'b0);

assign exitcond_i_i6_fu_430_p2 = ((empty_fu_238 == 4'd12) ? 1'b1 : 1'b0);

assign feature_axis_out_TDATA_int_regslice = {{trunc_ln39_reg_1202}, {tmp_16_fu_1057_p4}};

assign feature_axis_out_TVALID = regslice_both_feature_axis_out_V_data_V_U_vld_out;

assign grp_push_fu_388_ap_start = grp_push_fu_388_ap_start_reg;

assign guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core_load_load_fu_406_p1 = guard_variable_for_dsp_core_axis_top_stream_stream_axis_0_core;

assign icmp_ln19_1_fu_868_p2 = ((idx166_fu_254 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_548_p2 = ((idx_fu_242 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln753_1_fu_880_p2 = ((idx169_reg_377 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln753_fu_565_p2 = ((idx171_reg_366 == 5'd16) ? 1'b1 : 1'b0);

assign mul4_fu_732_p0 = mul4_fu_732_p00;

assign mul4_fu_732_p00 = empty_64_reg_1132;

assign mul4_fu_732_p1 = 21'd1366;

assign mul_ln754_1_fu_909_p0 = mul_ln754_1_fu_909_p00;

assign mul_ln754_1_fu_909_p00 = p_first_assign_1_fu_896_p4;

assign mul_ln754_1_fu_909_p1 = 15'd171;

assign mul_ln754_fu_594_p0 = mul_ln754_fu_594_p00;

assign mul_ln754_fu_594_p00 = p_first_assign_fu_581_p4;

assign mul_ln754_fu_594_p1 = 15'd171;

assign next_mul_fu_442_p2 = (phi_mul_fu_234 + 9'd22);

assign p_cast17_fu_709_p1 = tmp_8_fu_701_p3;

assign p_cast19_fu_783_p1 = tmp_9_fu_775_p3;

assign p_cast20_fu_771_p1 = tmp_7_fu_763_p3;

assign p_cast21_fu_787_p1 = empty_64_reg_1132;

assign p_cast23_fu_840_p1 = tmp_12_fu_832_p3;

assign p_cast24_fu_458_p1 = tmp_1_fu_448_p4;

assign p_cast25_fu_519_p1 = $signed(empty_59_fu_513_p2);

assign p_cast26_fu_748_p1 = tmp_4_fu_738_p4;

assign p_cast27_fu_802_p1 = $signed(empty_66_fu_796_p2);

assign p_cast29_fu_850_p1 = empty_71_fu_844_p2;

assign p_cast3_fu_487_p1 = tmp_5_fu_479_p3;

assign p_cast4_fu_509_p1 = $signed(empty_58_fu_503_p2);

assign p_cast5_fu_499_p1 = tmp_6_fu_491_p3;

assign p_first_assign_1_fu_896_p4 = {{{idx166_fu_254}, {trunc_ln752_1_fu_892_p1}}, {1'd0}};

assign p_first_assign_fu_581_p4 = {{{idx_fu_242}, {trunc_ln752_fu_577_p1}}, {1'd0}};

assign phi_mul_cast_fu_426_p1 = phi_mul_fu_234;

assign sample_accel_x_fu_1007_p1 = sample_axis_in_TDATA_int_regslice[15:0];

assign sample_axis_in_TREADY = regslice_both_sample_axis_in_V_data_V_U_ack_in;

assign sext_ln754_1_fu_667_p1 = $signed(add_ln754_fu_661_p2);

assign sext_ln754_2_fu_972_p1 = $signed(sub_ln754_1_fu_966_p2);

assign sext_ln754_3_fu_982_p1 = $signed(add_ln754_1_fu_976_p2);

assign sext_ln754_fu_657_p1 = $signed(sub_ln754_fu_651_p2);

assign shl_ln754_1_fu_986_p2 = 48'd3 << sext_ln754_3_fu_982_p1;

assign shl_ln754_2_fu_627_p3 = {{tmp_11_fu_619_p3}, {6'd0}};

assign shl_ln754_3_fu_635_p3 = {{tmp_11_fu_619_p3}, {4'd0}};

assign shl_ln754_4_fu_942_p3 = {{tmp_15_fu_934_p3}, {6'd0}};

assign shl_ln754_5_fu_950_p3 = {{tmp_15_fu_934_p3}, {4'd0}};

assign shl_ln754_fu_671_p2 = 48'd3 << sext_ln754_1_fu_667_p1;

assign sub_ln754_1_fu_966_p2 = (zext_ln754_6_fu_958_p1 - shl_ln754_4_fu_942_p3);

assign sub_ln754_fu_651_p2 = (zext_ln754_2_fu_643_p1 - shl_ln754_2_fu_627_p3);

assign tmp_10_fu_604_p4 = {{mul_ln754_fu_594_p2[14:13]}};

assign tmp_11_fu_619_p3 = zext_ln754_5_fu_600_p1[32'd13];

assign tmp_12_fu_832_p3 = {{empty_70_fu_828_p1}, {2'd0}};

assign tmp_13_fu_1045_p3 = core_q0[32'd128];

assign tmp_14_fu_919_p4 = {{mul_ln754_1_fu_909_p2[14:13]}};

assign tmp_15_fu_934_p3 = zext_ln754_9_fu_915_p1[32'd13];

assign tmp_16_fu_1057_p4 = {{core_q1[383:128]}};

assign tmp_1_fu_448_p4 = {{phi_mul_fu_234[8:7]}};

assign tmp_2_fu_463_p3 = phi_mul_cast_fu_426_p1[32'd7];

assign tmp_3_fu_471_p3 = {{tmp_2_fu_463_p3}, {6'd0}};

assign tmp_4_fu_738_p4 = {{mul4_fu_732_p2[20:16]}};

assign tmp_5_fu_479_p3 = {{tmp_2_fu_463_p3}, {4'd0}};

assign tmp_6_fu_491_p3 = {{empty_fu_238}, {3'd0}};

assign tmp_7_fu_763_p3 = {{tmp_s_fu_753_p4}, {6'd0}};

assign tmp_8_fu_701_p3 = {{empty_63_fu_697_p1}, {3'd0}};

assign tmp_9_fu_775_p3 = {{tmp_s_fu_753_p4}, {4'd0}};

assign tmp_nbreadreq_fu_258_p9 = sample_axis_in_TVALID_int_regslice;

assign tmp_s_fu_753_p4 = {{mul4_fu_732_p2[19:16]}};

assign trunc_ln39_fu_1053_p1 = core_q0[127:0];

assign trunc_ln752_1_fu_892_p1 = idx169_reg_377[3:0];

assign trunc_ln752_fu_577_p1 = idx171_reg_366[3:0];

assign zext_ln754_2_fu_643_p1 = shl_ln754_3_fu_635_p3;

assign zext_ln754_3_fu_647_p1 = p_first_assign_fu_581_p4;

assign zext_ln754_4_fu_929_p1 = tmp_14_fu_919_p4;

assign zext_ln754_5_fu_600_p1 = mul_ln754_fu_594_p2;

assign zext_ln754_6_fu_958_p1 = shl_ln754_5_fu_950_p3;

assign zext_ln754_7_fu_962_p1 = p_first_assign_1_fu_896_p4;

assign zext_ln754_9_fu_915_p1 = mul_ln754_1_fu_909_p2;

assign zext_ln754_fu_614_p1 = tmp_10_fu_604_p4;

always @ (posedge ap_clk) begin
    empty_64_reg_1132[2:0] <= 3'b000;
end


reg find_kernel_block = 0;
// synthesis translate_off
`include "dsp_core_axis_top_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //dsp_core_axis_top

