// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dsp_core_axis_top_fft128_real (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_real_address0,
        output_real_ce0,
        output_real_we0,
        output_real_d0,
        output_real_q0,
        output_imag_address0,
        output_imag_ce0,
        output_imag_we0,
        output_imag_d0,
        output_imag_q0
);

parameter    ap_ST_fsm_state1 = 25'd1;
parameter    ap_ST_fsm_state2 = 25'd2;
parameter    ap_ST_fsm_state3 = 25'd4;
parameter    ap_ST_fsm_state4 = 25'd8;
parameter    ap_ST_fsm_state5 = 25'd16;
parameter    ap_ST_fsm_state6 = 25'd32;
parameter    ap_ST_fsm_state7 = 25'd64;
parameter    ap_ST_fsm_state8 = 25'd128;
parameter    ap_ST_fsm_state9 = 25'd256;
parameter    ap_ST_fsm_state10 = 25'd512;
parameter    ap_ST_fsm_state11 = 25'd1024;
parameter    ap_ST_fsm_state12 = 25'd2048;
parameter    ap_ST_fsm_state13 = 25'd4096;
parameter    ap_ST_fsm_state14 = 25'd8192;
parameter    ap_ST_fsm_state15 = 25'd16384;
parameter    ap_ST_fsm_state16 = 25'd32768;
parameter    ap_ST_fsm_state17 = 25'd65536;
parameter    ap_ST_fsm_state18 = 25'd131072;
parameter    ap_ST_fsm_state19 = 25'd262144;
parameter    ap_ST_fsm_state20 = 25'd524288;
parameter    ap_ST_fsm_state21 = 25'd1048576;
parameter    ap_ST_fsm_state22 = 25'd2097152;
parameter    ap_ST_fsm_state23 = 25'd4194304;
parameter    ap_ST_fsm_state24 = 25'd8388608;
parameter    ap_ST_fsm_state25 = 25'd16777216;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [6:0] output_real_address0;
output   output_real_ce0;
output   output_real_we0;
output  [31:0] output_real_d0;
input  [31:0] output_real_q0;
output  [6:0] output_imag_address0;
output   output_imag_ce0;
output   output_imag_we0;
output  [31:0] output_imag_d0;
input  [31:0] output_imag_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg[6:0] output_real_address0;
reg output_real_ce0;
reg output_real_we0;
reg[31:0] output_real_d0;
reg[6:0] output_imag_address0;
reg output_imag_ce0;
reg output_imag_we0;
reg[31:0] output_imag_d0;

(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] zmpio_step1_kTwiddleRealQ15_address0;
reg    zmpio_step1_kTwiddleRealQ15_ce0;
wire   [15:0] zmpio_step1_kTwiddleRealQ15_q0;
wire   [5:0] zmpio_step1_kTwiddleImagQ15_address0;
reg    zmpio_step1_kTwiddleImagQ15_ce0;
wire   [15:0] zmpio_step1_kTwiddleImagQ15_q0;
wire   [47:0] grp_fu_258_p2;
reg   [47:0] reg_213;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state22;
wire   [7:0] index_fu_295_p2;
reg   [7:0] index_reg_870;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln39_fu_301_p1;
reg   [63:0] zext_ln39_reg_875;
reg   [31:0] input_load_reg_892;
wire    ap_CS_fsm_state3;
wire   [2:0] add_ln15_fu_317_p2;
wire    ap_CS_fsm_state4;
wire   [6:0] reversed_1_fu_340_p3;
wire   [7:0] trunc_ln43_fu_373_p1;
reg   [7:0] trunc_ln43_reg_916;
wire    ap_CS_fsm_state17;
reg   [6:0] trunc_ln_reg_921;
wire   [5:0] trunc_ln50_fu_385_p1;
reg   [5:0] trunc_ln50_reg_927;
wire   [6:0] trunc_ln46_fu_397_p1;
reg   [6:0] trunc_ln46_reg_935;
wire    ap_CS_fsm_state18;
wire   [6:0] offset_1_fu_416_p2;
reg   [6:0] offset_1_reg_943;
wire    ap_CS_fsm_state19;
wire   [6:0] add_ln48_fu_422_p2;
reg   [6:0] add_ln48_reg_948;
wire   [5:0] add_ln50_1_fu_438_p2;
reg   [5:0] add_ln50_1_reg_953;
reg   [6:0] output_real_addr_2_reg_958;
reg   [6:0] output_imag_addr_2_reg_968;
wire   [7:0] base_1_fu_449_p2;
wire  signed [47:0] sext_ln189_fu_454_p1;
reg  signed [47:0] sext_ln189_reg_983;
wire  signed [47:0] sext_ln27_fu_459_p1;
reg  signed [47:0] sext_ln27_reg_988;
reg   [15:0] zmpio_step1_kTwiddleImagQ15_load_reg_993;
reg   [6:0] output_real_addr_1_reg_998;
wire    ap_CS_fsm_state21;
reg   [6:0] output_imag_addr_1_reg_1003;
wire  signed [47:0] sext_ln56_fu_469_p1;
reg  signed [47:0] sext_ln56_reg_1008;
wire  signed [47:0] sext_ln28_fu_474_p1;
reg  signed [47:0] sext_ln28_reg_1013;
wire   [46:0] trunc_ln26_fu_484_p1;
reg   [46:0] trunc_ln26_reg_1018;
reg   [0:0] tmp_26_reg_1024;
wire   [31:0] select_ln19_2_fu_660_p3;
reg   [31:0] select_ln19_2_reg_1029;
wire   [31:0] odd_imag_fu_724_p3;
reg   [31:0] odd_imag_reg_1034;
wire    ap_CS_fsm_state23;
wire   [31:0] select_ln19_3_fu_852_p3;
reg   [31:0] select_ln19_3_reg_1039;
wire    ap_CS_fsm_state24;
reg   [2:0] bit_reg_202;
wire   [0:0] icmp_ln15_fu_311_p2;
reg   [7:0] base_reg_224;
wire   [0:0] icmp_ln47_fu_411_p2;
reg   [6:0] offset_reg_236;
wire   [0:0] tmp_fu_389_p3;
wire    ap_CS_fsm_state25;
reg   [5:0] index_4_reg_247;
wire   [0:0] icmp_ln39_fu_289_p2;
wire   [63:0] zext_ln15_fu_348_p1;
wire   [63:0] zext_ln50_fu_432_p1;
wire   [63:0] zext_ln21_fu_443_p1;
wire   [63:0] zext_ln48_fu_464_p1;
reg   [7:0] index_3_fu_98;
reg   [8:0] span_fu_102;
wire   [8:0] span_2_fu_401_p2;
wire    ap_CS_fsm_state5;
wire   [31:0] select_ln19_fu_599_p3;
wire   [31:0] select_ln19_1_fu_791_p3;
reg  signed [31:0] grp_fu_258_p0;
reg  signed [15:0] grp_fu_258_p1;
wire   [63:0] zext_ln15_1_fu_323_p1;
wire   [63:0] lshr_ln16_fu_327_p2;
wire   [6:0] trunc_ln16_1_fu_336_p0;
wire   [5:0] trunc_ln16_1_fu_336_p1;
wire   [0:0] trunc_ln16_fu_332_p1;
wire   [6:0] zext_ln15_fu_348_p0;
wire   [5:0] grp_fu_367_p2;
wire   [6:0] add_ln50_fu_427_p2;
wire  signed [31:0] sext_ln189_fu_454_p0;
wire  signed [31:0] sext_ln56_fu_469_p0;
wire   [47:0] real_fu_478_p2;
wire   [46:0] add_ln12_fu_496_p2;
wire   [46:0] sub_ln14_fu_511_p2;
wire   [31:0] trunc_ln4_fu_516_p4;
wire   [31:0] sub_ln14_1_fu_526_p2;
wire   [31:0] trunc_ln3_fu_501_p4;
wire  signed [31:0] sext_ln52_fu_539_p0;
wire   [31:0] odd_real_fu_532_p3;
wire  signed [32:0] sext_ln52_1_fu_543_p1;
wire  signed [32:0] sext_ln52_fu_539_p1;
wire   [32:0] add_ln52_fu_547_p2;
wire   [32:0] add_ln20_fu_561_p2;
wire   [32:0] sub_ln22_fu_577_p2;
wire   [31:0] trunc_ln6_fu_583_p4;
wire   [0:0] tmp_28_fu_553_p3;
wire   [31:0] sub_ln22_1_fu_593_p2;
wire   [31:0] trunc_ln5_fu_567_p4;
wire   [32:0] sub_ln56_fu_608_p2;
wire   [32:0] add_ln20_2_fu_622_p2;
wire   [32:0] sub_ln22_4_fu_638_p2;
wire   [31:0] trunc_ln22_2_fu_644_p4;
wire   [0:0] tmp_30_fu_614_p3;
wire   [31:0] sub_ln22_5_fu_654_p2;
wire   [31:0] trunc_ln20_2_fu_628_p4;
wire   [47:0] imag_fu_668_p2;
wire   [46:0] trunc_ln29_fu_674_p1;
wire   [46:0] add_ln12_1_fu_686_p2;
wire   [46:0] sub_ln14_2_fu_702_p2;
wire   [31:0] trunc_ln14_1_fu_708_p4;
wire   [0:0] tmp_27_fu_678_p3;
wire   [31:0] sub_ln14_3_fu_718_p2;
wire   [31:0] trunc_ln12_1_fu_692_p4;
wire  signed [31:0] sext_ln53_fu_732_p0;
wire  signed [32:0] sext_ln53_1_fu_736_p1;
wire  signed [32:0] sext_ln53_fu_732_p1;
wire   [32:0] add_ln53_fu_739_p2;
wire   [32:0] add_ln20_1_fu_753_p2;
wire   [32:0] sub_ln22_2_fu_769_p2;
wire   [31:0] trunc_ln22_1_fu_775_p4;
wire   [0:0] tmp_29_fu_745_p3;
wire   [31:0] sub_ln22_3_fu_785_p2;
wire   [31:0] trunc_ln20_1_fu_759_p4;
wire   [32:0] sub_ln57_fu_800_p2;
wire   [32:0] add_ln20_3_fu_814_p2;
wire   [32:0] sub_ln22_6_fu_830_p2;
wire   [31:0] trunc_ln22_3_fu_836_p4;
wire   [0:0] tmp_31_fu_806_p3;
wire   [31:0] sub_ln22_7_fu_846_p2;
wire   [31:0] trunc_ln20_3_fu_820_p4;
wire   [0:0] icmp_ln43_fu_361_p2;
reg    grp_fu_367_ap_start;
wire    grp_fu_367_ap_done;
reg   [24:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 25'd1;
#0 index_3_fu_98 = 8'd0;
#0 span_fu_102 = 9'd0;
end

dsp_core_axis_top_fft128_real_zmpio_step1_kTwiddleRealQ15_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
zmpio_step1_kTwiddleRealQ15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(zmpio_step1_kTwiddleRealQ15_address0),
    .ce0(zmpio_step1_kTwiddleRealQ15_ce0),
    .q0(zmpio_step1_kTwiddleRealQ15_q0)
);

dsp_core_axis_top_fft128_real_zmpio_step1_kTwiddleImagQ15_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
zmpio_step1_kTwiddleImagQ15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(zmpio_step1_kTwiddleImagQ15_address0),
    .ce0(zmpio_step1_kTwiddleImagQ15_ce0),
    .q0(zmpio_step1_kTwiddleImagQ15_q0)
);

dsp_core_axis_top_mul_32s_16s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_32s_16s_48_1_1_U1(
    .din0(grp_fu_258_p0),
    .din1(grp_fu_258_p1),
    .dout(grp_fu_258_p2)
);

dsp_core_axis_top_udiv_9ns_9ns_6_13_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 6 ))
udiv_9ns_9ns_6_13_seq_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_367_ap_start),
    .done(grp_fu_367_ap_done),
    .din0(9'd128),
    .din1(span_fu_102),
    .ce(1'b1),
    .dout(grp_fu_367_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln47_fu_411_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        base_reg_224 <= base_1_fu_449_p2;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        base_reg_224 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bit_reg_202 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln15_fu_311_p2 == 1'd0))) begin
        bit_reg_202 <= add_ln15_fu_317_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        index_3_fu_98 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln15_fu_311_p2 == 1'd1))) begin
        index_3_fu_98 <= index_reg_870;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        index_4_reg_247 <= add_ln50_1_reg_953;
    end else if (((tmp_fu_389_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        index_4_reg_247 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        offset_reg_236 <= offset_1_reg_943;
    end else if (((tmp_fu_389_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        offset_reg_236 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        reg_213 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln15_fu_311_p2 == 1'd0))) begin
        reg_213 <= reversed_1_fu_340_p3;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state20))) begin
        reg_213 <= grp_fu_258_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                span_fu_102[1] <= 1'b1;
        span_fu_102[2] <= 1'b0;
        span_fu_102[3] <= 1'b0;
        span_fu_102[4] <= 1'b0;
        span_fu_102[5] <= 1'b0;
        span_fu_102[6] <= 1'b0;
        span_fu_102[7] <= 1'b0;
        span_fu_102[8] <= 1'b0;
    end else if (((tmp_fu_389_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
                span_fu_102[8 : 1] <= span_2_fu_401_p2[8 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        add_ln48_reg_948 <= add_ln48_fu_422_p2;
        add_ln50_1_reg_953 <= add_ln50_1_fu_438_p2;
        offset_1_reg_943 <= offset_1_fu_416_p2;
        output_imag_addr_2_reg_968 <= zext_ln50_fu_432_p1;
        output_real_addr_2_reg_958 <= zext_ln50_fu_432_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        index_reg_870 <= index_fu_295_p2;
        zext_ln39_reg_875[7 : 0] <= zext_ln39_fu_301_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_load_reg_892 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        odd_imag_reg_1034 <= odd_imag_fu_724_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        output_imag_addr_1_reg_1003 <= zext_ln48_fu_464_p1;
        output_real_addr_1_reg_998 <= zext_ln48_fu_464_p1;
        sext_ln28_reg_1013 <= sext_ln28_fu_474_p1;
        sext_ln56_reg_1008 <= sext_ln56_fu_469_p1;
        tmp_26_reg_1024 <= real_fu_478_p2[32'd47];
        trunc_ln26_reg_1018 <= trunc_ln26_fu_484_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        select_ln19_2_reg_1029 <= select_ln19_2_fu_660_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        select_ln19_3_reg_1039 <= select_ln19_3_fu_852_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        sext_ln189_reg_983 <= sext_ln189_fu_454_p1;
        sext_ln27_reg_988 <= sext_ln27_fu_459_p1;
        zmpio_step1_kTwiddleImagQ15_load_reg_993 <= zmpio_step1_kTwiddleImagQ15_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        trunc_ln43_reg_916[7 : 1] <= trunc_ln43_fu_373_p1[7 : 1];
        trunc_ln50_reg_927 <= trunc_ln50_fu_385_p1;
        trunc_ln_reg_921 <= {{span_fu_102[7:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        trunc_ln46_reg_935 <= trunc_ln46_fu_397_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln43_fu_361_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_361_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_258_p0 = sext_ln56_reg_1008;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_258_p0 = sext_ln189_reg_983;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_258_p0 = sext_ln56_fu_469_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_258_p0 = sext_ln189_fu_454_p1;
    end else begin
        grp_fu_258_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_258_p1 = sext_ln27_reg_988;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_258_p1 = sext_ln28_reg_1013;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_258_p1 = sext_ln28_fu_474_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_258_p1 = sext_ln27_fu_459_p1;
    end else begin
        grp_fu_258_p1 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_361_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        grp_fu_367_ap_start = 1'b1;
    end else begin
        grp_fu_367_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23))) begin
        output_imag_address0 = output_imag_addr_1_reg_1003;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state25))) begin
        output_imag_address0 = output_imag_addr_2_reg_968;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_imag_address0 = zext_ln15_fu_348_p1;
    end else begin
        output_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state4))) begin
        output_imag_ce0 = 1'b1;
    end else begin
        output_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        output_imag_d0 = select_ln19_3_reg_1039;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        output_imag_d0 = select_ln19_1_fu_791_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_imag_d0 = 32'd0;
    end else begin
        output_imag_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln15_fu_311_p2 == 1'd1)))) begin
        output_imag_we0 = 1'b1;
    end else begin
        output_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        output_real_address0 = output_real_addr_2_reg_958;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        output_real_address0 = output_real_addr_1_reg_998;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        output_real_address0 = zext_ln48_fu_464_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        output_real_address0 = zext_ln50_fu_432_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_real_address0 = zext_ln15_fu_348_p1;
    end else begin
        output_real_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state4))) begin
        output_real_ce0 = 1'b1;
    end else begin
        output_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        output_real_d0 = select_ln19_2_reg_1029;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        output_real_d0 = select_ln19_fu_599_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_real_d0 = input_load_reg_892;
    end else begin
        output_real_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln15_fu_311_p2 == 1'd1)))) begin
        output_real_we0 = 1'b1;
    end else begin
        output_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        zmpio_step1_kTwiddleImagQ15_ce0 = 1'b1;
    end else begin
        zmpio_step1_kTwiddleImagQ15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        zmpio_step1_kTwiddleRealQ15_ce0 = 1'b1;
    end else begin
        zmpio_step1_kTwiddleRealQ15_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln39_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln15_fu_311_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln43_fu_361_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((tmp_fu_389_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln47_fu_411_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12_1_fu_686_p2 = (trunc_ln29_fu_674_p1 + 47'd16384);

assign add_ln12_fu_496_p2 = (trunc_ln26_reg_1018 + 47'd16384);

assign add_ln15_fu_317_p2 = (bit_reg_202 + 3'd1);

assign add_ln20_1_fu_753_p2 = (add_ln53_fu_739_p2 + 33'd1);

assign add_ln20_2_fu_622_p2 = (sub_ln56_fu_608_p2 + 33'd1);

assign add_ln20_3_fu_814_p2 = (sub_ln57_fu_800_p2 + 33'd1);

assign add_ln20_fu_561_p2 = (add_ln52_fu_547_p2 + 33'd1);

assign add_ln48_fu_422_p2 = (offset_reg_236 + trunc_ln46_reg_935);

assign add_ln50_1_fu_438_p2 = (index_4_reg_247 + trunc_ln50_reg_927);

assign add_ln50_fu_427_p2 = (add_ln48_fu_422_p2 + trunc_ln_reg_921);

assign add_ln52_fu_547_p2 = ($signed(sext_ln52_1_fu_543_p1) + $signed(sext_ln52_fu_539_p1));

assign add_ln53_fu_739_p2 = ($signed(sext_ln53_1_fu_736_p1) + $signed(sext_ln53_fu_732_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign base_1_fu_449_p2 = (trunc_ln43_reg_916 + base_reg_224);

assign icmp_ln15_fu_311_p2 = ((bit_reg_202 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_289_p2 = ((index_3_fu_98 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_361_p2 = ((span_fu_102 < 9'd129) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_411_p2 = ((offset_reg_236 == trunc_ln_reg_921) ? 1'b1 : 1'b0);

assign imag_fu_668_p2 = (reg_213 + grp_fu_258_p2);

assign index_fu_295_p2 = (index_3_fu_98 + 8'd1);

assign input_r_address0 = zext_ln39_fu_301_p1;

assign lshr_ln16_fu_327_p2 = zext_ln39_reg_875 >> zext_ln15_1_fu_323_p1;

assign odd_imag_fu_724_p3 = ((tmp_27_fu_678_p3[0:0] == 1'b1) ? sub_ln14_3_fu_718_p2 : trunc_ln12_1_fu_692_p4);

assign odd_real_fu_532_p3 = ((tmp_26_reg_1024[0:0] == 1'b1) ? sub_ln14_1_fu_526_p2 : trunc_ln3_fu_501_p4);

assign offset_1_fu_416_p2 = (offset_reg_236 + 7'd1);

assign real_fu_478_p2 = (reg_213 - grp_fu_258_p2);

assign reversed_1_fu_340_p3 = {{trunc_ln16_1_fu_336_p1}, {trunc_ln16_fu_332_p1}};

assign select_ln19_1_fu_791_p3 = ((tmp_29_fu_745_p3[0:0] == 1'b1) ? sub_ln22_3_fu_785_p2 : trunc_ln20_1_fu_759_p4);

assign select_ln19_2_fu_660_p3 = ((tmp_30_fu_614_p3[0:0] == 1'b1) ? sub_ln22_5_fu_654_p2 : trunc_ln20_2_fu_628_p4);

assign select_ln19_3_fu_852_p3 = ((tmp_31_fu_806_p3[0:0] == 1'b1) ? sub_ln22_7_fu_846_p2 : trunc_ln20_3_fu_820_p4);

assign select_ln19_fu_599_p3 = ((tmp_28_fu_553_p3[0:0] == 1'b1) ? sub_ln22_1_fu_593_p2 : trunc_ln5_fu_567_p4);

assign sext_ln189_fu_454_p0 = output_real_q0;

assign sext_ln189_fu_454_p1 = sext_ln189_fu_454_p0;

assign sext_ln27_fu_459_p1 = $signed(zmpio_step1_kTwiddleRealQ15_q0);

assign sext_ln28_fu_474_p1 = $signed(zmpio_step1_kTwiddleImagQ15_load_reg_993);

assign sext_ln52_1_fu_543_p1 = $signed(odd_real_fu_532_p3);

assign sext_ln52_fu_539_p0 = output_real_q0;

assign sext_ln52_fu_539_p1 = sext_ln52_fu_539_p0;

assign sext_ln53_1_fu_736_p1 = $signed(odd_imag_reg_1034);

assign sext_ln53_fu_732_p0 = output_imag_q0;

assign sext_ln53_fu_732_p1 = sext_ln53_fu_732_p0;

assign sext_ln56_fu_469_p0 = output_imag_q0;

assign sext_ln56_fu_469_p1 = sext_ln56_fu_469_p0;

assign span_2_fu_401_p2 = span_fu_102 << 9'd1;

assign sub_ln14_1_fu_526_p2 = (32'd0 - trunc_ln4_fu_516_p4);

assign sub_ln14_2_fu_702_p2 = (47'd16384 - trunc_ln29_fu_674_p1);

assign sub_ln14_3_fu_718_p2 = (32'd0 - trunc_ln14_1_fu_708_p4);

assign sub_ln14_fu_511_p2 = (47'd16384 - trunc_ln26_reg_1018);

assign sub_ln22_1_fu_593_p2 = (32'd0 - trunc_ln6_fu_583_p4);

assign sub_ln22_2_fu_769_p2 = (33'd1 - add_ln53_fu_739_p2);

assign sub_ln22_3_fu_785_p2 = (32'd0 - trunc_ln22_1_fu_775_p4);

assign sub_ln22_4_fu_638_p2 = (33'd1 - sub_ln56_fu_608_p2);

assign sub_ln22_5_fu_654_p2 = (32'd0 - trunc_ln22_2_fu_644_p4);

assign sub_ln22_6_fu_830_p2 = (33'd1 - sub_ln57_fu_800_p2);

assign sub_ln22_7_fu_846_p2 = (32'd0 - trunc_ln22_3_fu_836_p4);

assign sub_ln22_fu_577_p2 = (33'd1 - add_ln52_fu_547_p2);

assign sub_ln56_fu_608_p2 = ($signed(sext_ln52_fu_539_p1) - $signed(sext_ln52_1_fu_543_p1));

assign sub_ln57_fu_800_p2 = ($signed(sext_ln53_fu_732_p1) - $signed(sext_ln53_1_fu_736_p1));

assign tmp_27_fu_678_p3 = imag_fu_668_p2[32'd47];

assign tmp_28_fu_553_p3 = add_ln52_fu_547_p2[32'd32];

assign tmp_29_fu_745_p3 = add_ln53_fu_739_p2[32'd32];

assign tmp_30_fu_614_p3 = sub_ln56_fu_608_p2[32'd32];

assign tmp_31_fu_806_p3 = sub_ln57_fu_800_p2[32'd32];

assign tmp_fu_389_p3 = base_reg_224[32'd7];

assign trunc_ln12_1_fu_692_p4 = {{add_ln12_1_fu_686_p2[46:15]}};

assign trunc_ln14_1_fu_708_p4 = {{sub_ln14_2_fu_702_p2[46:15]}};

assign trunc_ln16_1_fu_336_p0 = reg_213;

assign trunc_ln16_1_fu_336_p1 = trunc_ln16_1_fu_336_p0[5:0];

assign trunc_ln16_fu_332_p1 = lshr_ln16_fu_327_p2[0:0];

assign trunc_ln20_1_fu_759_p4 = {{add_ln20_1_fu_753_p2[32:1]}};

assign trunc_ln20_2_fu_628_p4 = {{add_ln20_2_fu_622_p2[32:1]}};

assign trunc_ln20_3_fu_820_p4 = {{add_ln20_3_fu_814_p2[32:1]}};

assign trunc_ln22_1_fu_775_p4 = {{sub_ln22_2_fu_769_p2[32:1]}};

assign trunc_ln22_2_fu_644_p4 = {{sub_ln22_4_fu_638_p2[32:1]}};

assign trunc_ln22_3_fu_836_p4 = {{sub_ln22_6_fu_830_p2[32:1]}};

assign trunc_ln26_fu_484_p1 = real_fu_478_p2[46:0];

assign trunc_ln29_fu_674_p1 = imag_fu_668_p2[46:0];

assign trunc_ln3_fu_501_p4 = {{add_ln12_fu_496_p2[46:15]}};

assign trunc_ln43_fu_373_p1 = span_fu_102[7:0];

assign trunc_ln46_fu_397_p1 = base_reg_224[6:0];

assign trunc_ln4_fu_516_p4 = {{sub_ln14_fu_511_p2[46:15]}};

assign trunc_ln50_fu_385_p1 = grp_fu_367_p2[5:0];

assign trunc_ln5_fu_567_p4 = {{add_ln20_fu_561_p2[32:1]}};

assign trunc_ln6_fu_583_p4 = {{sub_ln22_fu_577_p2[32:1]}};

assign zext_ln15_1_fu_323_p1 = bit_reg_202;

assign zext_ln15_fu_348_p0 = reg_213;

assign zext_ln15_fu_348_p1 = zext_ln15_fu_348_p0;

assign zext_ln21_fu_443_p1 = index_4_reg_247;

assign zext_ln39_fu_301_p1 = index_3_fu_98;

assign zext_ln48_fu_464_p1 = add_ln48_reg_948;

assign zext_ln50_fu_432_p1 = add_ln50_fu_427_p2;

assign zmpio_step1_kTwiddleImagQ15_address0 = zext_ln21_fu_443_p1;

assign zmpio_step1_kTwiddleRealQ15_address0 = zext_ln21_fu_443_p1;

always @ (posedge ap_clk) begin
    zext_ln39_reg_875[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    trunc_ln43_reg_916[0] <= 1'b0;
    span_fu_102[0] <= 1'b0;
end

endmodule //dsp_core_axis_top_fft128_real
