domain_path: <ZMPIO_ROOT>\firmware\platform_dual\export\platform_dual\sw\free_rtos
app_src_dir: <VITIS_ROOT_PARENT>\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
