#!/usr/bin/env python3
"""Step 4 (docs/ROADMAP_DETAIL.md) -- regenerate
common/zmpio_abi_v3_layout_hash.h from the field/offset/size list below.

This script does NOT parse common/zmpio_abi_v3.h -- there is no C struct
parser here, so SPEC below must be kept in sync BY HAND with that header
every time an ABI-relevant field, size, or enum value changes. That is a
deliberate simplification (see the SDD for Step 4): the hash's job is only to
catch a REBUILD-ONLY-ONE-SIDE mistake (stale CPU0 or CPU1 ELF talking ABI v3
to a freshly rebuilt peer), not to be a source of truth for the layout.

Usage:
    python tools/gen_layout_hash.py            # regenerate the header
    python tools/gen_layout_hash.py --check    # exit 1 if the header is stale

The CRC32 used here (Python's zlib.crc32) is bit-for-bit the same algorithm
as common/zmpio_crc32.c: poly 0xEDB88320, init/xorout 0xFFFFFFFF -- this
script does not need to reimplement it.
"""
import argparse
import pathlib
import sys
import zlib

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT_HEADER = REPO_ROOT / "common" / "zmpio_abi_v3_layout_hash.h"

# (name, offset, size) for every field of every ABI v3 struct, in declaration
# order, plus the magic/version/enum constants that are part of the wire
# contract even though they are not struct fields. Must match
# common/zmpio_abi_v3.h exactly.
SPEC = [
    ("ZMPIO_ABI_V3_MAGIC", 0, 0x5A4D5033),
    ("ZMPIO_ABI_V3_VERSION", 0, 3),
    ("ZMPIO_ABI_V3_CMD_SLOTS", 0, 16),
    ("ZMPIO_ABI_V3_RSP_SLOTS", 0, 16),
    ("ZMPIO_ABI_V3_CMD_PAYLOAD_SIZE", 0, 64),
    ("ZMPIO_ABI_V3_RSP_PAYLOAD_SIZE", 0, 64),
    ("ZMPIO_ABI_V3_FEATURE_COUNT", 0, 10),
    ("ZMPIO_V3_CMD_HELLO", 0, 1),
    ("ZMPIO_V3_CMD_SET_DSP_CONFIG", 0, 2),
    ("ZMPIO_V3_CMD_DSP_SOFT_RESET", 0, 3),
    ("ZMPIO_V3_CMD_FIFO_FULL_INJECT", 0, 4),
    ("ZMPIO_V3_RSP_HELLO_ACK", 0, 1),
    ("ZMPIO_V3_RSP_CONFIG_ACK", 0, 2),
    ("ZMPIO_V3_RSP_CONFIG_NACK", 0, 3),
    ("ZMPIO_V3_RSP_DSP_SOFT_RESET_ACK", 0, 4),
    ("ZMPIO_V3_RSP_FIFO_FULL_INJECT_ACK", 0, 5),
    ("ZMPIO_V3_LINK_CPU1_NOT_READY", 0, 0),
    ("ZMPIO_V3_LINK_CPU1_READY", 0, 1),
    ("ZMPIO_V3_LINK_ONLINE", 0, 2),
    # zmpio_v3_cmd_slot_t fields (offset, size in bytes)
    ("cmd.type", 0, 4),
    ("cmd.correlation_id", 4, 4),
    ("cmd.session_id", 8, 4),
    ("cmd.payload_len", 12, 4),
    ("cmd.payload", 16, 64),
    ("cmd.crc32", 80, 4),
    ("sizeof(cmd_slot)", 0, 84),
    # zmpio_v3_rsp_slot_t fields
    ("rsp.type", 0, 4),
    ("rsp.correlation_id", 4, 4),
    ("rsp.session_id", 8, 4),
    ("rsp.status", 12, 4),
    ("rsp.payload_len", 16, 4),
    ("rsp.payload", 20, 64),
    ("rsp.crc32", 84, 4),
    ("sizeof(rsp_slot)", 0, 88),
    # zmpio_v3_control_t fields
    ("ctrl.magic", 0, 4),
    ("ctrl.abi_version", 4, 4),
    ("ctrl.layout_hash", 8, 4),
    ("ctrl.cpu1_link_state", 12, 4),
    ("ctrl.session_id", 16, 4),
    ("ctrl.cmd_head", 20, 4),
    ("ctrl.cmd_tail", 24, 4),
    ("ctrl.rsp_head", 28, 4),
    ("ctrl.rsp_tail", 32, 4),
    ("ctrl.cmd_ring_size", 36, 4),
    ("ctrl.rsp_ring_size", 40, 4),
    ("ctrl.cpu1_crc_drop_count", 44, 4),
    ("ctrl.cpu0_crc_drop_count", 48, 4),
    ("sizeof(control)", 0, 52),
    # zmpio_v3_set_dsp_config_t fields (a command payload, not the slot itself)
    ("set_dsp_config.coeff_set_id", 0, 4),
    ("set_dsp_config.fft_scale_shift", 4, 4),
    ("set_dsp_config.feature_mask", 8, 4),
    ("sizeof(set_dsp_config)", 0, 12),
    # zmpio_v3_dsp_soft_reset_ack_t fields (a response payload)
    ("dsp_soft_reset_ack.feature_count_before", 0, 4),
    ("dsp_soft_reset_ack.drop_count_before", 4, 4),
    ("sizeof(dsp_soft_reset_ack)", 0, 8),
]

HEADER_TEMPLATE = """#ifndef ZMPIO_ABI_V3_LAYOUT_HASH_H
#define ZMPIO_ABI_V3_LAYOUT_HASH_H

/* Generated by tools/gen_layout_hash.py -- do not hand edit.
 * Re-run `python tools/gen_layout_hash.py` after changing any ABI-relevant
 * field, size, or enum value in common/zmpio_abi_v3.h (and update that
 * script's SPEC list to match first). */
#define ZMPIO_ABI_V3_LAYOUT_HASH {hash_value}U

#endif
"""


def compute_hash() -> int:
    serialized = "\n".join(f"{name}:{offset}:{size}" for name, offset, size in SPEC)
    return zlib.crc32(serialized.encode("ascii")) & 0xFFFFFFFF


def render_header(hash_value: int) -> str:
    return HEADER_TEMPLATE.format(hash_value=f"0x{hash_value:08X}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                         help="exit 1 if the on-disk header is stale instead of rewriting it")
    args = parser.parse_args()

    hash_value = compute_hash()
    rendered = render_header(hash_value)

    if args.check:
        current = OUTPUT_HEADER.read_text() if OUTPUT_HEADER.exists() else ""
        if current != rendered:
            print(f"STALE: {OUTPUT_HEADER} does not match SPEC (expected hash 0x{hash_value:08X})")
            return 1
        print(f"OK: {OUTPUT_HEADER} matches SPEC (hash 0x{hash_value:08X})")
        return 0

    OUTPUT_HEADER.write_text(rendered)
    print(f"Wrote {OUTPUT_HEADER} with ZMPIO_ABI_V3_LAYOUT_HASH=0x{hash_value:08X}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
